// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BusIdCounterHandle : RemoteTableHandle<EventContext, BusIdCounter>
        {
            protected override string RemoteTableName => "bus_id_counter";

            public sealed class KeyUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(BusIdCounter row) => row.Key;

                public KeyUniqueIndex(BusIdCounterHandle table) : base(table) { }
            }

            public readonly KeyUniqueIndex Key;

            internal BusIdCounterHandle(DbConnection conn) : base(conn)
            {
                Key = new(this);
            }

            protected override object GetPrimaryKey(BusIdCounter row) => row.Key;
        }

        public readonly BusIdCounterHandle BusIdCounter;
    }

    public sealed class BusIdCounterCols
    {
        public global::SpacetimeDB.Col<BusIdCounter, string> Key { get; }
        public global::SpacetimeDB.Col<BusIdCounter, uint> NextId { get; }

        public BusIdCounterCols(string tableName)
        {
            Key = new global::SpacetimeDB.Col<BusIdCounter, string>(tableName, "key");
            NextId = new global::SpacetimeDB.Col<BusIdCounter, uint>(tableName, "next_id");
        }
    }

    public sealed class BusIdCounterIxCols
    {
        public global::SpacetimeDB.IxCol<BusIdCounter, string> Key { get; }

        public BusIdCounterIxCols(string tableName)
        {
            Key = new global::SpacetimeDB.IxCol<BusIdCounter, string>(tableName, "key");
        }
    }
}
