// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BusLocationHandle : RemoteTableHandle<EventContext, BusLocation>
        {
            protected override string RemoteTableName => "bus_location";

            public sealed class LocationIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(BusLocation row) => row.LocationId;

                public LocationIdUniqueIndex(BusLocationHandle table) : base(table) { }
            }

            public readonly LocationIdUniqueIndex LocationId;

            internal BusLocationHandle(DbConnection conn) : base(conn)
            {
                LocationId = new(this);
            }

            protected override object GetPrimaryKey(BusLocation row) => row.LocationId;
        }

        public readonly BusLocationHandle BusLocation;
    }

    public sealed class BusLocationCols
    {
        public global::SpacetimeDB.Col<BusLocation, uint> LocationId { get; }
        public global::SpacetimeDB.Col<BusLocation, uint> BusId { get; }
        public global::SpacetimeDB.Col<BusLocation, double> Latitude { get; }
        public global::SpacetimeDB.Col<BusLocation, double> Longitude { get; }
        public global::SpacetimeDB.Col<BusLocation, ulong> Timestamp { get; }
        public global::SpacetimeDB.NullableCol<BusLocation, uint> RouteId { get; }
        public global::SpacetimeDB.NullableCol<BusLocation, uint> ScheduleId { get; }
        public global::SpacetimeDB.NullableCol<BusLocation, double> Speed { get; }
        public global::SpacetimeDB.NullableCol<BusLocation, double> Heading { get; }
        public global::SpacetimeDB.NullableCol<BusLocation, string> Status { get; }
        public global::SpacetimeDB.NullableCol<BusLocation, uint> NextStopId { get; }
        public global::SpacetimeDB.NullableCol<BusLocation, ulong> EstimatedArrivalTime { get; }
        public global::SpacetimeDB.NullableCol<BusLocation, bool> IsDelayed { get; }
        public global::SpacetimeDB.NullableCol<BusLocation, uint> DelayMinutes { get; }
        public global::SpacetimeDB.NullableCol<BusLocation, string> DelayReason { get; }

        public BusLocationCols(string tableName)
        {
            LocationId = new global::SpacetimeDB.Col<BusLocation, uint>(tableName, "location_id");
            BusId = new global::SpacetimeDB.Col<BusLocation, uint>(tableName, "bus_id");
            Latitude = new global::SpacetimeDB.Col<BusLocation, double>(tableName, "latitude");
            Longitude = new global::SpacetimeDB.Col<BusLocation, double>(tableName, "longitude");
            Timestamp = new global::SpacetimeDB.Col<BusLocation, ulong>(tableName, "timestamp");
            RouteId = new global::SpacetimeDB.NullableCol<BusLocation, uint>(tableName, "route_id");
            ScheduleId = new global::SpacetimeDB.NullableCol<BusLocation, uint>(tableName, "schedule_id");
            Speed = new global::SpacetimeDB.NullableCol<BusLocation, double>(tableName, "speed");
            Heading = new global::SpacetimeDB.NullableCol<BusLocation, double>(tableName, "heading");
            Status = new global::SpacetimeDB.NullableCol<BusLocation, string>(tableName, "status");
            NextStopId = new global::SpacetimeDB.NullableCol<BusLocation, uint>(tableName, "next_stop_id");
            EstimatedArrivalTime = new global::SpacetimeDB.NullableCol<BusLocation, ulong>(tableName, "estimated_arrival_time");
            IsDelayed = new global::SpacetimeDB.NullableCol<BusLocation, bool>(tableName, "is_delayed");
            DelayMinutes = new global::SpacetimeDB.NullableCol<BusLocation, uint>(tableName, "delay_minutes");
            DelayReason = new global::SpacetimeDB.NullableCol<BusLocation, string>(tableName, "delay_reason");
        }
    }

    public sealed class BusLocationIxCols
    {
        public global::SpacetimeDB.IxCol<BusLocation, uint> LocationId { get; }

        public BusLocationIxCols(string tableName)
        {
            LocationId = new global::SpacetimeDB.IxCol<BusLocation, uint>(tableName, "location_id");
        }
    }
}
