// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BusStatusEventHandle : RemoteEventTableHandle<EventContext, BusStatusEvent>
        {
            protected override string RemoteTableName => "bus_status_event";

            internal BusStatusEventHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly BusStatusEventHandle BusStatusEvent;
    }

    public sealed class BusStatusEventCols
    {
        public global::SpacetimeDB.Col<BusStatusEvent, uint> BusId { get; }
        public global::SpacetimeDB.Col<BusStatusEvent, string> PreviousStatus { get; }
        public global::SpacetimeDB.Col<BusStatusEvent, string> NewStatus { get; }
        public global::SpacetimeDB.Col<BusStatusEvent, ulong> Timestamp { get; }
        public global::SpacetimeDB.Col<BusStatusEvent, SpacetimeDB.Identity> ChangedBy { get; }
        public global::SpacetimeDB.Col<BusStatusEvent, string> Reason { get; }

        public BusStatusEventCols(string tableName)
        {
            BusId = new global::SpacetimeDB.Col<BusStatusEvent, uint>(tableName, "bus_id");
            PreviousStatus = new global::SpacetimeDB.Col<BusStatusEvent, string>(tableName, "previous_status");
            NewStatus = new global::SpacetimeDB.Col<BusStatusEvent, string>(tableName, "new_status");
            Timestamp = new global::SpacetimeDB.Col<BusStatusEvent, ulong>(tableName, "timestamp");
            ChangedBy = new global::SpacetimeDB.Col<BusStatusEvent, SpacetimeDB.Identity>(tableName, "changed_by");
            Reason = new global::SpacetimeDB.Col<BusStatusEvent, string>(tableName, "reason");
        }
    }

    public sealed class BusStatusEventIxCols
    {

        public BusStatusEventIxCols(string tableName)
        {
        }
    }
}
