// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EmployeeShiftHandle : RemoteTableHandle<EventContext, EmployeeShift>
        {
            protected override string RemoteTableName => "EmployeeShift";

            public sealed class ShiftIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(EmployeeShift row) => row.ShiftId;

                public ShiftIdUniqueIndex(EmployeeShiftHandle table) : base(table) { }
            }

            public readonly ShiftIdUniqueIndex ShiftId;

            internal EmployeeShiftHandle(DbConnection conn) : base(conn)
            {
                ShiftId = new(this);
            }

            protected override object GetPrimaryKey(EmployeeShift row) => row.ShiftId;
        }

        public readonly EmployeeShiftHandle EmployeeShift;
    }
}
