// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EmployeeIdCounterHandle : RemoteTableHandle<EventContext, EmployeeIdCounter>
        {
            protected override string RemoteTableName => "EmployeeIdCounter";

            public sealed class KeyUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(EmployeeIdCounter row) => row.Key;

                public KeyUniqueIndex(EmployeeIdCounterHandle table) : base(table) { }
            }

            public readonly KeyUniqueIndex Key;

            internal EmployeeIdCounterHandle(DbConnection conn) : base(conn)
            {
                Key = new(this);
            }

            protected override object GetPrimaryKey(EmployeeIdCounter row) => row.Key;
        }

        public readonly EmployeeIdCounterHandle EmployeeIdCounter;
    }
}
