// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class FuelRecordHandle : RemoteTableHandle<EventContext, FuelRecord>
        {
            protected override string RemoteTableName => "FuelRecord";

            public sealed class FuelRecordIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(FuelRecord row) => row.FuelRecordId;

                public FuelRecordIdUniqueIndex(FuelRecordHandle table) : base(table) { }
            }

            public readonly FuelRecordIdUniqueIndex FuelRecordId;

            internal FuelRecordHandle(DbConnection conn) : base(conn)
            {
                FuelRecordId = new(this);
            }

            protected override object GetPrimaryKey(FuelRecord row) => row.FuelRecordId;
        }

        public readonly FuelRecordHandle FuelRecord;
    }
}
