// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class FuelRecordHandle : RemoteTableHandle<EventContext, FuelRecord>
        {
            protected override string RemoteTableName => "fuel_record";

            public sealed class FuelRecordIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(FuelRecord row) => row.FuelRecordId;

                public FuelRecordIdUniqueIndex(FuelRecordHandle table) : base(table) { }
            }

            public readonly FuelRecordIdUniqueIndex FuelRecordId;

            internal FuelRecordHandle(DbConnection conn) : base(conn)
            {
                FuelRecordId = new(this);
            }

            protected override object GetPrimaryKey(FuelRecord row) => row.FuelRecordId;
        }

        public readonly FuelRecordHandle FuelRecord;
    }

    public sealed class FuelRecordCols
    {
        public global::SpacetimeDB.Col<FuelRecord, uint> FuelRecordId { get; }
        public global::SpacetimeDB.Col<FuelRecord, uint> BusId { get; }
        public global::SpacetimeDB.Col<FuelRecord, ulong> Date { get; }
        public global::SpacetimeDB.Col<FuelRecord, double> Amount { get; }
        public global::SpacetimeDB.Col<FuelRecord, double> Cost { get; }
        public global::SpacetimeDB.Col<FuelRecord, double> Odometer { get; }
        public global::SpacetimeDB.NullableCol<FuelRecord, string> FuelType { get; }
        public global::SpacetimeDB.NullableCol<FuelRecord, string> FuelStation { get; }
        public global::SpacetimeDB.NullableCol<FuelRecord, uint> EmployeeId { get; }
        public global::SpacetimeDB.NullableCol<FuelRecord, string> Notes { get; }
        public global::SpacetimeDB.NullableCol<FuelRecord, double> FuelEconomy { get; }
        public global::SpacetimeDB.NullableCol<FuelRecord, double> PreviousOdometer { get; }
        public global::SpacetimeDB.NullableCol<FuelRecord, double> Distance { get; }

        public FuelRecordCols(string tableName)
        {
            FuelRecordId = new global::SpacetimeDB.Col<FuelRecord, uint>(tableName, "fuel_record_id");
            BusId = new global::SpacetimeDB.Col<FuelRecord, uint>(tableName, "bus_id");
            Date = new global::SpacetimeDB.Col<FuelRecord, ulong>(tableName, "date");
            Amount = new global::SpacetimeDB.Col<FuelRecord, double>(tableName, "amount");
            Cost = new global::SpacetimeDB.Col<FuelRecord, double>(tableName, "cost");
            Odometer = new global::SpacetimeDB.Col<FuelRecord, double>(tableName, "odometer");
            FuelType = new global::SpacetimeDB.NullableCol<FuelRecord, string>(tableName, "fuel_type");
            FuelStation = new global::SpacetimeDB.NullableCol<FuelRecord, string>(tableName, "fuel_station");
            EmployeeId = new global::SpacetimeDB.NullableCol<FuelRecord, uint>(tableName, "employee_id");
            Notes = new global::SpacetimeDB.NullableCol<FuelRecord, string>(tableName, "notes");
            FuelEconomy = new global::SpacetimeDB.NullableCol<FuelRecord, double>(tableName, "fuel_economy");
            PreviousOdometer = new global::SpacetimeDB.NullableCol<FuelRecord, double>(tableName, "previous_odometer");
            Distance = new global::SpacetimeDB.NullableCol<FuelRecord, double>(tableName, "distance");
        }
    }

    public sealed class FuelRecordIxCols
    {
        public global::SpacetimeDB.IxCol<FuelRecord, uint> FuelRecordId { get; }

        public FuelRecordIxCols(string tableName)
        {
            FuelRecordId = new global::SpacetimeDB.IxCol<FuelRecord, uint>(tableName, "fuel_record_id");
        }
    }
}
