// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class JobIdCounterHandle : RemoteTableHandle<EventContext, JobIdCounter>
        {
            protected override string RemoteTableName => "JobIdCounter";

            public sealed class KeyUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(JobIdCounter row) => row.Key;

                public KeyUniqueIndex(JobIdCounterHandle table) : base(table) { }
            }

            public readonly KeyUniqueIndex Key;

            internal JobIdCounterHandle(DbConnection conn) : base(conn)
            {
                Key = new(this);
            }

            protected override object GetPrimaryKey(JobIdCounter row) => row.Key;
        }

        public readonly JobIdCounterHandle JobIdCounter;
    }
}
