// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MaintenanceIdCounterHandle : RemoteTableHandle<EventContext, MaintenanceIdCounter>
        {
            protected override string RemoteTableName => "maintenance_id_counter";

            public sealed class KeyUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(MaintenanceIdCounter row) => row.Key;

                public KeyUniqueIndex(MaintenanceIdCounterHandle table) : base(table) { }
            }

            public readonly KeyUniqueIndex Key;

            internal MaintenanceIdCounterHandle(DbConnection conn) : base(conn)
            {
                Key = new(this);
            }

            protected override object GetPrimaryKey(MaintenanceIdCounter row) => row.Key;
        }

        public readonly MaintenanceIdCounterHandle MaintenanceIdCounter;
    }

    public sealed class MaintenanceIdCounterCols
    {
        public global::SpacetimeDB.Col<MaintenanceIdCounter, string> Key { get; }
        public global::SpacetimeDB.Col<MaintenanceIdCounter, uint> NextId { get; }

        public MaintenanceIdCounterCols(string tableName)
        {
            Key = new global::SpacetimeDB.Col<MaintenanceIdCounter, string>(tableName, "key");
            NextId = new global::SpacetimeDB.Col<MaintenanceIdCounter, uint>(tableName, "next_id");
        }
    }

    public sealed class MaintenanceIdCounterIxCols
    {
        public global::SpacetimeDB.IxCol<MaintenanceIdCounter, string> Key { get; }

        public MaintenanceIdCounterIxCols(string tableName)
        {
            Key = new global::SpacetimeDB.IxCol<MaintenanceIdCounter, string>(tableName, "key");
        }
    }
}
