// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class OpenIdConnectGrantHandle : RemoteTableHandle<EventContext, OpenIdConnectGrant>
        {
            protected override string RemoteTableName => "open_id_connect_grant";

            public sealed class GrantIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(OpenIdConnectGrant row) => row.GrantId;

                public GrantIdUniqueIndex(OpenIdConnectGrantHandle table) : base(table) { }
            }

            public readonly GrantIdUniqueIndex GrantId;

            internal OpenIdConnectGrantHandle(DbConnection conn) : base(conn)
            {
                GrantId = new(this);
            }

            protected override object GetPrimaryKey(OpenIdConnectGrant row) => row.GrantId;
        }

        public readonly OpenIdConnectGrantHandle OpenIdConnectGrant;
    }

    public sealed class OpenIdConnectGrantCols
    {
        public global::SpacetimeDB.Col<OpenIdConnectGrant, string> GrantId { get; }
        public global::SpacetimeDB.Col<OpenIdConnectGrant, string> ClientId { get; }
        public global::SpacetimeDB.Col<OpenIdConnectGrant, SpacetimeDB.Identity> UserId { get; }
        public global::SpacetimeDB.Col<OpenIdConnectGrant, string> Type { get; }
        public global::SpacetimeDB.Col<OpenIdConnectGrant, System.Collections.Generic.List<string>> Scopes { get; }
        public global::SpacetimeDB.Col<OpenIdConnectGrant, ulong> CreatedAt { get; }
        public global::SpacetimeDB.Col<OpenIdConnectGrant, ulong> ExpiresAt { get; }
        public global::SpacetimeDB.Col<OpenIdConnectGrant, bool> IsRevoked { get; }

        public OpenIdConnectGrantCols(string tableName)
        {
            GrantId = new global::SpacetimeDB.Col<OpenIdConnectGrant, string>(tableName, "grant_id");
            ClientId = new global::SpacetimeDB.Col<OpenIdConnectGrant, string>(tableName, "client_id");
            UserId = new global::SpacetimeDB.Col<OpenIdConnectGrant, SpacetimeDB.Identity>(tableName, "user_id");
            Type = new global::SpacetimeDB.Col<OpenIdConnectGrant, string>(tableName, "type");
            Scopes = new global::SpacetimeDB.Col<OpenIdConnectGrant, System.Collections.Generic.List<string>>(tableName, "scopes");
            CreatedAt = new global::SpacetimeDB.Col<OpenIdConnectGrant, ulong>(tableName, "created_at");
            ExpiresAt = new global::SpacetimeDB.Col<OpenIdConnectGrant, ulong>(tableName, "expires_at");
            IsRevoked = new global::SpacetimeDB.Col<OpenIdConnectGrant, bool>(tableName, "is_revoked");
        }
    }

    public sealed class OpenIdConnectGrantIxCols
    {
        public global::SpacetimeDB.IxCol<OpenIdConnectGrant, string> GrantId { get; }

        public OpenIdConnectGrantIxCols(string tableName)
        {
            GrantId = new global::SpacetimeDB.IxCol<OpenIdConnectGrant, string>(tableName, "grant_id");
        }
    }
}
