// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class OpenIddictSpacetimeTokenHandle : RemoteTableHandle<EventContext, OpenIddictSpacetimeToken>
        {
            protected override string RemoteTableName => "OpenIddictSpacetimeToken";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(OpenIddictSpacetimeToken row) => row.Id;

                public IdUniqueIndex(OpenIddictSpacetimeTokenHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal OpenIddictSpacetimeTokenHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(OpenIddictSpacetimeToken row) => row.Id;
        }

        public readonly OpenIddictSpacetimeTokenHandle OpenIddictSpacetimeToken;
    }
}
