// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class OpenIddictSpacetimeTokenHandle : RemoteTableHandle<EventContext, OpenIddictSpacetimeToken>
        {
<<<<<<< HEAD
            protected override string RemoteTableName => "OpenIddictSpacetimeToken";
=======
            protected override string RemoteTableName => "open_iddict_spacetime_token";
>>>>>>> maintofix

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(OpenIddictSpacetimeToken row) => row.Id;

                public IdUniqueIndex(OpenIddictSpacetimeTokenHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal OpenIddictSpacetimeTokenHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(OpenIddictSpacetimeToken row) => row.Id;
        }

        public readonly OpenIddictSpacetimeTokenHandle OpenIddictSpacetimeToken;
    }
<<<<<<< HEAD
=======

    public sealed class OpenIddictSpacetimeTokenCols
    {
        public global::SpacetimeDB.Col<OpenIddictSpacetimeToken, uint> Id { get; }
        public global::SpacetimeDB.Col<OpenIddictSpacetimeToken, string> OpenIddictTokenId { get; }
        public global::SpacetimeDB.NullableCol<OpenIddictSpacetimeToken, uint> AuthorizationId { get; }
        public global::SpacetimeDB.NullableCol<OpenIddictSpacetimeToken, string> ApplicationClientId { get; }
        public global::SpacetimeDB.NullableCol<OpenIddictSpacetimeToken, ulong> CreationDate { get; }
        public global::SpacetimeDB.NullableCol<OpenIddictSpacetimeToken, ulong> ExpirationDate { get; }
        public global::SpacetimeDB.NullableCol<OpenIddictSpacetimeToken, string> Payload { get; }
        public global::SpacetimeDB.NullableCol<OpenIddictSpacetimeToken, string> Properties { get; }
        public global::SpacetimeDB.NullableCol<OpenIddictSpacetimeToken, ulong> RedemptionDate { get; }
        public global::SpacetimeDB.NullableCol<OpenIddictSpacetimeToken, string> ReferenceId { get; }
        public global::SpacetimeDB.NullableCol<OpenIddictSpacetimeToken, string> Status { get; }
        public global::SpacetimeDB.NullableCol<OpenIddictSpacetimeToken, string> Subject { get; }
        public global::SpacetimeDB.NullableCol<OpenIddictSpacetimeToken, string> Type { get; }

        public OpenIddictSpacetimeTokenCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<OpenIddictSpacetimeToken, uint>(tableName, "id");
            OpenIddictTokenId = new global::SpacetimeDB.Col<OpenIddictSpacetimeToken, string>(tableName, "open_iddict_token_id");
            AuthorizationId = new global::SpacetimeDB.NullableCol<OpenIddictSpacetimeToken, uint>(tableName, "authorization_id");
            ApplicationClientId = new global::SpacetimeDB.NullableCol<OpenIddictSpacetimeToken, string>(tableName, "application_client_id");
            CreationDate = new global::SpacetimeDB.NullableCol<OpenIddictSpacetimeToken, ulong>(tableName, "creation_date");
            ExpirationDate = new global::SpacetimeDB.NullableCol<OpenIddictSpacetimeToken, ulong>(tableName, "expiration_date");
            Payload = new global::SpacetimeDB.NullableCol<OpenIddictSpacetimeToken, string>(tableName, "payload");
            Properties = new global::SpacetimeDB.NullableCol<OpenIddictSpacetimeToken, string>(tableName, "properties");
            RedemptionDate = new global::SpacetimeDB.NullableCol<OpenIddictSpacetimeToken, ulong>(tableName, "redemption_date");
            ReferenceId = new global::SpacetimeDB.NullableCol<OpenIddictSpacetimeToken, string>(tableName, "reference_id");
            Status = new global::SpacetimeDB.NullableCol<OpenIddictSpacetimeToken, string>(tableName, "status");
            Subject = new global::SpacetimeDB.NullableCol<OpenIddictSpacetimeToken, string>(tableName, "subject");
            Type = new global::SpacetimeDB.NullableCol<OpenIddictSpacetimeToken, string>(tableName, "type");
        }
    }

    public sealed class OpenIddictSpacetimeTokenIxCols
    {
        public global::SpacetimeDB.IxCol<OpenIddictSpacetimeToken, uint> Id { get; }

        public OpenIddictSpacetimeTokenIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<OpenIddictSpacetimeToken, uint>(tableName, "id");
        }
    }
>>>>>>> maintofix
}
