// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PassengerCountHandle : RemoteTableHandle<EventContext, PassengerCount>
        {
            protected override string RemoteTableName => "PassengerCount";

            public sealed class PassengerCountIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(PassengerCount row) => row.PassengerCountId;

                public PassengerCountIdUniqueIndex(PassengerCountHandle table) : base(table) { }
            }

            public readonly PassengerCountIdUniqueIndex PassengerCountId;

            internal PassengerCountHandle(DbConnection conn) : base(conn)
            {
                PassengerCountId = new(this);
            }

            protected override object GetPrimaryKey(PassengerCount row) => row.PassengerCountId;
        }

        public readonly PassengerCountHandle PassengerCount;
    }
}
