// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PassengerHandle : RemoteTableHandle<EventContext, Passenger>
        {
            protected override string RemoteTableName => "Passenger";

            public sealed class PassengerIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Passenger row) => row.PassengerId;

                public PassengerIdUniqueIndex(PassengerHandle table) : base(table) { }
            }

            public readonly PassengerIdUniqueIndex PassengerId;

            internal PassengerHandle(DbConnection conn) : base(conn)
            {
                PassengerId = new(this);
            }

            protected override object GetPrimaryKey(Passenger row) => row.PassengerId;
        }

        public readonly PassengerHandle Passenger;
    }
}
