// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PermissionIdCounterHandle : RemoteTableHandle<EventContext, PermissionIdCounter>
        {
            protected override string RemoteTableName => "PermissionIdCounter";

            public sealed class KeyUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(PermissionIdCounter row) => row.Key;

                public KeyUniqueIndex(PermissionIdCounterHandle table) : base(table) { }
            }

            public readonly KeyUniqueIndex Key;

            internal PermissionIdCounterHandle(DbConnection conn) : base(conn)
            {
                Key = new(this);
            }

            protected override object GetPrimaryKey(PermissionIdCounter row) => row.Key;
        }

        public readonly PermissionIdCounterHandle PermissionIdCounter;
    }
}
