// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class QrSessionHandle : RemoteTableHandle<EventContext, QrSession>
        {
            protected override string RemoteTableName => "QRSession";

            public sealed class SessionIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(QrSession row) => row.SessionId;

                public SessionIdUniqueIndex(QrSessionHandle table) : base(table) { }
            }

            public readonly SessionIdUniqueIndex SessionId;

            internal QrSessionHandle(DbConnection conn) : base(conn)
            {
                SessionId = new(this);
            }

            protected override object GetPrimaryKey(QrSession row) => row.SessionId;
        }

        public readonly QrSessionHandle QrSession;
    }
}
