// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class RoleHandle : RemoteTableHandle<EventContext, Role>
        {
            protected override string RemoteTableName => "Role";

            public sealed class RoleIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Role row) => row.RoleId;

                public RoleIdUniqueIndex(RoleHandle table) : base(table) { }
            }

            public readonly RoleIdUniqueIndex RoleId;

            internal RoleHandle(DbConnection conn) : base(conn)
            {
                RoleId = new(this);
            }

            protected override object GetPrimaryKey(Role row) => row.RoleId;
        }

        public readonly RoleHandle Role;
    }
}
