// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SaleHandle : RemoteTableHandle<EventContext, Sale>
        {
            protected override string RemoteTableName => "sale";

            public sealed class SaleIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Sale row) => row.SaleId;

                public SaleIdUniqueIndex(SaleHandle table) : base(table) { }
            }

            public readonly SaleIdUniqueIndex SaleId;

            internal SaleHandle(DbConnection conn) : base(conn)
            {
                SaleId = new(this);
            }

            protected override object GetPrimaryKey(Sale row) => row.SaleId;
        }

        public readonly SaleHandle Sale;
    }

    public sealed class SaleCols
    {
        public global::SpacetimeDB.Col<Sale, uint> SaleId { get; }
        public global::SpacetimeDB.Col<Sale, ulong> SaleDate { get; }
        public global::SpacetimeDB.Col<Sale, uint> TicketId { get; }
        public global::SpacetimeDB.Col<Sale, string> TicketSoldToUser { get; }
        public global::SpacetimeDB.Col<Sale, string> TicketSoldToUserPhone { get; }
        public global::SpacetimeDB.Col<Sale, SpacetimeDB.Identity> SellerId { get; }
        public global::SpacetimeDB.Col<Sale, string> SaleLocation { get; }
        public global::SpacetimeDB.Col<Sale, string> SaleNotes { get; }
        public global::SpacetimeDB.Col<Sale, string> PaymentMethod { get; }
        public global::SpacetimeDB.Col<Sale, string> PaymentStatus { get; }
        public global::SpacetimeDB.Col<Sale, string> TransactionId { get; }
        public global::SpacetimeDB.Col<Sale, double> TaxAmount { get; }
        public global::SpacetimeDB.Col<Sale, string> InvoiceNumber { get; }
        public global::SpacetimeDB.Col<Sale, bool> IsSubscription { get; }
        public global::SpacetimeDB.Col<Sale, string> SubscriptionType { get; }
        public global::SpacetimeDB.Col<Sale, ulong> SubscriptionStartDate { get; }
        public global::SpacetimeDB.Col<Sale, ulong> SubscriptionEndDate { get; }
        public global::SpacetimeDB.Col<Sale, bool> IsGift { get; }
        public global::SpacetimeDB.Col<Sale, string> GiftRecipient { get; }
        public global::SpacetimeDB.Col<Sale, string> PromotionCode { get; }
        public global::SpacetimeDB.Col<Sale, double> DiscountAmount { get; }
        public global::SpacetimeDB.Col<Sale, double> TotalAmount { get; }
        public global::SpacetimeDB.Col<Sale, string> PaymentTransactionId { get; }
        public global::SpacetimeDB.Col<Sale, double> ChangeAmount { get; }
        public global::SpacetimeDB.Col<Sale, string> PaymentProvider { get; }
        public global::SpacetimeDB.Col<Sale, string> PaymentReference { get; }

        public SaleCols(string tableName)
        {
            SaleId = new global::SpacetimeDB.Col<Sale, uint>(tableName, "sale_id");
            SaleDate = new global::SpacetimeDB.Col<Sale, ulong>(tableName, "sale_date");
            TicketId = new global::SpacetimeDB.Col<Sale, uint>(tableName, "ticket_id");
            TicketSoldToUser = new global::SpacetimeDB.Col<Sale, string>(tableName, "ticket_sold_to_user");
            TicketSoldToUserPhone = new global::SpacetimeDB.Col<Sale, string>(tableName, "ticket_sold_to_user_phone");
            SellerId = new global::SpacetimeDB.Col<Sale, SpacetimeDB.Identity>(tableName, "seller_id");
            SaleLocation = new global::SpacetimeDB.Col<Sale, string>(tableName, "sale_location");
            SaleNotes = new global::SpacetimeDB.Col<Sale, string>(tableName, "sale_notes");
            PaymentMethod = new global::SpacetimeDB.Col<Sale, string>(tableName, "payment_method");
            PaymentStatus = new global::SpacetimeDB.Col<Sale, string>(tableName, "payment_status");
            TransactionId = new global::SpacetimeDB.Col<Sale, string>(tableName, "transaction_id");
            TaxAmount = new global::SpacetimeDB.Col<Sale, double>(tableName, "tax_amount");
            InvoiceNumber = new global::SpacetimeDB.Col<Sale, string>(tableName, "invoice_number");
            IsSubscription = new global::SpacetimeDB.Col<Sale, bool>(tableName, "is_subscription");
            SubscriptionType = new global::SpacetimeDB.Col<Sale, string>(tableName, "subscription_type");
            SubscriptionStartDate = new global::SpacetimeDB.Col<Sale, ulong>(tableName, "subscription_start_date");
            SubscriptionEndDate = new global::SpacetimeDB.Col<Sale, ulong>(tableName, "subscription_end_date");
            IsGift = new global::SpacetimeDB.Col<Sale, bool>(tableName, "is_gift");
            GiftRecipient = new global::SpacetimeDB.Col<Sale, string>(tableName, "gift_recipient");
            PromotionCode = new global::SpacetimeDB.Col<Sale, string>(tableName, "promotion_code");
            DiscountAmount = new global::SpacetimeDB.Col<Sale, double>(tableName, "discount_amount");
            TotalAmount = new global::SpacetimeDB.Col<Sale, double>(tableName, "total_amount");
            PaymentTransactionId = new global::SpacetimeDB.Col<Sale, string>(tableName, "payment_transaction_id");
            ChangeAmount = new global::SpacetimeDB.Col<Sale, double>(tableName, "change_amount");
            PaymentProvider = new global::SpacetimeDB.Col<Sale, string>(tableName, "payment_provider");
            PaymentReference = new global::SpacetimeDB.Col<Sale, string>(tableName, "payment_reference");
        }
    }

    public sealed class SaleIxCols
    {
        public global::SpacetimeDB.IxCol<Sale, uint> SaleId { get; }

        public SaleIxCols(string tableName)
        {
            SaleId = new global::SpacetimeDB.IxCol<Sale, uint>(tableName, "sale_id");
        }
    }
}
