// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SeatConfigurationIdCounterHandle : RemoteTableHandle<EventContext, SeatConfigurationIdCounter>
        {
            protected override string RemoteTableName => "seat_configuration_id_counter";

            public sealed class KeyUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(SeatConfigurationIdCounter row) => row.Key;

                public KeyUniqueIndex(SeatConfigurationIdCounterHandle table) : base(table) { }
            }

            public readonly KeyUniqueIndex Key;

            internal SeatConfigurationIdCounterHandle(DbConnection conn) : base(conn)
            {
                Key = new(this);
            }

            protected override object GetPrimaryKey(SeatConfigurationIdCounter row) => row.Key;
        }

        public readonly SeatConfigurationIdCounterHandle SeatConfigurationIdCounter;
    }

    public sealed class SeatConfigurationIdCounterCols
    {
        public global::SpacetimeDB.Col<SeatConfigurationIdCounter, string> Key { get; }
        public global::SpacetimeDB.Col<SeatConfigurationIdCounter, uint> NextId { get; }

        public SeatConfigurationIdCounterCols(string tableName)
        {
            Key = new global::SpacetimeDB.Col<SeatConfigurationIdCounter, string>(tableName, "key");
            NextId = new global::SpacetimeDB.Col<SeatConfigurationIdCounter, uint>(tableName, "next_id");
        }
    }

    public sealed class SeatConfigurationIdCounterIxCols
    {
        public global::SpacetimeDB.IxCol<SeatConfigurationIdCounter, string> Key { get; }

        public SeatConfigurationIdCounterIxCols(string tableName)
        {
            Key = new global::SpacetimeDB.IxCol<SeatConfigurationIdCounter, string>(tableName, "key");
        }
    }
}
