// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SeatConfigurationHandle : RemoteTableHandle<EventContext, SeatConfiguration>
        {
            protected override string RemoteTableName => "seat_configuration";

            public sealed class ConfigurationIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(SeatConfiguration row) => row.ConfigurationId;

                public ConfigurationIdUniqueIndex(SeatConfigurationHandle table) : base(table) { }
            }

            public readonly ConfigurationIdUniqueIndex ConfigurationId;

            internal SeatConfigurationHandle(DbConnection conn) : base(conn)
            {
                ConfigurationId = new(this);
            }

            protected override object GetPrimaryKey(SeatConfiguration row) => row.ConfigurationId;
        }

        public readonly SeatConfigurationHandle SeatConfiguration;
    }

    public sealed class SeatConfigurationCols
    {
        public global::SpacetimeDB.Col<SeatConfiguration, uint> ConfigurationId { get; }
        public global::SpacetimeDB.Col<SeatConfiguration, uint> BusId { get; }
        public global::SpacetimeDB.Col<SeatConfiguration, uint> SeatNumber { get; }
        public global::SpacetimeDB.Col<SeatConfiguration, string> SeatType { get; }
        public global::SpacetimeDB.Col<SeatConfiguration, string> SeatStatus { get; }
        public global::SpacetimeDB.Col<SeatConfiguration, uint> SeatRow { get; }
        public global::SpacetimeDB.Col<SeatConfiguration, uint> SeatColumn { get; }
        public global::SpacetimeDB.Col<SeatConfiguration, bool> IsAccessible { get; }
        public global::SpacetimeDB.Col<SeatConfiguration, bool> IsEmergencyExit { get; }
        public global::SpacetimeDB.Col<SeatConfiguration, string> Notes { get; }
        public global::SpacetimeDB.Col<SeatConfiguration, ulong> CreatedAt { get; }
        public global::SpacetimeDB.Col<SeatConfiguration, string> CreatedBy { get; }
        public global::SpacetimeDB.Col<SeatConfiguration, ulong> UpdatedAt { get; }
        public global::SpacetimeDB.Col<SeatConfiguration, string> UpdatedBy { get; }

        public SeatConfigurationCols(string tableName)
        {
            ConfigurationId = new global::SpacetimeDB.Col<SeatConfiguration, uint>(tableName, "configuration_id");
            BusId = new global::SpacetimeDB.Col<SeatConfiguration, uint>(tableName, "bus_id");
            SeatNumber = new global::SpacetimeDB.Col<SeatConfiguration, uint>(tableName, "seat_number");
            SeatType = new global::SpacetimeDB.Col<SeatConfiguration, string>(tableName, "seat_type");
            SeatStatus = new global::SpacetimeDB.Col<SeatConfiguration, string>(tableName, "seat_status");
            SeatRow = new global::SpacetimeDB.Col<SeatConfiguration, uint>(tableName, "seat_row");
            SeatColumn = new global::SpacetimeDB.Col<SeatConfiguration, uint>(tableName, "seat_column");
            IsAccessible = new global::SpacetimeDB.Col<SeatConfiguration, bool>(tableName, "is_accessible");
            IsEmergencyExit = new global::SpacetimeDB.Col<SeatConfiguration, bool>(tableName, "is_emergency_exit");
            Notes = new global::SpacetimeDB.Col<SeatConfiguration, string>(tableName, "notes");
            CreatedAt = new global::SpacetimeDB.Col<SeatConfiguration, ulong>(tableName, "created_at");
            CreatedBy = new global::SpacetimeDB.Col<SeatConfiguration, string>(tableName, "created_by");
            UpdatedAt = new global::SpacetimeDB.Col<SeatConfiguration, ulong>(tableName, "updated_at");
            UpdatedBy = new global::SpacetimeDB.Col<SeatConfiguration, string>(tableName, "updated_by");
        }
    }

    public sealed class SeatConfigurationIxCols
    {
        public global::SpacetimeDB.IxCol<SeatConfiguration, uint> ConfigurationId { get; }

        public SeatConfigurationIxCols(string tableName)
        {
            ConfigurationId = new global::SpacetimeDB.IxCol<SeatConfiguration, uint>(tableName, "configuration_id");
        }
    }
}
