// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TicketSaleEventHandle : RemoteEventTableHandle<EventContext, TicketSaleEvent>
        {
            protected override string RemoteTableName => "ticket_sale_event";

            internal TicketSaleEventHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly TicketSaleEventHandle TicketSaleEvent;
    }

    public sealed class TicketSaleEventCols
    {
        public global::SpacetimeDB.Col<TicketSaleEvent, uint> SaleId { get; }
        public global::SpacetimeDB.Col<TicketSaleEvent, uint> TicketId { get; }
        public global::SpacetimeDB.Col<TicketSaleEvent, uint> RouteId { get; }
        public global::SpacetimeDB.Col<TicketSaleEvent, SpacetimeDB.Identity> BuyerId { get; }
        public global::SpacetimeDB.Col<TicketSaleEvent, double> Amount { get; }
        public global::SpacetimeDB.Col<TicketSaleEvent, ulong> Timestamp { get; }
        public global::SpacetimeDB.Col<TicketSaleEvent, string> PaymentMethod { get; }

        public TicketSaleEventCols(string tableName)
        {
            SaleId = new global::SpacetimeDB.Col<TicketSaleEvent, uint>(tableName, "sale_id");
            TicketId = new global::SpacetimeDB.Col<TicketSaleEvent, uint>(tableName, "ticket_id");
            RouteId = new global::SpacetimeDB.Col<TicketSaleEvent, uint>(tableName, "route_id");
            BuyerId = new global::SpacetimeDB.Col<TicketSaleEvent, SpacetimeDB.Identity>(tableName, "buyer_id");
            Amount = new global::SpacetimeDB.Col<TicketSaleEvent, double>(tableName, "amount");
            Timestamp = new global::SpacetimeDB.Col<TicketSaleEvent, ulong>(tableName, "timestamp");
            PaymentMethod = new global::SpacetimeDB.Col<TicketSaleEvent, string>(tableName, "payment_method");
        }
    }

    public sealed class TicketSaleEventIxCols
    {

        public TicketSaleEventIxCols(string tableName)
        {
        }
    }
}
