// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TotpSecretHandle : RemoteTableHandle<EventContext, TotpSecret>
        {
<<<<<<< HEAD
            protected override string RemoteTableName => "TotpSecret";
=======
            protected override string RemoteTableName => "totp_secret";
>>>>>>> maintofix

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(TotpSecret row) => row.Id;

                public IdUniqueIndex(TotpSecretHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal TotpSecretHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(TotpSecret row) => row.Id;
        }

        public readonly TotpSecretHandle TotpSecret;
    }
<<<<<<< HEAD
=======

    public sealed class TotpSecretCols
    {
        public global::SpacetimeDB.Col<TotpSecret, uint> Id { get; }
        public global::SpacetimeDB.Col<TotpSecret, SpacetimeDB.Identity> UserId { get; }
        public global::SpacetimeDB.Col<TotpSecret, string> Secret { get; }
        public global::SpacetimeDB.Col<TotpSecret, ulong> CreatedAt { get; }
        public global::SpacetimeDB.Col<TotpSecret, bool> IsActive { get; }

        public TotpSecretCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<TotpSecret, uint>(tableName, "id");
            UserId = new global::SpacetimeDB.Col<TotpSecret, SpacetimeDB.Identity>(tableName, "user_id");
            Secret = new global::SpacetimeDB.Col<TotpSecret, string>(tableName, "secret");
            CreatedAt = new global::SpacetimeDB.Col<TotpSecret, ulong>(tableName, "created_at");
            IsActive = new global::SpacetimeDB.Col<TotpSecret, bool>(tableName, "is_active");
        }
    }

    public sealed class TotpSecretIxCols
    {
        public global::SpacetimeDB.IxCol<TotpSecret, uint> Id { get; }

        public TotpSecretIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<TotpSecret, uint>(tableName, "id");
        }
    }
>>>>>>> maintofix
}
