// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TotpSecretIdCounterHandle : RemoteTableHandle<EventContext, TotpSecretIdCounter>
        {
            protected override string RemoteTableName => "TotpSecretIdCounter";

            public sealed class KeyUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(TotpSecretIdCounter row) => row.Key;

                public KeyUniqueIndex(TotpSecretIdCounterHandle table) : base(table) { }
            }

            public readonly KeyUniqueIndex Key;

            internal TotpSecretIdCounterHandle(DbConnection conn) : base(conn)
            {
                Key = new(this);
            }

            protected override object GetPrimaryKey(TotpSecretIdCounter row) => row.Key;
        }

        public readonly TotpSecretIdCounterHandle TotpSecretIdCounter;
    }
}
