// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UserRoleHandle : RemoteTableHandle<EventContext, UserRole>
        {
            protected override string RemoteTableName => "UserRole";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(UserRole row) => row.Id;

                public IdUniqueIndex(UserRoleHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal UserRoleHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(UserRole row) => row.Id;
        }

        public readonly UserRoleHandle UserRole;
    }
}
