// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UserIdCounterHandle : RemoteTableHandle<EventContext, UserIdCounter>
        {
            protected override string RemoteTableName => "user_id_counter";

            public sealed class KeyUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(UserIdCounter row) => row.Key;

                public KeyUniqueIndex(UserIdCounterHandle table) : base(table) { }
            }

            public readonly KeyUniqueIndex Key;

            internal UserIdCounterHandle(DbConnection conn) : base(conn)
            {
                Key = new(this);
            }

            protected override object GetPrimaryKey(UserIdCounter row) => row.Key;
        }

        public readonly UserIdCounterHandle UserIdCounter;
    }

    public sealed class UserIdCounterCols
    {
        public global::SpacetimeDB.Col<UserIdCounter, string> Key { get; }
        public global::SpacetimeDB.Col<UserIdCounter, uint> NextId { get; }

        public UserIdCounterCols(string tableName)
        {
            Key = new global::SpacetimeDB.Col<UserIdCounter, string>(tableName, "key");
            NextId = new global::SpacetimeDB.Col<UserIdCounter, uint>(tableName, "next_id");
        }
    }

    public sealed class UserIdCounterIxCols
    {
        public global::SpacetimeDB.IxCol<UserIdCounter, string> Key { get; }

        public UserIdCounterIxCols(string tableName)
        {
            Key = new global::SpacetimeDB.IxCol<UserIdCounter, string>(tableName, "key");
        }
    }
}
