// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UserSettingsHandle : RemoteTableHandle<EventContext, UserSettings>
        {
            protected override string RemoteTableName => "user_settings";

            public sealed class UserSettingIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(UserSettings row) => row.UserSettingId;

                public UserSettingIdUniqueIndex(UserSettingsHandle table) : base(table) { }
            }

            public readonly UserSettingIdUniqueIndex UserSettingId;

            internal UserSettingsHandle(DbConnection conn) : base(conn)
            {
                UserSettingId = new(this);
            }

            protected override object GetPrimaryKey(UserSettings row) => row.UserSettingId;
        }

        public readonly UserSettingsHandle UserSettings;
    }

    public sealed class UserSettingsCols
    {
        public global::SpacetimeDB.Col<UserSettings, uint> UserSettingId { get; }
        public global::SpacetimeDB.Col<UserSettings, SpacetimeDB.Identity> UserId { get; }
        public global::SpacetimeDB.Col<UserSettings, bool> TotpEnabled { get; }
        public global::SpacetimeDB.Col<UserSettings, bool> WebAuthnEnabled { get; }
        public global::SpacetimeDB.Col<UserSettings, bool> IsEmailNotificationsEnabled { get; }
        public global::SpacetimeDB.Col<UserSettings, bool> IsSmsNotificationsEnabled { get; }
        public global::SpacetimeDB.Col<UserSettings, bool> IsPushNotificationsEnabled { get; }
        public global::SpacetimeDB.Col<UserSettings, bool> IsWhatsAppNotificationsEnabled { get; }
        public global::SpacetimeDB.Col<UserSettings, bool> IsTelegramNotificationsEnabled { get; }
        public global::SpacetimeDB.Col<UserSettings, bool> IsDiscordNotificationsEnabled { get; }

        public UserSettingsCols(string tableName)
        {
            UserSettingId = new global::SpacetimeDB.Col<UserSettings, uint>(tableName, "user_setting_id");
            UserId = new global::SpacetimeDB.Col<UserSettings, SpacetimeDB.Identity>(tableName, "user_id");
            TotpEnabled = new global::SpacetimeDB.Col<UserSettings, bool>(tableName, "totp_enabled");
            WebAuthnEnabled = new global::SpacetimeDB.Col<UserSettings, bool>(tableName, "web_authn_enabled");
            IsEmailNotificationsEnabled = new global::SpacetimeDB.Col<UserSettings, bool>(tableName, "is_email_notifications_enabled");
            IsSmsNotificationsEnabled = new global::SpacetimeDB.Col<UserSettings, bool>(tableName, "is_sms_notifications_enabled");
            IsPushNotificationsEnabled = new global::SpacetimeDB.Col<UserSettings, bool>(tableName, "is_push_notifications_enabled");
            IsWhatsAppNotificationsEnabled = new global::SpacetimeDB.Col<UserSettings, bool>(tableName, "is_whats_app_notifications_enabled");
            IsTelegramNotificationsEnabled = new global::SpacetimeDB.Col<UserSettings, bool>(tableName, "is_telegram_notifications_enabled");
            IsDiscordNotificationsEnabled = new global::SpacetimeDB.Col<UserSettings, bool>(tableName, "is_discord_notifications_enabled");
        }
    }

    public sealed class UserSettingsIxCols
    {
        public global::SpacetimeDB.IxCol<UserSettings, uint> UserSettingId { get; }

        public UserSettingsIxCols(string tableName)
        {
            UserSettingId = new global::SpacetimeDB.IxCol<UserSettings, uint>(tableName, "user_setting_id");
        }
    }
}
