// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UserSettingsHandle : RemoteTableHandle<EventContext, UserSettings>
        {
            protected override string RemoteTableName => "UserSettings";

            public sealed class UserSettingIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(UserSettings row) => row.UserSettingId;

                public UserSettingIdUniqueIndex(UserSettingsHandle table) : base(table) { }
            }

            public readonly UserSettingIdUniqueIndex UserSettingId;

            internal UserSettingsHandle(DbConnection conn) : base(conn)
            {
                UserSettingId = new(this);
            }

            protected override object GetPrimaryKey(UserSettings row) => row.UserSettingId;
        }

        public readonly UserSettingsHandle UserSettings;
    }
}
