// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WebAuthnCredentialIdCounterHandle : RemoteTableHandle<EventContext, WebAuthnCredentialIdCounter>
        {
            protected override string RemoteTableName => "WebAuthnCredentialIdCounter";

            public sealed class KeyUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(WebAuthnCredentialIdCounter row) => row.Key;

                public KeyUniqueIndex(WebAuthnCredentialIdCounterHandle table) : base(table) { }
            }

            public readonly KeyUniqueIndex Key;

            internal WebAuthnCredentialIdCounterHandle(DbConnection conn) : base(conn)
            {
                Key = new(this);
            }

            protected override object GetPrimaryKey(WebAuthnCredentialIdCounter row) => row.Key;
        }

        public readonly WebAuthnCredentialIdCounterHandle WebAuthnCredentialIdCounter;
    }
}
