// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WebAuthnChallengeHandle : RemoteTableHandle<EventContext, WebAuthnChallenge>
        {
            protected override string RemoteTableName => "web_authn_challenge";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(WebAuthnChallenge row) => row.Id;

                public IdUniqueIndex(WebAuthnChallengeHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal WebAuthnChallengeHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(WebAuthnChallenge row) => row.Id;
        }

        public readonly WebAuthnChallengeHandle WebAuthnChallenge;
    }

    public sealed class WebAuthnChallengeCols
    {
        public global::SpacetimeDB.Col<WebAuthnChallenge, uint> Id { get; }
        public global::SpacetimeDB.Col<WebAuthnChallenge, SpacetimeDB.Identity> UserId { get; }
        public global::SpacetimeDB.Col<WebAuthnChallenge, string> Challenge { get; }
        public global::SpacetimeDB.Col<WebAuthnChallenge, ulong> ExpiresAt { get; }
        public global::SpacetimeDB.Col<WebAuthnChallenge, ulong> CreatedAt { get; }

        public WebAuthnChallengeCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<WebAuthnChallenge, uint>(tableName, "id");
            UserId = new global::SpacetimeDB.Col<WebAuthnChallenge, SpacetimeDB.Identity>(tableName, "user_id");
            Challenge = new global::SpacetimeDB.Col<WebAuthnChallenge, string>(tableName, "challenge");
            ExpiresAt = new global::SpacetimeDB.Col<WebAuthnChallenge, ulong>(tableName, "expires_at");
            CreatedAt = new global::SpacetimeDB.Col<WebAuthnChallenge, ulong>(tableName, "created_at");
        }
    }

    public sealed class WebAuthnChallengeIxCols
    {
        public global::SpacetimeDB.IxCol<WebAuthnChallenge, uint> Id { get; }

        public WebAuthnChallengeIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<WebAuthnChallenge, uint>(tableName, "id");
        }
    }
}
