// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BusLocation
    {
        [DataMember(Name = "location_id")]
        public uint LocationId;
        [DataMember(Name = "bus_id")]
        public uint BusId;
        [DataMember(Name = "latitude")]
        public double Latitude;
        [DataMember(Name = "longitude")]
        public double Longitude;
        [DataMember(Name = "timestamp")]
        public ulong Timestamp;
        [DataMember(Name = "route_id")]
        public uint? RouteId;
        [DataMember(Name = "schedule_id")]
        public uint? ScheduleId;
        [DataMember(Name = "speed")]
        public double? Speed;
        [DataMember(Name = "heading")]
        public double? Heading;
        [DataMember(Name = "status")]
        public string? Status;
        [DataMember(Name = "next_stop_id")]
        public uint? NextStopId;
        [DataMember(Name = "estimated_arrival_time")]
        public ulong? EstimatedArrivalTime;
        [DataMember(Name = "is_delayed")]
        public bool? IsDelayed;
        [DataMember(Name = "delay_minutes")]
        public uint? DelayMinutes;
        [DataMember(Name = "delay_reason")]
        public string? DelayReason;

        public BusLocation(
            uint LocationId,
            uint BusId,
            double Latitude,
            double Longitude,
            ulong Timestamp,
            uint? RouteId,
            uint? ScheduleId,
            double? Speed,
            double? Heading,
            string? Status,
            uint? NextStopId,
            ulong? EstimatedArrivalTime,
            bool? IsDelayed,
            uint? DelayMinutes,
            string? DelayReason
        )
        {
            this.LocationId = LocationId;
            this.BusId = BusId;
            this.Latitude = Latitude;
            this.Longitude = Longitude;
            this.Timestamp = Timestamp;
            this.RouteId = RouteId;
            this.ScheduleId = ScheduleId;
            this.Speed = Speed;
            this.Heading = Heading;
            this.Status = Status;
            this.NextStopId = NextStopId;
            this.EstimatedArrivalTime = EstimatedArrivalTime;
            this.IsDelayed = IsDelayed;
            this.DelayMinutes = DelayMinutes;
            this.DelayReason = DelayReason;
        }

        public BusLocation()
        {
        }
    }
}
