// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BusStatusEvent
    {
        [DataMember(Name = "bus_id")]
        public uint BusId;
        [DataMember(Name = "previous_status")]
        public string PreviousStatus;
        [DataMember(Name = "new_status")]
        public string NewStatus;
        [DataMember(Name = "timestamp")]
        public ulong Timestamp;
        [DataMember(Name = "changed_by")]
        public SpacetimeDB.Identity ChangedBy;
        [DataMember(Name = "reason")]
        public string? Reason;

        public BusStatusEvent(
            uint BusId,
            string PreviousStatus,
            string NewStatus,
            ulong Timestamp,
            SpacetimeDB.Identity ChangedBy,
            string? Reason
        )
        {
            this.BusId = BusId;
            this.PreviousStatus = PreviousStatus;
            this.NewStatus = NewStatus;
            this.Timestamp = Timestamp;
            this.ChangedBy = ChangedBy;
            this.Reason = Reason;
        }

        public BusStatusEvent()
        {
            this.PreviousStatus = "";
            this.NewStatus = "";
        }
    }
}
