// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Client
    {
        [DataMember(Name = "Id")]
        public int Id;
        [DataMember(Name = "ClientId")]
        public string ClientId;
        [DataMember(Name = "ClientSecret")]
        public string ClientSecret;

        public Client(
            int Id,
            string ClientId,
            string ClientSecret
        )
        {
            this.Id = Id;
            this.ClientId = ClientId;
            this.ClientSecret = ClientSecret;
        }

        public Client()
        {
            this.ClientId = "";
            this.ClientSecret = "";
        }
    }
}
