// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConductorStatistics
    {
        [DataMember(Name = "StatId")]
        public uint StatId;
        [DataMember(Name = "EmployeeId")]
        public uint EmployeeId;
        [DataMember(Name = "PeriodStart")]
        public ulong PeriodStart;
        [DataMember(Name = "PeriodEnd")]
        public ulong PeriodEnd;
        [DataMember(Name = "TotalPassengersServed")]
        public long TotalPassengersServed;
        [DataMember(Name = "AverageFareEvasionRate")]
        public double AverageFareEvasionRate;
        [DataMember(Name = "TotalRevenueCollected")]
        public double TotalRevenueCollected;
        [DataMember(Name = "TotalFinesCollected")]
        public double TotalFinesCollected;
        [DataMember(Name = "TotalComplaintsReceived")]
        public long TotalComplaintsReceived;
        [DataMember(Name = "AverageRating")]
        public double AverageRating;
        [DataMember(Name = "TotalShiftsWorked")]
        public long TotalShiftsWorked;
        [DataMember(Name = "AveragePassengersPerShift")]
        public double AveragePassengersPerShift;
        [DataMember(Name = "EfficiencyScore")]
        public double EfficiencyScore;
        [DataMember(Name = "TotalTicketsSold")]
        public long TotalTicketsSold;
        [DataMember(Name = "AverageTicketsPerHour")]
        public double AverageTicketsPerHour;
        [DataMember(Name = "AverageRevenuePerShift")]
        public double AverageRevenuePerShift;
        [DataMember(Name = "TotalIncidentsReported")]
        public long TotalIncidentsReported;
        [DataMember(Name = "TotalSafetyViolationsReported")]
        public long TotalSafetyViolationsReported;
        [DataMember(Name = "TotalPassengerAssistance")]
        public long TotalPassengerAssistance;
        [DataMember(Name = "AveragePerformanceRating")]
        public double AveragePerformanceRating;
        [DataMember(Name = "TotalFirstAidProvided")]
        public long TotalFirstAidProvided;
        [DataMember(Name = "TotalEmergencyResponses")]
        public long TotalEmergencyResponses;

        public ConductorStatistics(
            uint StatId,
            uint EmployeeId,
            ulong PeriodStart,
            ulong PeriodEnd,
            long TotalPassengersServed,
            double AverageFareEvasionRate,
            double TotalRevenueCollected,
            double TotalFinesCollected,
            long TotalComplaintsReceived,
            double AverageRating,
            long TotalShiftsWorked,
            double AveragePassengersPerShift,
            double EfficiencyScore,
            long TotalTicketsSold,
            double AverageTicketsPerHour,
            double AverageRevenuePerShift,
            long TotalIncidentsReported,
            long TotalSafetyViolationsReported,
            long TotalPassengerAssistance,
            double AveragePerformanceRating,
            long TotalFirstAidProvided,
            long TotalEmergencyResponses
        )
        {
            this.StatId = StatId;
            this.EmployeeId = EmployeeId;
            this.PeriodStart = PeriodStart;
            this.PeriodEnd = PeriodEnd;
            this.TotalPassengersServed = TotalPassengersServed;
            this.AverageFareEvasionRate = AverageFareEvasionRate;
            this.TotalRevenueCollected = TotalRevenueCollected;
            this.TotalFinesCollected = TotalFinesCollected;
            this.TotalComplaintsReceived = TotalComplaintsReceived;
            this.AverageRating = AverageRating;
            this.TotalShiftsWorked = TotalShiftsWorked;
            this.AveragePassengersPerShift = AveragePassengersPerShift;
            this.EfficiencyScore = EfficiencyScore;
            this.TotalTicketsSold = TotalTicketsSold;
            this.AverageTicketsPerHour = AverageTicketsPerHour;
            this.AverageRevenuePerShift = AverageRevenuePerShift;
            this.TotalIncidentsReported = TotalIncidentsReported;
            this.TotalSafetyViolationsReported = TotalSafetyViolationsReported;
            this.TotalPassengerAssistance = TotalPassengerAssistance;
            this.AveragePerformanceRating = AveragePerformanceRating;
            this.TotalFirstAidProvided = TotalFirstAidProvided;
            this.TotalEmergencyResponses = TotalEmergencyResponses;
        }

        public ConductorStatistics()
        {
        }
    }
}
