// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Discounts
    {
        [DataMember(Name = "DiscountId")]
        public uint DiscountId;
        [DataMember(Name = "DiscountType")]
        public string DiscountType;
        [DataMember(Name = "DiscountPercentage")]
        public double DiscountPercentage;
        [DataMember(Name = "StartDate")]
        public ulong StartDate;
        [DataMember(Name = "EndDate")]
        public ulong EndDate;
        [DataMember(Name = "IsActive")]
        public bool IsActive;
        [DataMember(Name = "Description")]
        public string? Description;
        [DataMember(Name = "RequiredDocuments")]
        public string? RequiredDocuments;
        [DataMember(Name = "CreatedBy")]
        public string? CreatedBy;
        [DataMember(Name = "CreatedAt")]
        public ulong CreatedAt;
        [DataMember(Name = "UpdatedBy")]
        public string? UpdatedBy;
        [DataMember(Name = "UpdatedAt")]
        public ulong? UpdatedAt;

        public Discounts(
            uint DiscountId,
            string DiscountType,
            double DiscountPercentage,
            ulong StartDate,
            ulong EndDate,
            bool IsActive,
            string? Description,
            string? RequiredDocuments,
            string? CreatedBy,
            ulong CreatedAt,
            string? UpdatedBy,
            ulong? UpdatedAt
        )
        {
            this.DiscountId = DiscountId;
            this.DiscountType = DiscountType;
            this.DiscountPercentage = DiscountPercentage;
            this.StartDate = StartDate;
            this.EndDate = EndDate;
            this.IsActive = IsActive;
            this.Description = Description;
            this.RequiredDocuments = RequiredDocuments;
            this.CreatedBy = CreatedBy;
            this.CreatedAt = CreatedAt;
            this.UpdatedBy = UpdatedBy;
            this.UpdatedAt = UpdatedAt;
        }

        public Discounts()
        {
            this.DiscountType = "";
        }
    }
}
