// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Employee
    {
        [DataMember(Name = "EmployeeId")]
        public uint EmployeeId;
        [DataMember(Name = "Surname")]
        public string Surname;
        [DataMember(Name = "Name")]
        public string Name;
        [DataMember(Name = "Patronym")]
        public string? Patronym;
        [DataMember(Name = "EmployedSince")]
        public ulong EmployedSince;
        [DataMember(Name = "JobId")]
        public uint JobId;

        public Employee(
            uint EmployeeId,
            string Surname,
            string Name,
            string? Patronym,
            ulong EmployedSince,
            uint JobId
        )
        {
            this.EmployeeId = EmployeeId;
            this.Surname = Surname;
            this.Name = Name;
            this.Patronym = Patronym;
            this.EmployedSince = EmployedSince;
            this.JobId = JobId;
        }

        public Employee()
        {
            this.Surname = "";
            this.Name = "";
        }
    }
}
