// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EmployeeShift
    {
        [DataMember(Name = "ShiftId")]
        public uint ShiftId;
        [DataMember(Name = "EmployeeId")]
        public uint EmployeeId;
        [DataMember(Name = "ShiftStartDate")]
        public ulong ShiftStartDate;
        [DataMember(Name = "ShiftEndDate")]
        public ulong ShiftEndDate;
        [DataMember(Name = "ShiftStartTime")]
        public ulong ShiftStartTime;
        [DataMember(Name = "ShiftEndTime")]
        public ulong ShiftEndTime;
        [DataMember(Name = "ShiftType")]
        public string ShiftType;
        [DataMember(Name = "ShiftStatus")]
        public string ShiftStatus;
        [DataMember(Name = "RouteId")]
        public uint? RouteId;
        [DataMember(Name = "Notes")]
        public string? Notes;
        [DataMember(Name = "AssignedBy")]
        public SpacetimeDB.Identity? AssignedBy;
        [DataMember(Name = "AssignedAt")]
        public ulong AssignedAt;
        [DataMember(Name = "ShiftForm")]
        public string? ShiftForm;
        [DataMember(Name = "ShiftDuration")]
        public double ShiftDuration;
        [DataMember(Name = "BreakStartTime")]
        public ulong? BreakStartTime;
        [DataMember(Name = "BreakEndTime")]
        public ulong? BreakEndTime;
        [DataMember(Name = "BreakDuration")]
        public double? BreakDuration;
        [DataMember(Name = "IsOvertime")]
        public bool? IsOvertime;
        [DataMember(Name = "OvertimeHours")]
        public double? OvertimeHours;
        [DataMember(Name = "ReplacementFor")]
        public string? ReplacementFor;
        [DataMember(Name = "IsTraining")]
        public bool? IsTraining;
        [DataMember(Name = "TrainerName")]
        public string? TrainerName;
        [DataMember(Name = "ShiftLocation")]
        public string? ShiftLocation;
        [DataMember(Name = "ShiftFeedback")]
        public string? ShiftFeedback;
        [DataMember(Name = "ComplianceWithRegulations")]
        public bool? ComplianceWithRegulations;

        public EmployeeShift(
            uint ShiftId,
            uint EmployeeId,
            ulong ShiftStartDate,
            ulong ShiftEndDate,
            ulong ShiftStartTime,
            ulong ShiftEndTime,
            string ShiftType,
            string ShiftStatus,
            uint? RouteId,
            string? Notes,
            SpacetimeDB.Identity? AssignedBy,
            ulong AssignedAt,
            string? ShiftForm,
            double ShiftDuration,
            ulong? BreakStartTime,
            ulong? BreakEndTime,
            double? BreakDuration,
            bool? IsOvertime,
            double? OvertimeHours,
            string? ReplacementFor,
            bool? IsTraining,
            string? TrainerName,
            string? ShiftLocation,
            string? ShiftFeedback,
            bool? ComplianceWithRegulations
        )
        {
            this.ShiftId = ShiftId;
            this.EmployeeId = EmployeeId;
            this.ShiftStartDate = ShiftStartDate;
            this.ShiftEndDate = ShiftEndDate;
            this.ShiftStartTime = ShiftStartTime;
            this.ShiftEndTime = ShiftEndTime;
            this.ShiftType = ShiftType;
            this.ShiftStatus = ShiftStatus;
            this.RouteId = RouteId;
            this.Notes = Notes;
            this.AssignedBy = AssignedBy;
            this.AssignedAt = AssignedAt;
            this.ShiftForm = ShiftForm;
            this.ShiftDuration = ShiftDuration;
            this.BreakStartTime = BreakStartTime;
            this.BreakEndTime = BreakEndTime;
            this.BreakDuration = BreakDuration;
            this.IsOvertime = IsOvertime;
            this.OvertimeHours = OvertimeHours;
            this.ReplacementFor = ReplacementFor;
            this.IsTraining = IsTraining;
            this.TrainerName = TrainerName;
            this.ShiftLocation = ShiftLocation;
            this.ShiftFeedback = ShiftFeedback;
            this.ComplianceWithRegulations = ComplianceWithRegulations;
        }

        public EmployeeShift()
        {
            this.ShiftType = "";
            this.ShiftStatus = "";
        }
    }
}
