// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class FeatureFlagOverride
    {
        [DataMember(Name = "flag_name")]
        public string FlagName;
        [DataMember(Name = "enabled")]
        public bool Enabled;
        [DataMember(Name = "updated_by")]
        public SpacetimeDB.Identity UpdatedBy;
        [DataMember(Name = "updated_at")]
        public ulong UpdatedAt;

        public FeatureFlagOverride(
            string FlagName,
            bool Enabled,
            SpacetimeDB.Identity UpdatedBy,
            ulong UpdatedAt
        )
        {
            this.FlagName = FlagName;
            this.Enabled = Enabled;
            this.UpdatedBy = UpdatedBy;
            this.UpdatedAt = UpdatedAt;
        }

        public FeatureFlagOverride()
        {
            this.FlagName = "";
        }
    }
}
