// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Job
    {
        [DataMember(Name = "JobId")]
        public uint JobId;
        [DataMember(Name = "JobTitle")]
        public string JobTitle;
        [DataMember(Name = "Internship")]
        public string? Internship;

        public Job(
            uint JobId,
            string JobTitle,
            string? Internship
        )
        {
            this.JobId = JobId;
            this.JobTitle = JobTitle;
            this.Internship = Internship;
        }

        public Job()
        {
            this.JobTitle = "";
        }
    }
}
