// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class JobIdCounter
    {
<<<<<<< HEAD
        [DataMember(Name = "Key")]
        public string Key;
        [DataMember(Name = "NextId")]
=======
        [DataMember(Name = "key")]
        public string Key;
        [DataMember(Name = "next_id")]
>>>>>>> maintofix
        public uint NextId;

        public JobIdCounter(
            string Key,
            uint NextId
        )
        {
            this.Key = Key;
            this.NextId = NextId;
        }

        public JobIdCounter()
        {
            this.Key = "";
        }
    }
}
