// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MagicLinkToken
    {
        [DataMember(Name = "Token")]
        public string Token;
        [DataMember(Name = "UserId")]
        public SpacetimeDB.Identity UserId;
        [DataMember(Name = "ExpiresAt")]
        public ulong ExpiresAt;
        [DataMember(Name = "IsUsed")]
        public bool IsUsed;
        [DataMember(Name = "DeviceInfo")]
        public string? DeviceInfo;
        [DataMember(Name = "IpAddress")]
        public string? IpAddress;

        public MagicLinkToken(
            string Token,
            SpacetimeDB.Identity UserId,
            ulong ExpiresAt,
            bool IsUsed,
            string? DeviceInfo,
            string? IpAddress
        )
        {
            this.Token = Token;
            this.UserId = UserId;
            this.ExpiresAt = ExpiresAt;
            this.IsUsed = IsUsed;
            this.DeviceInfo = DeviceInfo;
            this.IpAddress = IpAddress;
        }

        public MagicLinkToken()
        {
            this.Token = "";
        }
    }
}
