// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Maintenance
    {
        [DataMember(Name = "MaintenanceId")]
        public uint MaintenanceId;
        [DataMember(Name = "BusId")]
        public uint BusId;
        [DataMember(Name = "LastServiceDate")]
        public ulong LastServiceDate;
        [DataMember(Name = "MileageThreshold")]
        public string? MileageThreshold;
        [DataMember(Name = "MaintenanceType")]
        public string? MaintenanceType;
        [DataMember(Name = "ServiceEngineer")]
        public string? ServiceEngineer;
        [DataMember(Name = "FoundIssues")]
        public string? FoundIssues;
        [DataMember(Name = "NextServiceDate")]
        public ulong NextServiceDate;
        [DataMember(Name = "Roadworthiness")]
        public string? Roadworthiness;

        public Maintenance(
            uint MaintenanceId,
            uint BusId,
            ulong LastServiceDate,
            string? MileageThreshold,
            string? MaintenanceType,
            string? ServiceEngineer,
            string? FoundIssues,
            ulong NextServiceDate,
            string? Roadworthiness
        )
        {
            this.MaintenanceId = MaintenanceId;
            this.BusId = BusId;
            this.LastServiceDate = LastServiceDate;
            this.MileageThreshold = MileageThreshold;
            this.MaintenanceType = MaintenanceType;
            this.ServiceEngineer = ServiceEngineer;
            this.FoundIssues = FoundIssues;
            this.NextServiceDate = NextServiceDate;
            this.Roadworthiness = Roadworthiness;
        }

        public Maintenance()
        {
        }
    }
}
