// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Maintenance
    {
        [DataMember(Name = "maintenance_id")]
        public uint MaintenanceId;
        [DataMember(Name = "bus_id")]
        public uint BusId;
        [DataMember(Name = "last_service_date")]
        public ulong LastServiceDate;
        [DataMember(Name = "mileage_threshold")]
        public string? MileageThreshold;
        [DataMember(Name = "maintenance_type")]
        public string? MaintenanceType;
        [DataMember(Name = "service_engineer")]
        public string? ServiceEngineer;
        [DataMember(Name = "found_issues")]
        public string? FoundIssues;
        [DataMember(Name = "next_service_date")]
        public ulong NextServiceDate;
        [DataMember(Name = "roadworthiness")]
        public string? Roadworthiness;
        [DataMember(Name = "maintenance_cost")]
        public double MaintenanceCost;
        [DataMember(Name = "parts_replaced")]
        public string? PartsReplaced;
        [DataMember(Name = "maintenance_duration")]
        public ulong MaintenanceDuration;
        [DataMember(Name = "is_scheduled")]
        public bool IsScheduled;
        [DataMember(Name = "maintenance_location")]
        public string? MaintenanceLocation;
        [DataMember(Name = "scheduled_by_employee_id")]
        public uint? ScheduledByEmployeeId;
        [DataMember(Name = "completed_by_employee_id")]
        public uint? CompletedByEmployeeId;
        [DataMember(Name = "maintenance_notes")]
        public string? MaintenanceNotes;
        [DataMember(Name = "maintenance_status")]
        public string? MaintenanceStatus;
        [DataMember(Name = "diagnostic_codes")]
        public System.Collections.Generic.List<string>? DiagnosticCodes;
        [DataMember(Name = "labor_cost")]
        public double? LaborCost;
        [DataMember(Name = "parts_cost")]
        public double? PartsCost;

        public Maintenance(
            uint MaintenanceId,
            uint BusId,
            ulong LastServiceDate,
            string? MileageThreshold,
            string? MaintenanceType,
            string? ServiceEngineer,
            string? FoundIssues,
            ulong NextServiceDate,
            string? Roadworthiness,
            double MaintenanceCost,
            string? PartsReplaced,
            ulong MaintenanceDuration,
            bool IsScheduled,
            string? MaintenanceLocation,
            uint? ScheduledByEmployeeId,
            uint? CompletedByEmployeeId,
            string? MaintenanceNotes,
            string? MaintenanceStatus,
            System.Collections.Generic.List<string>? DiagnosticCodes,
            double? LaborCost,
            double? PartsCost
        )
        {
            this.MaintenanceId = MaintenanceId;
            this.BusId = BusId;
            this.LastServiceDate = LastServiceDate;
            this.MileageThreshold = MileageThreshold;
            this.MaintenanceType = MaintenanceType;
            this.ServiceEngineer = ServiceEngineer;
            this.FoundIssues = FoundIssues;
            this.NextServiceDate = NextServiceDate;
            this.Roadworthiness = Roadworthiness;
            this.MaintenanceCost = MaintenanceCost;
            this.PartsReplaced = PartsReplaced;
            this.MaintenanceDuration = MaintenanceDuration;
            this.IsScheduled = IsScheduled;
            this.MaintenanceLocation = MaintenanceLocation;
            this.ScheduledByEmployeeId = ScheduledByEmployeeId;
            this.CompletedByEmployeeId = CompletedByEmployeeId;
            this.MaintenanceNotes = MaintenanceNotes;
            this.MaintenanceStatus = MaintenanceStatus;
            this.DiagnosticCodes = DiagnosticCodes;
            this.LaborCost = LaborCost;
            this.PartsCost = PartsCost;
        }

        public Maintenance()
        {
        }
    }
}
