// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class OpenIdConnectGrant
    {
        [DataMember(Name = "GrantId")]
        public string GrantId;
        [DataMember(Name = "ClientId")]
        public string ClientId;
        [DataMember(Name = "UserId")]
        public SpacetimeDB.Identity UserId;
        [DataMember(Name = "Type")]
        public string Type;
        [DataMember(Name = "Scopes")]
        public System.Collections.Generic.List<string> Scopes;
        [DataMember(Name = "CreatedAt")]
        public ulong CreatedAt;
        [DataMember(Name = "ExpiresAt")]
        public ulong ExpiresAt;
        [DataMember(Name = "IsRevoked")]
        public bool IsRevoked;

        public OpenIdConnectGrant(
            string GrantId,
            string ClientId,
            SpacetimeDB.Identity UserId,
            string Type,
            System.Collections.Generic.List<string> Scopes,
            ulong CreatedAt,
            ulong ExpiresAt,
            bool IsRevoked
        )
        {
            this.GrantId = GrantId;
            this.ClientId = ClientId;
            this.UserId = UserId;
            this.Type = Type;
            this.Scopes = Scopes;
            this.CreatedAt = CreatedAt;
            this.ExpiresAt = ExpiresAt;
            this.IsRevoked = IsRevoked;
        }

        public OpenIdConnectGrant()
        {
            this.GrantId = "";
            this.ClientId = "";
            this.Type = "";
            this.Scopes = new();
        }
    }
}
