// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class OpenIddictSpacetimeScope
    {
        [DataMember(Name = "Id")]
        public uint Id;
        [DataMember(Name = "OpenIddictScopeId")]
        public string OpenIddictScopeId;
        [DataMember(Name = "Name")]
        public string Name;
        [DataMember(Name = "Description")]
        public string? Description;
        [DataMember(Name = "Descriptions")]
        public string? Descriptions;
        [DataMember(Name = "DisplayName")]
        public string? DisplayName;
        [DataMember(Name = "DisplayNames")]
        public string? DisplayNames;
        [DataMember(Name = "Properties")]
        public string? Properties;
        [DataMember(Name = "Resources")]
        public string? Resources;

        public OpenIddictSpacetimeScope(
            uint Id,
            string OpenIddictScopeId,
            string Name,
            string? Description,
            string? Descriptions,
            string? DisplayName,
            string? DisplayNames,
            string? Properties,
            string? Resources
        )
        {
            this.Id = Id;
            this.OpenIddictScopeId = OpenIddictScopeId;
            this.Name = Name;
            this.Description = Description;
            this.Descriptions = Descriptions;
            this.DisplayName = DisplayName;
            this.DisplayNames = DisplayNames;
            this.Properties = Properties;
            this.Resources = Resources;
        }

        public OpenIddictSpacetimeScope()
        {
            this.OpenIddictScopeId = "";
            this.Name = "";
        }
    }
}
