// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class OpenIddictSpacetimeAuthorization
    {
<<<<<<< HEAD
        [DataMember(Name = "Id")]
        public uint Id;
        [DataMember(Name = "OpenIddictAuthorizationId")]
        public string OpenIddictAuthorizationId;
        [DataMember(Name = "ApplicationClientId")]
        public string? ApplicationClientId;
        [DataMember(Name = "CreationDate")]
        public ulong? CreationDate;
        [DataMember(Name = "Properties")]
        public string? Properties;
        [DataMember(Name = "Scopes")]
        public string? Scopes;
        [DataMember(Name = "Status")]
        public string? Status;
        [DataMember(Name = "Subject")]
        public string? Subject;
        [DataMember(Name = "Type")]
=======
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "open_iddict_authorization_id")]
        public string OpenIddictAuthorizationId;
        [DataMember(Name = "application_client_id")]
        public string? ApplicationClientId;
        [DataMember(Name = "creation_date")]
        public ulong? CreationDate;
        [DataMember(Name = "properties")]
        public string? Properties;
        [DataMember(Name = "scopes")]
        public string? Scopes;
        [DataMember(Name = "status")]
        public string? Status;
        [DataMember(Name = "subject")]
        public string? Subject;
        [DataMember(Name = "type")]
>>>>>>> maintofix
        public string? Type;

        public OpenIddictSpacetimeAuthorization(
            uint Id,
            string OpenIddictAuthorizationId,
            string? ApplicationClientId,
            ulong? CreationDate,
            string? Properties,
            string? Scopes,
            string? Status,
            string? Subject,
            string? Type
        )
        {
            this.Id = Id;
            this.OpenIddictAuthorizationId = OpenIddictAuthorizationId;
            this.ApplicationClientId = ApplicationClientId;
            this.CreationDate = CreationDate;
            this.Properties = Properties;
            this.Scopes = Scopes;
            this.Status = Status;
            this.Subject = Subject;
            this.Type = Type;
        }

        public OpenIddictSpacetimeAuthorization()
        {
            this.OpenIddictAuthorizationId = "";
        }
    }
}
