// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PassengerCount
    {
<<<<<<< HEAD
        [DataMember(Name = "PassengerCountId")]
        public uint PassengerCountId;
        [DataMember(Name = "Timestamp")]
        public ulong Timestamp;
        [DataMember(Name = "RouteId")]
        public uint RouteId;
        [DataMember(Name = "StopId")]
        public uint StopId;
        [DataMember(Name = "PassengerCountNumber")]
        public uint PassengerCountNumber;
        [DataMember(Name = "Notes")]
        public string? Notes;
        [DataMember(Name = "EmployeeId")]
=======
        [DataMember(Name = "passenger_count_id")]
        public uint PassengerCountId;
        [DataMember(Name = "timestamp")]
        public ulong Timestamp;
        [DataMember(Name = "route_id")]
        public uint RouteId;
        [DataMember(Name = "stop_id")]
        public uint StopId;
        [DataMember(Name = "passenger_count_number")]
        public uint PassengerCountNumber;
        [DataMember(Name = "notes")]
        public string? Notes;
        [DataMember(Name = "employee_id")]
>>>>>>> maintofix
        public uint? EmployeeId;

        public PassengerCount(
            uint PassengerCountId,
            ulong Timestamp,
            uint RouteId,
            uint StopId,
            uint PassengerCountNumber,
            string? Notes,
            uint? EmployeeId
        )
        {
            this.PassengerCountId = PassengerCountId;
            this.Timestamp = Timestamp;
            this.RouteId = RouteId;
            this.StopId = StopId;
            this.PassengerCountNumber = PassengerCountNumber;
            this.Notes = Notes;
            this.EmployeeId = EmployeeId;
        }

        public PassengerCount()
        {
        }
    }
}
