// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Permission
    {
        [DataMember(Name = "permission_id")]
        public uint PermissionId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "description")]
        public string Description;
        [DataMember(Name = "category")]
        public string Category;
        [DataMember(Name = "is_active")]
        public bool IsActive;
        [DataMember(Name = "created_at")]
        public ulong CreatedAt;

        public Permission(
            uint PermissionId,
            string Name,
            string Description,
            string Category,
            bool IsActive,
            ulong CreatedAt
        )
        {
            this.PermissionId = PermissionId;
            this.Name = Name;
            this.Description = Description;
            this.Category = Category;
            this.IsActive = IsActive;
            this.CreatedAt = CreatedAt;
        }

        public Permission()
        {
            this.Name = "";
            this.Description = "";
            this.Category = "";
        }
    }
}
