// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RolePermission
    {
        [DataMember(Name = "Id")]
        public uint Id;
        [DataMember(Name = "RoleId")]
        public uint RoleId;
        [DataMember(Name = "PermissionId")]
        public uint PermissionId;
        [DataMember(Name = "GrantedAt")]
        public ulong GrantedAt;
        [DataMember(Name = "GrantedBy")]
        public string? GrantedBy;

        public RolePermission(
            uint Id,
            uint RoleId,
            uint PermissionId,
            ulong GrantedAt,
            string? GrantedBy
        )
        {
            this.Id = Id;
            this.RoleId = RoleId;
            this.PermissionId = PermissionId;
            this.GrantedAt = GrantedAt;
            this.GrantedBy = GrantedBy;
        }

        public RolePermission()
        {
        }
    }
}
