// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Route
    {
        [DataMember(Name = "RouteId")]
        public uint RouteId;
        [DataMember(Name = "StartPoint")]
        public string StartPoint;
        [DataMember(Name = "EndPoint")]
        public string EndPoint;
        [DataMember(Name = "DriverId")]
        public uint DriverId;
        [DataMember(Name = "BusId")]
        public uint BusId;
        [DataMember(Name = "TravelTime")]
        public string? TravelTime;
        [DataMember(Name = "IsActive")]
        public bool IsActive;

        public Route(
            uint RouteId,
            string StartPoint,
            string EndPoint,
            uint DriverId,
            uint BusId,
            string? TravelTime,
            bool IsActive
        )
        {
            this.RouteId = RouteId;
            this.StartPoint = StartPoint;
            this.EndPoint = EndPoint;
            this.DriverId = DriverId;
            this.BusId = BusId;
            this.TravelTime = TravelTime;
            this.IsActive = IsActive;
        }

        public Route()
        {
            this.StartPoint = "";
            this.EndPoint = "";
        }
    }
}
