// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RouteSchedule
    {
<<<<<<< HEAD
        [DataMember(Name = "ScheduleId")]
        public uint ScheduleId;
        [DataMember(Name = "RouteId")]
        public uint RouteId;
        [DataMember(Name = "StartPoint")]
        public string? StartPoint;
        [DataMember(Name = "RouteStops")]
        public System.Collections.Generic.List<string>? RouteStops;
        [DataMember(Name = "EndPoint")]
        public string? EndPoint;
        [DataMember(Name = "DepartureTime")]
        public ulong DepartureTime;
        [DataMember(Name = "ArrivalTime")]
        public ulong ArrivalTime;
        [DataMember(Name = "Price")]
        public double Price;
        [DataMember(Name = "AvailableSeats")]
        public uint AvailableSeats;
        [DataMember(Name = "SeatedCapacity")]
        public uint? SeatedCapacity;
        [DataMember(Name = "StandingCapacity")]
        public uint? StandingCapacity;
        [DataMember(Name = "DaysOfWeek")]
        public System.Collections.Generic.List<string>? DaysOfWeek;
        [DataMember(Name = "BusTypes")]
        public System.Collections.Generic.List<string>? BusTypes;
        [DataMember(Name = "IsActive")]
        public bool IsActive;
        [DataMember(Name = "ValidFrom")]
        public ulong ValidFrom;
        [DataMember(Name = "ValidUntil")]
        public ulong? ValidUntil;
        [DataMember(Name = "StopDurationMinutes")]
        public uint? StopDurationMinutes;
        [DataMember(Name = "IsRecurring")]
        public bool IsRecurring;
        [DataMember(Name = "EstimatedStopTimes")]
        public System.Collections.Generic.List<string>? EstimatedStopTimes;
        [DataMember(Name = "StopDistances")]
        public System.Collections.Generic.List<double>? StopDistances;
        [DataMember(Name = "Notes")]
        public string? Notes;
        [DataMember(Name = "CreatedAt")]
        public ulong CreatedAt;
        [DataMember(Name = "UpdatedAt")]
        public ulong? UpdatedAt;
        [DataMember(Name = "UpdatedBy")]
        public string? UpdatedBy;
        [DataMember(Name = "PeakHourLoad")]
        public double? PeakHourLoad;
        [DataMember(Name = "OffPeakHourLoad")]
        public double? OffPeakHourLoad;
        [DataMember(Name = "IsSpecialEvent")]
        public bool? IsSpecialEvent;
        [DataMember(Name = "SpecialEventName")]
        public string? SpecialEventName;
        [DataMember(Name = "IsHoliday")]
        public bool? IsHoliday;
        [DataMember(Name = "HolidayName")]
        public string? HolidayName;
        [DataMember(Name = "IsWeekend")]
        public bool? IsWeekend;
        [DataMember(Name = "SeatConfigurationId")]
        public uint? SeatConfigurationId;
        [DataMember(Name = "RequiresSeatReservation")]
        public bool? RequiresSeatReservation;
        [DataMember(Name = "RouteType")]
=======
        [DataMember(Name = "schedule_id")]
        public uint ScheduleId;
        [DataMember(Name = "route_id")]
        public uint RouteId;
        [DataMember(Name = "start_point")]
        public string? StartPoint;
        [DataMember(Name = "route_stops")]
        public System.Collections.Generic.List<string>? RouteStops;
        [DataMember(Name = "end_point")]
        public string? EndPoint;
        [DataMember(Name = "departure_time")]
        public ulong DepartureTime;
        [DataMember(Name = "arrival_time")]
        public ulong ArrivalTime;
        [DataMember(Name = "price")]
        public double Price;
        [DataMember(Name = "available_seats")]
        public uint AvailableSeats;
        [DataMember(Name = "seated_capacity")]
        public uint? SeatedCapacity;
        [DataMember(Name = "standing_capacity")]
        public uint? StandingCapacity;
        [DataMember(Name = "days_of_week")]
        public System.Collections.Generic.List<string>? DaysOfWeek;
        [DataMember(Name = "bus_types")]
        public System.Collections.Generic.List<string>? BusTypes;
        [DataMember(Name = "is_active")]
        public bool IsActive;
        [DataMember(Name = "valid_from")]
        public ulong ValidFrom;
        [DataMember(Name = "valid_until")]
        public ulong? ValidUntil;
        [DataMember(Name = "stop_duration_minutes")]
        public uint? StopDurationMinutes;
        [DataMember(Name = "is_recurring")]
        public bool IsRecurring;
        [DataMember(Name = "estimated_stop_times")]
        public System.Collections.Generic.List<string>? EstimatedStopTimes;
        [DataMember(Name = "stop_distances")]
        public System.Collections.Generic.List<double>? StopDistances;
        [DataMember(Name = "notes")]
        public string? Notes;
        [DataMember(Name = "created_at")]
        public ulong CreatedAt;
        [DataMember(Name = "updated_at")]
        public ulong? UpdatedAt;
        [DataMember(Name = "updated_by")]
        public string? UpdatedBy;
        [DataMember(Name = "peak_hour_load")]
        public double? PeakHourLoad;
        [DataMember(Name = "off_peak_hour_load")]
        public double? OffPeakHourLoad;
        [DataMember(Name = "is_special_event")]
        public bool? IsSpecialEvent;
        [DataMember(Name = "special_event_name")]
        public string? SpecialEventName;
        [DataMember(Name = "is_holiday")]
        public bool? IsHoliday;
        [DataMember(Name = "holiday_name")]
        public string? HolidayName;
        [DataMember(Name = "is_weekend")]
        public bool? IsWeekend;
        [DataMember(Name = "seat_configuration_id")]
        public uint? SeatConfigurationId;
        [DataMember(Name = "requires_seat_reservation")]
        public bool? RequiresSeatReservation;
        [DataMember(Name = "route_type")]
>>>>>>> maintofix
        public string? RouteType;

        public RouteSchedule(
            uint ScheduleId,
            uint RouteId,
            string? StartPoint,
            System.Collections.Generic.List<string>? RouteStops,
            string? EndPoint,
            ulong DepartureTime,
            ulong ArrivalTime,
            double Price,
            uint AvailableSeats,
            uint? SeatedCapacity,
            uint? StandingCapacity,
            System.Collections.Generic.List<string>? DaysOfWeek,
            System.Collections.Generic.List<string>? BusTypes,
            bool IsActive,
            ulong ValidFrom,
            ulong? ValidUntil,
            uint? StopDurationMinutes,
            bool IsRecurring,
            System.Collections.Generic.List<string>? EstimatedStopTimes,
            System.Collections.Generic.List<double>? StopDistances,
            string? Notes,
            ulong CreatedAt,
            ulong? UpdatedAt,
            string? UpdatedBy,
            double? PeakHourLoad,
            double? OffPeakHourLoad,
            bool? IsSpecialEvent,
            string? SpecialEventName,
            bool? IsHoliday,
            string? HolidayName,
            bool? IsWeekend,
            uint? SeatConfigurationId,
            bool? RequiresSeatReservation,
            string? RouteType
        )
        {
            this.ScheduleId = ScheduleId;
            this.RouteId = RouteId;
            this.StartPoint = StartPoint;
            this.RouteStops = RouteStops;
            this.EndPoint = EndPoint;
            this.DepartureTime = DepartureTime;
            this.ArrivalTime = ArrivalTime;
            this.Price = Price;
            this.AvailableSeats = AvailableSeats;
            this.SeatedCapacity = SeatedCapacity;
            this.StandingCapacity = StandingCapacity;
            this.DaysOfWeek = DaysOfWeek;
            this.BusTypes = BusTypes;
            this.IsActive = IsActive;
            this.ValidFrom = ValidFrom;
            this.ValidUntil = ValidUntil;
            this.StopDurationMinutes = StopDurationMinutes;
            this.IsRecurring = IsRecurring;
            this.EstimatedStopTimes = EstimatedStopTimes;
            this.StopDistances = StopDistances;
            this.Notes = Notes;
            this.CreatedAt = CreatedAt;
            this.UpdatedAt = UpdatedAt;
            this.UpdatedBy = UpdatedBy;
            this.PeakHourLoad = PeakHourLoad;
            this.OffPeakHourLoad = OffPeakHourLoad;
            this.IsSpecialEvent = IsSpecialEvent;
            this.SpecialEventName = SpecialEventName;
            this.IsHoliday = IsHoliday;
            this.HolidayName = HolidayName;
            this.IsWeekend = IsWeekend;
            this.SeatConfigurationId = SeatConfigurationId;
            this.RequiresSeatReservation = RequiresSeatReservation;
            this.RouteType = RouteType;
        }

        public RouteSchedule()
        {
        }
    }
}
