// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SeatConfiguration
    {
        [DataMember(Name = "ConfigurationId")]
        public uint ConfigurationId;
        [DataMember(Name = "BusId")]
        public uint BusId;
        [DataMember(Name = "SeatNumber")]
        public uint SeatNumber;
        [DataMember(Name = "SeatType")]
        public string SeatType;
        [DataMember(Name = "SeatStatus")]
        public string SeatStatus;
        [DataMember(Name = "SeatRow")]
        public uint SeatRow;
        [DataMember(Name = "SeatColumn")]
        public uint SeatColumn;
        [DataMember(Name = "IsAccessible")]
        public bool IsAccessible;
        [DataMember(Name = "IsEmergencyExit")]
        public bool IsEmergencyExit;
        [DataMember(Name = "Notes")]
        public string? Notes;
        [DataMember(Name = "CreatedAt")]
        public ulong CreatedAt;
        [DataMember(Name = "CreatedBy")]
        public string? CreatedBy;
        [DataMember(Name = "UpdatedAt")]
        public ulong? UpdatedAt;
        [DataMember(Name = "UpdatedBy")]
        public string? UpdatedBy;

        public SeatConfiguration(
            uint ConfigurationId,
            uint BusId,
            uint SeatNumber,
            string SeatType,
            string SeatStatus,
            uint SeatRow,
            uint SeatColumn,
            bool IsAccessible,
            bool IsEmergencyExit,
            string? Notes,
            ulong CreatedAt,
            string? CreatedBy,
            ulong? UpdatedAt,
            string? UpdatedBy
        )
        {
            this.ConfigurationId = ConfigurationId;
            this.BusId = BusId;
            this.SeatNumber = SeatNumber;
            this.SeatType = SeatType;
            this.SeatStatus = SeatStatus;
            this.SeatRow = SeatRow;
            this.SeatColumn = SeatColumn;
            this.IsAccessible = IsAccessible;
            this.IsEmergencyExit = IsEmergencyExit;
            this.Notes = Notes;
            this.CreatedAt = CreatedAt;
            this.CreatedBy = CreatedBy;
            this.UpdatedAt = UpdatedAt;
            this.UpdatedBy = UpdatedBy;
        }

        public SeatConfiguration()
        {
            this.SeatType = "";
            this.SeatStatus = "";
        }
    }
}
