// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TotpSecret
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "user_id")]
        public SpacetimeDB.Identity UserId;
        [DataMember(Name = "secret")]
        public string Secret;
        [DataMember(Name = "created_at")]
        public ulong CreatedAt;
        [DataMember(Name = "is_active")]
        public bool IsActive;

        public TotpSecret(
            uint Id,
            SpacetimeDB.Identity UserId,
            string Secret,
            ulong CreatedAt,
            bool IsActive
        )
        {
            this.Id = Id;
            this.UserId = UserId;
            this.Secret = Secret;
            this.CreatedAt = CreatedAt;
            this.IsActive = IsActive;
        }

        public TotpSecret()
        {
            this.Secret = "";
        }
    }
}
