// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class UserRole
    {
<<<<<<< HEAD
        [DataMember(Name = "Id")]
        public uint Id;
        [DataMember(Name = "UserId")]
        public SpacetimeDB.Identity UserId;
        [DataMember(Name = "RoleId")]
        public uint RoleId;
        [DataMember(Name = "AssignedAt")]
        public ulong AssignedAt;
        [DataMember(Name = "AssignedBy")]
=======
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "user_id")]
        public SpacetimeDB.Identity UserId;
        [DataMember(Name = "role_id")]
        public uint RoleId;
        [DataMember(Name = "assigned_at")]
        public ulong AssignedAt;
        [DataMember(Name = "assigned_by")]
>>>>>>> maintofix
        public string? AssignedBy;

        public UserRole(
            uint Id,
            SpacetimeDB.Identity UserId,
            uint RoleId,
            ulong AssignedAt,
            string? AssignedBy
        )
        {
            this.Id = Id;
            this.UserId = UserId;
            this.RoleId = RoleId;
            this.AssignedAt = AssignedAt;
            this.AssignedBy = AssignedBy;
        }

        public UserRole()
        {
        }
    }
}
