// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WebAuthnChallenge
    {
        [DataMember(Name = "Id")]
        public uint Id;
        [DataMember(Name = "UserId")]
        public SpacetimeDB.Identity UserId;
        [DataMember(Name = "Challenge")]
        public string Challenge;
        [DataMember(Name = "ExpiresAt")]
        public ulong ExpiresAt;
        [DataMember(Name = "CreatedAt")]
        public ulong CreatedAt;

        public WebAuthnChallenge(
            uint Id,
            SpacetimeDB.Identity UserId,
            string Challenge,
            ulong ExpiresAt,
            ulong CreatedAt
        )
        {
            this.Id = Id;
            this.UserId = UserId;
            this.Challenge = Challenge;
            this.ExpiresAt = ExpiresAt;
            this.CreatedAt = CreatedAt;
        }

        public WebAuthnChallenge()
        {
            this.Challenge = "";
        }
    }
}
