// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.1.0 (commit 6981f48b4bc1a71c8dd9bdfe5a2c343f6370243d).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        internal RemoteReducers(DbConnection conn) : base(conn) { }
        internal event Action<ReducerEventContext, Exception>? InternalOnUnhandledReducerError;
    }

    public sealed partial class RemoteProcedures : RemoteBase
    {
        internal RemoteProcedures(DbConnection conn) : base(conn) { }
    }

    public sealed partial class RemoteTables : RemoteTablesBase
    {
        public RemoteTables(DbConnection conn)
        {
            AddTable(AdminActionLog = new(conn));
            AddTable(AuthenticationEvent = new(conn));
            AddTable(Bus = new(conn));
            AddTable(BusIdCounter = new(conn));
            AddTable(BusLocation = new(conn));
            AddTable(BusStatusEvent = new(conn));
            AddTable(BusStop = new(conn));
            AddTable(CashierDay = new(conn));
            AddTable(Client = new(conn));
            AddTable(ConductorStatistics = new(conn));
            AddTable(DiscountIdCounter = new(conn));
            AddTable(Discounts = new(conn));
            AddTable(Employee = new(conn));
            AddTable(EmployeeIdCounter = new(conn));
            AddTable(EmployeeShift = new(conn));
            AddTable(FeatureFlagOverride = new(conn));
            AddTable(FuelRecord = new(conn));
            AddTable(Incident = new(conn));
            AddTable(Job = new(conn));
            AddTable(JobIdCounter = new(conn));
            AddTable(LogIdCounter = new(conn));
            AddTable(MagicLinkToken = new(conn));
            AddTable(Maintenance = new(conn));
            AddTable(MaintenanceEvent = new(conn));
            AddTable(MaintenanceIdCounter = new(conn));
            AddTable(OidcAuthorizationIdCounter = new(conn));
            AddTable(OidcScopeIdCounter = new(conn));
            AddTable(OidcTokenIdCounter = new(conn));
            AddTable(OpenIdConnect = new(conn));
            AddTable(OpenIdConnectGrant = new(conn));
            AddTable(OpenIddictSpacetimeAuthorization = new(conn));
            AddTable(OpenIddictSpacetimeScope = new(conn));
            AddTable(OpenIddictSpacetimeToken = new(conn));
            AddTable(Passenger = new(conn));
            AddTable(PassengerCount = new(conn));
            AddTable(PassengerIdCounter = new(conn));
            AddTable(Permission = new(conn));
            AddTable(PermissionIdCounter = new(conn));
            AddTable(Person = new(conn));
            AddTable(QrSession = new(conn));
            AddTable(Role = new(conn));
            AddTable(RoleIdCounter = new(conn));
            AddTable(RolePermission = new(conn));
            AddTable(RolePermissionIdCounter = new(conn));
            AddTable(Route = new(conn));
            AddTable(RouteConductor = new(conn));
            AddTable(RouteIdCounter = new(conn));
            AddTable(RouteSchedule = new(conn));
            AddTable(RouteScheduleEvent = new(conn));
            AddTable(Sale = new(conn));
            AddTable(SaleIdCounter = new(conn));
            AddTable(ScheduleIdCounter = new(conn));
            AddTable(SeatConfiguration = new(conn));
            AddTable(SeatConfigurationIdCounter = new(conn));
            AddTable(Ticket = new(conn));
            AddTable(TicketIdCounter = new(conn));
            AddTable(TicketSaleEvent = new(conn));
            AddTable(TotpSecret = new(conn));
            AddTable(TotpSecretIdCounter = new(conn));
            AddTable(TwoFactorToken = new(conn));
            AddTable(TwoFactorTokenIdCounter = new(conn));
            AddTable(UserIdCounter = new(conn));
            AddTable(UserProfile = new(conn));
            AddTable(UserRole = new(conn));
            AddTable(UserRoleIdCounter = new(conn));
            AddTable(UserSettings = new(conn));
            AddTable(WebAuthnChallenge = new(conn));
            AddTable(WebAuthnChallengeIdCounter = new(conn));
            AddTable(WebAuthnCredential = new(conn));
            AddTable(WebAuthnCredentialIdCounter = new(conn));
        }
    }


        public interface IRemoteDbContext : IDbContext<RemoteTables, RemoteReducers, SubscriptionBuilder, RemoteProcedures> {
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError;
        }

        public sealed class EventContext : IEventContext, IRemoteDbContext
        {
            private readonly DbConnection conn;

            /// <summary>
            /// The event that caused this callback to run.
            /// </summary>
            public readonly Event<Reducer> Event;

            /// <summary>
            /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
            ///
            /// The returned <c>DbView</c> will have a method to access each table defined by the module.
            /// </summary>
            public RemoteTables Db => conn.Db;
            /// <summary>
            /// Access to reducers defined by the module.
            ///
            /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
            /// plus methods for adding and removing callbacks on each of those reducers.
            /// </summary>
            public RemoteReducers Reducers => conn.Reducers;
            /// <summary>
            /// Access to procedures defined by the module.
            ///
            /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
            /// with a callback for when the procedure completes and returns a value.
            /// </summary>
            public RemoteProcedures Procedures => conn.Procedures;
            /// <summary>
            /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
            /// </summary>
            public bool IsActive => conn.IsActive;
            /// <summary>
            /// Close the connection.
            ///
            /// Throws an error if the connection is already closed.
            /// </summary>
            public void Disconnect() {
                conn.Disconnect();
            }
            /// <summary>
            /// Start building a subscription.
            /// </summary>
            /// <returns>A builder-pattern constructor for subscribing to queries,
            /// causing matching rows to be replicated into the client cache.</returns>
            public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
            /// <summary>
            /// Get the <c>Identity</c> of this connection.
            ///
            /// This method returns null if the connection was constructed anonymously
            /// and we have not yet received our newly-generated <c>Identity</c> from the host.
            /// </summary>
            public Identity? Identity => conn.Identity;
            /// <summary>
            /// Get this connection's <c>ConnectionId</c>.
            /// </summary>
            public ConnectionId ConnectionId => conn.ConnectionId;
            /// <summary>
            /// Register a callback to be called when a reducer with no handler returns an error.
            /// </summary>
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
                add => Reducers.InternalOnUnhandledReducerError += value;
                remove => Reducers.InternalOnUnhandledReducerError -= value;
            }

            internal EventContext(DbConnection conn, Event<Reducer> Event)
            {
                this.conn = conn;
                this.Event = Event;
            }
        }

        public sealed class ReducerEventContext : IReducerEventContext, IRemoteDbContext
        {
            private readonly DbConnection conn;
            /// <summary>
            /// The reducer event that caused this callback to run.
            /// </summary>
            public readonly ReducerEvent<Reducer> Event;

            /// <summary>
            /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
            ///
            /// The returned <c>DbView</c> will have a method to access each table defined by the module.
            /// </summary>
            public RemoteTables Db => conn.Db;
            /// <summary>
            /// Access to reducers defined by the module.
            ///
            /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
            /// plus methods for adding and removing callbacks on each of those reducers.
            /// </summary>
            public RemoteReducers Reducers => conn.Reducers;
            /// <summary>
            /// Access to procedures defined by the module.
            ///
            /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
            /// with a callback for when the procedure completes and returns a value.
            /// </summary>
            public RemoteProcedures Procedures => conn.Procedures;
            /// <summary>
            /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
            /// </summary>
            public bool IsActive => conn.IsActive;
            /// <summary>
            /// Close the connection.
            ///
            /// Throws an error if the connection is already closed.
            /// </summary>
            public void Disconnect() {
                conn.Disconnect();
            }
            /// <summary>
            /// Start building a subscription.
            /// </summary>
            /// <returns>A builder-pattern constructor for subscribing to queries,
            /// causing matching rows to be replicated into the client cache.</returns>
            public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
            /// <summary>
            /// Get the <c>Identity</c> of this connection.
            ///
            /// This method returns null if the connection was constructed anonymously
            /// and we have not yet received our newly-generated <c>Identity</c> from the host.
            /// </summary>
            public Identity? Identity => conn.Identity;
            /// <summary>
            /// Get this connection's <c>ConnectionId</c>.
            /// </summary>
            public ConnectionId ConnectionId => conn.ConnectionId;
            /// <summary>
            /// Register a callback to be called when a reducer with no handler returns an error.
            /// </summary>
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
                add => Reducers.InternalOnUnhandledReducerError += value;
                remove => Reducers.InternalOnUnhandledReducerError -= value;
            }

            internal ReducerEventContext(DbConnection conn, ReducerEvent<Reducer> reducerEvent)
            {
                this.conn = conn;
                Event = reducerEvent;
            }
        }

        public sealed class ErrorContext : IErrorContext, IRemoteDbContext
        {
            private readonly DbConnection conn;
            /// <summary>
            /// The <c>Exception</c> that caused this error callback to be run.
            /// </summary>
            public readonly Exception Event;
            Exception IErrorContext.Event {
                get {
                    return Event;
                }
            }

            /// <summary>
            /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
            ///
            /// The returned <c>DbView</c> will have a method to access each table defined by the module.
            /// </summary>
            public RemoteTables Db => conn.Db;
            /// <summary>
            /// Access to reducers defined by the module.
            ///
            /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
            /// plus methods for adding and removing callbacks on each of those reducers.
            /// </summary>
            public RemoteReducers Reducers => conn.Reducers;
            /// <summary>
            /// Access to procedures defined by the module.
            ///
            /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
            /// with a callback for when the procedure completes and returns a value.
            /// </summary>
            public RemoteProcedures Procedures => conn.Procedures;
            /// <summary>
            /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
            /// </summary>
            public bool IsActive => conn.IsActive;
            /// <summary>
            /// Close the connection.
            ///
            /// Throws an error if the connection is already closed.
            /// </summary>
            public void Disconnect() {
                conn.Disconnect();
            }
            /// <summary>
            /// Start building a subscription.
            /// </summary>
            /// <returns>A builder-pattern constructor for subscribing to queries,
            /// causing matching rows to be replicated into the client cache.</returns>
            public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
            /// <summary>
            /// Get the <c>Identity</c> of this connection.
            ///
            /// This method returns null if the connection was constructed anonymously
            /// and we have not yet received our newly-generated <c>Identity</c> from the host.
            /// </summary>
            public Identity? Identity => conn.Identity;
            /// <summary>
            /// Get this connection's <c>ConnectionId</c>.
            /// </summary>
            public ConnectionId ConnectionId => conn.ConnectionId;
            /// <summary>
            /// Register a callback to be called when a reducer with no handler returns an error.
            /// </summary>
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
                add => Reducers.InternalOnUnhandledReducerError += value;
                remove => Reducers.InternalOnUnhandledReducerError -= value;
            }

            internal ErrorContext(DbConnection conn, Exception error)
            {
                this.conn = conn;
                Event = error;
            }
        }

        public sealed class SubscriptionEventContext : ISubscriptionEventContext, IRemoteDbContext
        {
            private readonly DbConnection conn;

            /// <summary>
            /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
            ///
            /// The returned <c>DbView</c> will have a method to access each table defined by the module.
            /// </summary>
            public RemoteTables Db => conn.Db;
            /// <summary>
            /// Access to reducers defined by the module.
            ///
            /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
            /// plus methods for adding and removing callbacks on each of those reducers.
            /// </summary>
            public RemoteReducers Reducers => conn.Reducers;
            /// <summary>
            /// Access to procedures defined by the module.
            ///
            /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
            /// with a callback for when the procedure completes and returns a value.
            /// </summary>
            public RemoteProcedures Procedures => conn.Procedures;
            /// <summary>
            /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
            /// </summary>
            public bool IsActive => conn.IsActive;
            /// <summary>
            /// Close the connection.
            ///
            /// Throws an error if the connection is already closed.
            /// </summary>
            public void Disconnect() {
                conn.Disconnect();
            }
            /// <summary>
            /// Start building a subscription.
            /// </summary>
            /// <returns>A builder-pattern constructor for subscribing to queries,
            /// causing matching rows to be replicated into the client cache.</returns>
            public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
            /// <summary>
            /// Get the <c>Identity</c> of this connection.
            ///
            /// This method returns null if the connection was constructed anonymously
            /// and we have not yet received our newly-generated <c>Identity</c> from the host.
            /// </summary>
            public Identity? Identity => conn.Identity;
            /// <summary>
            /// Get this connection's <c>ConnectionId</c>.
            /// </summary>
            public ConnectionId ConnectionId => conn.ConnectionId;
            /// <summary>
            /// Register a callback to be called when a reducer with no handler returns an error.
            /// </summary>
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
                add => Reducers.InternalOnUnhandledReducerError += value;
                remove => Reducers.InternalOnUnhandledReducerError -= value;
            }

            internal SubscriptionEventContext(DbConnection conn)
            {
                this.conn = conn;
            }
        }

        public sealed class ProcedureEventContext : IProcedureEventContext, IRemoteDbContext
        {
            private readonly DbConnection conn;
            /// <summary>
            /// The procedure event that caused this callback to run.
            /// </summary>
            public readonly ProcedureEvent Event;

            /// <summary>
            /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
            ///
            /// The returned <c>DbView</c> will have a method to access each table defined by the module.
            /// </summary>
            public RemoteTables Db => conn.Db;
            /// <summary>
            /// Access to reducers defined by the module.
            ///
            /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
            /// plus methods for adding and removing callbacks on each of those reducers.
            /// </summary>
            public RemoteReducers Reducers => conn.Reducers;
            /// <summary>
            /// Access to procedures defined by the module.
            ///
            /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
            /// with a callback for when the procedure completes and returns a value.
            /// </summary>
            public RemoteProcedures Procedures => conn.Procedures;
            /// <summary>
            /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
            /// </summary>
            public bool IsActive => conn.IsActive;
            /// <summary>
            /// Close the connection.
            ///
            /// Throws an error if the connection is already closed.
            /// </summary>
            public void Disconnect() {
                conn.Disconnect();
            }
            /// <summary>
            /// Start building a subscription.
            /// </summary>
            /// <returns>A builder-pattern constructor for subscribing to queries,
            /// causing matching rows to be replicated into the client cache.</returns>
            public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
            /// <summary>
            /// Get the <c>Identity</c> of this connection.
            ///
            /// This method returns null if the connection was constructed anonymously
            /// and we have not yet received our newly-generated <c>Identity</c> from the host.
            /// </summary>
            public Identity? Identity => conn.Identity;
            /// <summary>
            /// Get this connection's <c>ConnectionId</c>.
            /// </summary>
            public ConnectionId ConnectionId => conn.ConnectionId;
            /// <summary>
            /// Register a callback to be called when a reducer with no handler returns an error.
            /// </summary>
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
                add => Reducers.InternalOnUnhandledReducerError += value;
                remove => Reducers.InternalOnUnhandledReducerError -= value;
            }

            internal ProcedureEventContext(DbConnection conn, ProcedureEvent Event)
            {
                this.conn = conn;
                this.Event = Event;
            }
        }

        /// <summary>
        /// Builder-pattern constructor for subscription queries.
        /// </summary>
        public sealed class SubscriptionBuilder
        {
            private readonly IDbConnection conn;

            private event Action<SubscriptionEventContext>? Applied;
            private event Action<ErrorContext, Exception>? Error;

            /// <summary>
            /// Private API, use <c>conn.SubscriptionBuilder()</c> instead.
            /// </summary>
            public SubscriptionBuilder(IDbConnection conn)
            {
                this.conn = conn;
            }

            /// <summary>
            /// Register a callback to run when the subscription is applied.
            /// </summary>
            public SubscriptionBuilder OnApplied(
                Action<SubscriptionEventContext> callback
            )
            {
                Applied += callback;
                return this;
            }

            /// <summary>
            /// Register a callback to run when the subscription fails.
            ///
            /// Note that this callback may run either when attempting to apply the subscription,
            /// in which case <c>Self::on_applied</c> will never run,
            /// or later during the subscription's lifetime if the module's interface changes,
            /// in which case <c>Self::on_applied</c> may have already run.
            /// </summary>
            public SubscriptionBuilder OnError(
                Action<ErrorContext, Exception> callback
            )
            {
                Error += callback;
                return this;
            }
        
            /// <summary>
            /// Add a typed query to this subscription.
            ///
            /// This is the entry point for building subscriptions without writing SQL by hand.
            /// Once a typed query is added, only typed queries may follow (SQL and typed queries cannot be mixed).
            /// </summary>
            public TypedSubscriptionBuilder AddQuery<TRow>(
                Func<QueryBuilder, global::SpacetimeDB.IQuery<TRow>> build
            )
            {
                var typed = new TypedSubscriptionBuilder(conn, Applied, Error);
                return typed.AddQuery(build);
            }

            /// <summary>
            /// Subscribe to the following SQL queries.
            ///
            /// This method returns immediately, with the data not yet added to the DbConnection.
            /// The provided callbacks will be invoked once the data is returned from the remote server.
            /// Data from all the provided queries will be returned at the same time.
            ///
            /// See the SpacetimeDB SQL docs for more information on SQL syntax:
            /// <a href="https://spacetimedb.com/docs/sql">https://spacetimedb.com/docs/sql</a>
            /// </summary>
            public SubscriptionHandle Subscribe(
                string[] querySqls
            ) => new(conn, Applied, Error, querySqls);

            /// <summary>
            /// Subscribe to all rows from all tables.
            ///
            /// This method is intended as a convenience
            /// for applications where client-side memory use and network bandwidth are not concerns.
            /// Applications where these resources are a constraint
            /// should register more precise queries via <c>Self.Subscribe</c>
            /// in order to replicate only the subset of data which the client needs to function.
            ///
            /// This method should not be combined with <c>Self.Subscribe</c> on the same <c>DbConnection</c>.
            /// A connection may either <c>Self.Subscribe</c> to particular queries,
            /// or <c>Self.SubscribeToAllTables</c>, but not both.
            /// Attempting to call <c>Self.Subscribe</c>
            /// on a <c>DbConnection</c> that has previously used <c>Self.SubscribeToAllTables</c>,
            /// or vice versa, may misbehave in any number of ways,
            /// including dropping subscriptions, corrupting the client cache, or panicking.
            /// </summary>
            public SubscriptionHandle SubscribeToAllTables() =>
                new(conn, Applied, Error, QueryBuilder.AllTablesSqlQueries());
        }

        public sealed class SubscriptionHandle : SubscriptionHandleBase<SubscriptionEventContext, ErrorContext> {
            /// <summary>
            /// Internal API. Construct <c>SubscriptionHandle</c>s using <c>conn.SubscriptionBuilder</c>.
            /// </summary>
            public SubscriptionHandle(
                IDbConnection conn,
                Action<SubscriptionEventContext>? onApplied,
                Action<ErrorContext, Exception>? onError,
                string[] querySqls
            ) : base(conn, onApplied, onError, querySqls)
            { }
        }

    public sealed class QueryBuilder
    {
        public From From { get; } = new();

        internal static string[] AllTablesSqlQueries() => new string[]
        {
            new QueryBuilder().From.AdminActionLog().ToSql(),
            new QueryBuilder().From.AuthenticationEvent().ToSql(),
            new QueryBuilder().From.Bus().ToSql(),
            new QueryBuilder().From.BusIdCounter().ToSql(),
            new QueryBuilder().From.BusLocation().ToSql(),
            new QueryBuilder().From.BusStatusEvent().ToSql(),
            new QueryBuilder().From.BusStop().ToSql(),
            new QueryBuilder().From.CashierDay().ToSql(),
            new QueryBuilder().From.Client().ToSql(),
            new QueryBuilder().From.ConductorStatistics().ToSql(),
            new QueryBuilder().From.DiscountIdCounter().ToSql(),
            new QueryBuilder().From.Discounts().ToSql(),
            new QueryBuilder().From.Employee().ToSql(),
            new QueryBuilder().From.EmployeeIdCounter().ToSql(),
            new QueryBuilder().From.EmployeeShift().ToSql(),
            new QueryBuilder().From.FeatureFlagOverride().ToSql(),
            new QueryBuilder().From.FuelRecord().ToSql(),
            new QueryBuilder().From.Incident().ToSql(),
            new QueryBuilder().From.Job().ToSql(),
            new QueryBuilder().From.JobIdCounter().ToSql(),
            new QueryBuilder().From.LogIdCounter().ToSql(),
            new QueryBuilder().From.MagicLinkToken().ToSql(),
            new QueryBuilder().From.Maintenance().ToSql(),
            new QueryBuilder().From.MaintenanceEvent().ToSql(),
            new QueryBuilder().From.MaintenanceIdCounter().ToSql(),
            new QueryBuilder().From.OidcAuthorizationIdCounter().ToSql(),
            new QueryBuilder().From.OidcScopeIdCounter().ToSql(),
            new QueryBuilder().From.OidcTokenIdCounter().ToSql(),
            new QueryBuilder().From.OpenIdConnect().ToSql(),
            new QueryBuilder().From.OpenIdConnectGrant().ToSql(),
            new QueryBuilder().From.OpenIddictSpacetimeAuthorization().ToSql(),
            new QueryBuilder().From.OpenIddictSpacetimeScope().ToSql(),
            new QueryBuilder().From.OpenIddictSpacetimeToken().ToSql(),
            new QueryBuilder().From.Passenger().ToSql(),
            new QueryBuilder().From.PassengerCount().ToSql(),
            new QueryBuilder().From.PassengerIdCounter().ToSql(),
            new QueryBuilder().From.Permission().ToSql(),
            new QueryBuilder().From.PermissionIdCounter().ToSql(),
            new QueryBuilder().From.Person().ToSql(),
            new QueryBuilder().From.QrSession().ToSql(),
            new QueryBuilder().From.Role().ToSql(),
            new QueryBuilder().From.RoleIdCounter().ToSql(),
            new QueryBuilder().From.RolePermission().ToSql(),
            new QueryBuilder().From.RolePermissionIdCounter().ToSql(),
            new QueryBuilder().From.Route().ToSql(),
            new QueryBuilder().From.RouteConductor().ToSql(),
            new QueryBuilder().From.RouteIdCounter().ToSql(),
            new QueryBuilder().From.RouteSchedule().ToSql(),
            new QueryBuilder().From.RouteScheduleEvent().ToSql(),
            new QueryBuilder().From.Sale().ToSql(),
            new QueryBuilder().From.SaleIdCounter().ToSql(),
            new QueryBuilder().From.ScheduleIdCounter().ToSql(),
            new QueryBuilder().From.SeatConfiguration().ToSql(),
            new QueryBuilder().From.SeatConfigurationIdCounter().ToSql(),
            new QueryBuilder().From.Ticket().ToSql(),
            new QueryBuilder().From.TicketIdCounter().ToSql(),
            new QueryBuilder().From.TicketSaleEvent().ToSql(),
            new QueryBuilder().From.TotpSecret().ToSql(),
            new QueryBuilder().From.TotpSecretIdCounter().ToSql(),
            new QueryBuilder().From.TwoFactorToken().ToSql(),
            new QueryBuilder().From.TwoFactorTokenIdCounter().ToSql(),
            new QueryBuilder().From.UserIdCounter().ToSql(),
            new QueryBuilder().From.UserProfile().ToSql(),
            new QueryBuilder().From.UserRole().ToSql(),
            new QueryBuilder().From.UserRoleIdCounter().ToSql(),
            new QueryBuilder().From.UserSettings().ToSql(),
            new QueryBuilder().From.WebAuthnChallenge().ToSql(),
            new QueryBuilder().From.WebAuthnChallengeIdCounter().ToSql(),
            new QueryBuilder().From.WebAuthnCredential().ToSql(),
            new QueryBuilder().From.WebAuthnCredentialIdCounter().ToSql(),
        }
        ;
    }

    public sealed class From
    {
        public global::SpacetimeDB.Table<AdminActionLog, AdminActionLogCols, AdminActionLogIxCols> AdminActionLog() => new("admin_action_log", new AdminActionLogCols("admin_action_log"), new AdminActionLogIxCols("admin_action_log"));
        public global::SpacetimeDB.Table<AuthenticationEvent, AuthenticationEventCols, AuthenticationEventIxCols> AuthenticationEvent() => new("authentication_event", new AuthenticationEventCols("authentication_event"), new AuthenticationEventIxCols("authentication_event"));
        public global::SpacetimeDB.Table<Bus, BusCols, BusIxCols> Bus() => new("bus", new BusCols("bus"), new BusIxCols("bus"));
        public global::SpacetimeDB.Table<BusIdCounter, BusIdCounterCols, BusIdCounterIxCols> BusIdCounter() => new("bus_id_counter", new BusIdCounterCols("bus_id_counter"), new BusIdCounterIxCols("bus_id_counter"));
        public global::SpacetimeDB.Table<BusLocation, BusLocationCols, BusLocationIxCols> BusLocation() => new("bus_location", new BusLocationCols("bus_location"), new BusLocationIxCols("bus_location"));
        public global::SpacetimeDB.Table<BusStatusEvent, BusStatusEventCols, BusStatusEventIxCols> BusStatusEvent() => new("bus_status_event", new BusStatusEventCols("bus_status_event"), new BusStatusEventIxCols("bus_status_event"));
        public global::SpacetimeDB.Table<BusStop, BusStopCols, BusStopIxCols> BusStop() => new("bus_stop", new BusStopCols("bus_stop"), new BusStopIxCols("bus_stop"));
        public global::SpacetimeDB.Table<CashierDay, CashierDayCols, CashierDayIxCols> CashierDay() => new("cashier_day", new CashierDayCols("cashier_day"), new CashierDayIxCols("cashier_day"));
        public global::SpacetimeDB.Table<Client, ClientCols, ClientIxCols> Client() => new("client", new ClientCols("client"), new ClientIxCols("client"));
        public global::SpacetimeDB.Table<ConductorStatistics, ConductorStatisticsCols, ConductorStatisticsIxCols> ConductorStatistics() => new("conductor_statistics", new ConductorStatisticsCols("conductor_statistics"), new ConductorStatisticsIxCols("conductor_statistics"));
        public global::SpacetimeDB.Table<DiscountIdCounter, DiscountIdCounterCols, DiscountIdCounterIxCols> DiscountIdCounter() => new("discount_id_counter", new DiscountIdCounterCols("discount_id_counter"), new DiscountIdCounterIxCols("discount_id_counter"));
        public global::SpacetimeDB.Table<Discounts, DiscountsCols, DiscountsIxCols> Discounts() => new("discounts", new DiscountsCols("discounts"), new DiscountsIxCols("discounts"));
        public global::SpacetimeDB.Table<Employee, EmployeeCols, EmployeeIxCols> Employee() => new("employee", new EmployeeCols("employee"), new EmployeeIxCols("employee"));
        public global::SpacetimeDB.Table<EmployeeIdCounter, EmployeeIdCounterCols, EmployeeIdCounterIxCols> EmployeeIdCounter() => new("employee_id_counter", new EmployeeIdCounterCols("employee_id_counter"), new EmployeeIdCounterIxCols("employee_id_counter"));
        public global::SpacetimeDB.Table<EmployeeShift, EmployeeShiftCols, EmployeeShiftIxCols> EmployeeShift() => new("employee_shift", new EmployeeShiftCols("employee_shift"), new EmployeeShiftIxCols("employee_shift"));
        public global::SpacetimeDB.Table<FeatureFlagOverride, FeatureFlagOverrideCols, FeatureFlagOverrideIxCols> FeatureFlagOverride() => new("feature_flag_override", new FeatureFlagOverrideCols("feature_flag_override"), new FeatureFlagOverrideIxCols("feature_flag_override"));
        public global::SpacetimeDB.Table<FuelRecord, FuelRecordCols, FuelRecordIxCols> FuelRecord() => new("fuel_record", new FuelRecordCols("fuel_record"), new FuelRecordIxCols("fuel_record"));
        public global::SpacetimeDB.Table<Incident, IncidentCols, IncidentIxCols> Incident() => new("incident", new IncidentCols("incident"), new IncidentIxCols("incident"));
        public global::SpacetimeDB.Table<Job, JobCols, JobIxCols> Job() => new("job", new JobCols("job"), new JobIxCols("job"));
        public global::SpacetimeDB.Table<JobIdCounter, JobIdCounterCols, JobIdCounterIxCols> JobIdCounter() => new("job_id_counter", new JobIdCounterCols("job_id_counter"), new JobIdCounterIxCols("job_id_counter"));
        public global::SpacetimeDB.Table<LogIdCounter, LogIdCounterCols, LogIdCounterIxCols> LogIdCounter() => new("log_id_counter", new LogIdCounterCols("log_id_counter"), new LogIdCounterIxCols("log_id_counter"));
        public global::SpacetimeDB.Table<MagicLinkToken, MagicLinkTokenCols, MagicLinkTokenIxCols> MagicLinkToken() => new("magic_link_token", new MagicLinkTokenCols("magic_link_token"), new MagicLinkTokenIxCols("magic_link_token"));
        public global::SpacetimeDB.Table<Maintenance, MaintenanceCols, MaintenanceIxCols> Maintenance() => new("maintenance", new MaintenanceCols("maintenance"), new MaintenanceIxCols("maintenance"));
        public global::SpacetimeDB.Table<MaintenanceEvent, MaintenanceEventCols, MaintenanceEventIxCols> MaintenanceEvent() => new("maintenance_event", new MaintenanceEventCols("maintenance_event"), new MaintenanceEventIxCols("maintenance_event"));
        public global::SpacetimeDB.Table<MaintenanceIdCounter, MaintenanceIdCounterCols, MaintenanceIdCounterIxCols> MaintenanceIdCounter() => new("maintenance_id_counter", new MaintenanceIdCounterCols("maintenance_id_counter"), new MaintenanceIdCounterIxCols("maintenance_id_counter"));
        public global::SpacetimeDB.Table<OidcAuthorizationIdCounter, OidcAuthorizationIdCounterCols, OidcAuthorizationIdCounterIxCols> OidcAuthorizationIdCounter() => new("oidc_authorization_id_counter", new OidcAuthorizationIdCounterCols("oidc_authorization_id_counter"), new OidcAuthorizationIdCounterIxCols("oidc_authorization_id_counter"));
        public global::SpacetimeDB.Table<OidcScopeIdCounter, OidcScopeIdCounterCols, OidcScopeIdCounterIxCols> OidcScopeIdCounter() => new("oidc_scope_id_counter", new OidcScopeIdCounterCols("oidc_scope_id_counter"), new OidcScopeIdCounterIxCols("oidc_scope_id_counter"));
        public global::SpacetimeDB.Table<OidcTokenIdCounter, OidcTokenIdCounterCols, OidcTokenIdCounterIxCols> OidcTokenIdCounter() => new("oidc_token_id_counter", new OidcTokenIdCounterCols("oidc_token_id_counter"), new OidcTokenIdCounterIxCols("oidc_token_id_counter"));
        public global::SpacetimeDB.Table<OpenIdConnect, OpenIdConnectCols, OpenIdConnectIxCols> OpenIdConnect() => new("open_id_connect", new OpenIdConnectCols("open_id_connect"), new OpenIdConnectIxCols("open_id_connect"));
        public global::SpacetimeDB.Table<OpenIdConnectGrant, OpenIdConnectGrantCols, OpenIdConnectGrantIxCols> OpenIdConnectGrant() => new("open_id_connect_grant", new OpenIdConnectGrantCols("open_id_connect_grant"), new OpenIdConnectGrantIxCols("open_id_connect_grant"));
        public global::SpacetimeDB.Table<OpenIddictSpacetimeAuthorization, OpenIddictSpacetimeAuthorizationCols, OpenIddictSpacetimeAuthorizationIxCols> OpenIddictSpacetimeAuthorization() => new("open_iddict_spacetime_authorization", new OpenIddictSpacetimeAuthorizationCols("open_iddict_spacetime_authorization"), new OpenIddictSpacetimeAuthorizationIxCols("open_iddict_spacetime_authorization"));
        public global::SpacetimeDB.Table<OpenIddictSpacetimeScope, OpenIddictSpacetimeScopeCols, OpenIddictSpacetimeScopeIxCols> OpenIddictSpacetimeScope() => new("open_iddict_spacetime_scope", new OpenIddictSpacetimeScopeCols("open_iddict_spacetime_scope"), new OpenIddictSpacetimeScopeIxCols("open_iddict_spacetime_scope"));
        public global::SpacetimeDB.Table<OpenIddictSpacetimeToken, OpenIddictSpacetimeTokenCols, OpenIddictSpacetimeTokenIxCols> OpenIddictSpacetimeToken() => new("open_iddict_spacetime_token", new OpenIddictSpacetimeTokenCols("open_iddict_spacetime_token"), new OpenIddictSpacetimeTokenIxCols("open_iddict_spacetime_token"));
        public global::SpacetimeDB.Table<Passenger, PassengerCols, PassengerIxCols> Passenger() => new("passenger", new PassengerCols("passenger"), new PassengerIxCols("passenger"));
        public global::SpacetimeDB.Table<PassengerCount, PassengerCountCols, PassengerCountIxCols> PassengerCount() => new("passenger_count", new PassengerCountCols("passenger_count"), new PassengerCountIxCols("passenger_count"));
        public global::SpacetimeDB.Table<PassengerIdCounter, PassengerIdCounterCols, PassengerIdCounterIxCols> PassengerIdCounter() => new("passenger_id_counter", new PassengerIdCounterCols("passenger_id_counter"), new PassengerIdCounterIxCols("passenger_id_counter"));
        public global::SpacetimeDB.Table<Permission, PermissionCols, PermissionIxCols> Permission() => new("permission", new PermissionCols("permission"), new PermissionIxCols("permission"));
        public global::SpacetimeDB.Table<PermissionIdCounter, PermissionIdCounterCols, PermissionIdCounterIxCols> PermissionIdCounter() => new("permission_id_counter", new PermissionIdCounterCols("permission_id_counter"), new PermissionIdCounterIxCols("permission_id_counter"));
        public global::SpacetimeDB.Table<Person, PersonCols, PersonIxCols> Person() => new("person", new PersonCols("person"), new PersonIxCols("person"));
        public global::SpacetimeDB.Table<QrSession, QrSessionCols, QrSessionIxCols> QrSession() => new("qr_session", new QrSessionCols("qr_session"), new QrSessionIxCols("qr_session"));
        public global::SpacetimeDB.Table<Role, RoleCols, RoleIxCols> Role() => new("role", new RoleCols("role"), new RoleIxCols("role"));
        public global::SpacetimeDB.Table<RoleIdCounter, RoleIdCounterCols, RoleIdCounterIxCols> RoleIdCounter() => new("role_id_counter", new RoleIdCounterCols("role_id_counter"), new RoleIdCounterIxCols("role_id_counter"));
        public global::SpacetimeDB.Table<RolePermission, RolePermissionCols, RolePermissionIxCols> RolePermission() => new("role_permission", new RolePermissionCols("role_permission"), new RolePermissionIxCols("role_permission"));
        public global::SpacetimeDB.Table<RolePermissionIdCounter, RolePermissionIdCounterCols, RolePermissionIdCounterIxCols> RolePermissionIdCounter() => new("role_permission_id_counter", new RolePermissionIdCounterCols("role_permission_id_counter"), new RolePermissionIdCounterIxCols("role_permission_id_counter"));
        public global::SpacetimeDB.Table<Route, RouteCols, RouteIxCols> Route() => new("route", new RouteCols("route"), new RouteIxCols("route"));
        public global::SpacetimeDB.Table<RouteConductor, RouteConductorCols, RouteConductorIxCols> RouteConductor() => new("route_conductor", new RouteConductorCols("route_conductor"), new RouteConductorIxCols("route_conductor"));
        public global::SpacetimeDB.Table<RouteIdCounter, RouteIdCounterCols, RouteIdCounterIxCols> RouteIdCounter() => new("route_id_counter", new RouteIdCounterCols("route_id_counter"), new RouteIdCounterIxCols("route_id_counter"));
        public global::SpacetimeDB.Table<RouteSchedule, RouteScheduleCols, RouteScheduleIxCols> RouteSchedule() => new("route_schedule", new RouteScheduleCols("route_schedule"), new RouteScheduleIxCols("route_schedule"));
        public global::SpacetimeDB.Table<RouteScheduleEvent, RouteScheduleEventCols, RouteScheduleEventIxCols> RouteScheduleEvent() => new("route_schedule_event", new RouteScheduleEventCols("route_schedule_event"), new RouteScheduleEventIxCols("route_schedule_event"));
        public global::SpacetimeDB.Table<Sale, SaleCols, SaleIxCols> Sale() => new("sale", new SaleCols("sale"), new SaleIxCols("sale"));
        public global::SpacetimeDB.Table<SaleIdCounter, SaleIdCounterCols, SaleIdCounterIxCols> SaleIdCounter() => new("sale_id_counter", new SaleIdCounterCols("sale_id_counter"), new SaleIdCounterIxCols("sale_id_counter"));
        public global::SpacetimeDB.Table<ScheduleIdCounter, ScheduleIdCounterCols, ScheduleIdCounterIxCols> ScheduleIdCounter() => new("schedule_id_counter", new ScheduleIdCounterCols("schedule_id_counter"), new ScheduleIdCounterIxCols("schedule_id_counter"));
        public global::SpacetimeDB.Table<SeatConfiguration, SeatConfigurationCols, SeatConfigurationIxCols> SeatConfiguration() => new("seat_configuration", new SeatConfigurationCols("seat_configuration"), new SeatConfigurationIxCols("seat_configuration"));
        public global::SpacetimeDB.Table<SeatConfigurationIdCounter, SeatConfigurationIdCounterCols, SeatConfigurationIdCounterIxCols> SeatConfigurationIdCounter() => new("seat_configuration_id_counter", new SeatConfigurationIdCounterCols("seat_configuration_id_counter"), new SeatConfigurationIdCounterIxCols("seat_configuration_id_counter"));
        public global::SpacetimeDB.Table<Ticket, TicketCols, TicketIxCols> Ticket() => new("ticket", new TicketCols("ticket"), new TicketIxCols("ticket"));
        public global::SpacetimeDB.Table<TicketIdCounter, TicketIdCounterCols, TicketIdCounterIxCols> TicketIdCounter() => new("ticket_id_counter", new TicketIdCounterCols("ticket_id_counter"), new TicketIdCounterIxCols("ticket_id_counter"));
        public global::SpacetimeDB.Table<TicketSaleEvent, TicketSaleEventCols, TicketSaleEventIxCols> TicketSaleEvent() => new("ticket_sale_event", new TicketSaleEventCols("ticket_sale_event"), new TicketSaleEventIxCols("ticket_sale_event"));
        public global::SpacetimeDB.Table<TotpSecret, TotpSecretCols, TotpSecretIxCols> TotpSecret() => new("totp_secret", new TotpSecretCols("totp_secret"), new TotpSecretIxCols("totp_secret"));
        public global::SpacetimeDB.Table<TotpSecretIdCounter, TotpSecretIdCounterCols, TotpSecretIdCounterIxCols> TotpSecretIdCounter() => new("totp_secret_id_counter", new TotpSecretIdCounterCols("totp_secret_id_counter"), new TotpSecretIdCounterIxCols("totp_secret_id_counter"));
        public global::SpacetimeDB.Table<TwoFactorToken, TwoFactorTokenCols, TwoFactorTokenIxCols> TwoFactorToken() => new("two_factor_token", new TwoFactorTokenCols("two_factor_token"), new TwoFactorTokenIxCols("two_factor_token"));
        public global::SpacetimeDB.Table<TwoFactorTokenIdCounter, TwoFactorTokenIdCounterCols, TwoFactorTokenIdCounterIxCols> TwoFactorTokenIdCounter() => new("two_factor_token_id_counter", new TwoFactorTokenIdCounterCols("two_factor_token_id_counter"), new TwoFactorTokenIdCounterIxCols("two_factor_token_id_counter"));
        public global::SpacetimeDB.Table<UserIdCounter, UserIdCounterCols, UserIdCounterIxCols> UserIdCounter() => new("user_id_counter", new UserIdCounterCols("user_id_counter"), new UserIdCounterIxCols("user_id_counter"));
        public global::SpacetimeDB.Table<UserProfile, UserProfileCols, UserProfileIxCols> UserProfile() => new("user_profile", new UserProfileCols("user_profile"), new UserProfileIxCols("user_profile"));
        public global::SpacetimeDB.Table<UserRole, UserRoleCols, UserRoleIxCols> UserRole() => new("user_role", new UserRoleCols("user_role"), new UserRoleIxCols("user_role"));
        public global::SpacetimeDB.Table<UserRoleIdCounter, UserRoleIdCounterCols, UserRoleIdCounterIxCols> UserRoleIdCounter() => new("user_role_id_counter", new UserRoleIdCounterCols("user_role_id_counter"), new UserRoleIdCounterIxCols("user_role_id_counter"));
        public global::SpacetimeDB.Table<UserSettings, UserSettingsCols, UserSettingsIxCols> UserSettings() => new("user_settings", new UserSettingsCols("user_settings"), new UserSettingsIxCols("user_settings"));
        public global::SpacetimeDB.Table<WebAuthnChallenge, WebAuthnChallengeCols, WebAuthnChallengeIxCols> WebAuthnChallenge() => new("web_authn_challenge", new WebAuthnChallengeCols("web_authn_challenge"), new WebAuthnChallengeIxCols("web_authn_challenge"));
        public global::SpacetimeDB.Table<WebAuthnChallengeIdCounter, WebAuthnChallengeIdCounterCols, WebAuthnChallengeIdCounterIxCols> WebAuthnChallengeIdCounter() => new("web_authn_challenge_id_counter", new WebAuthnChallengeIdCounterCols("web_authn_challenge_id_counter"), new WebAuthnChallengeIdCounterIxCols("web_authn_challenge_id_counter"));
        public global::SpacetimeDB.Table<WebAuthnCredential, WebAuthnCredentialCols, WebAuthnCredentialIxCols> WebAuthnCredential() => new("web_authn_credential", new WebAuthnCredentialCols("web_authn_credential"), new WebAuthnCredentialIxCols("web_authn_credential"));
        public global::SpacetimeDB.Table<WebAuthnCredentialIdCounter, WebAuthnCredentialIdCounterCols, WebAuthnCredentialIdCounterIxCols> WebAuthnCredentialIdCounter() => new("web_authn_credential_id_counter", new WebAuthnCredentialIdCounterCols("web_authn_credential_id_counter"), new WebAuthnCredentialIdCounterIxCols("web_authn_credential_id_counter"));
    }

    public sealed class TypedSubscriptionBuilder
    {
        private readonly IDbConnection conn;
        private Action<SubscriptionEventContext>? Applied;
        private Action<ErrorContext, Exception>? Error;
        private readonly List<string> querySqls = new();

        internal TypedSubscriptionBuilder(IDbConnection conn, Action<SubscriptionEventContext>? applied, Action<ErrorContext, Exception>? error)
        {
            this.conn = conn;
            Applied = applied;
            Error = error;
        }

        public TypedSubscriptionBuilder OnApplied(Action<SubscriptionEventContext> callback)
        {
            Applied += callback;
            return this;
        }

        public TypedSubscriptionBuilder OnError(Action<ErrorContext, Exception> callback)
        {
            Error += callback;
            return this;
        }

        public TypedSubscriptionBuilder AddQuery<TRow>(Func<QueryBuilder, global::SpacetimeDB.IQuery<TRow>> build)
        {
            var qb = new QueryBuilder();
            querySqls.Add(build(qb).ToSql());
            return this;
        }

        public SubscriptionHandle Subscribe() => new(conn, Applied, Error, querySqls.ToArray());
    }

    public abstract partial class Reducer
    {
        private Reducer() { }
    }

    public abstract partial class Procedure
    {
        private Procedure() { }
    }

    public sealed class DbConnection : DbConnectionBase<DbConnection, RemoteTables, Reducer>
    {
        public override RemoteTables Db { get; }
        public readonly RemoteReducers Reducers;
        public readonly RemoteProcedures Procedures;

        public DbConnection()
        {
            Db = new(this);
            Reducers = new(this);
            Procedures = new(this);
        }

        protected override IEventContext ToEventContext(Event<Reducer> Event) =>
        new EventContext(this, Event);

        protected override IReducerEventContext ToReducerEventContext(ReducerEvent<Reducer> reducerEvent) =>
        new ReducerEventContext(this, reducerEvent);

        protected override ISubscriptionEventContext MakeSubscriptionEventContext() =>
        new SubscriptionEventContext(this);

        protected override IErrorContext ToErrorContext(Exception exception) =>
        new ErrorContext(this, exception);

        protected override IProcedureEventContext ToProcedureEventContext(ProcedureEvent procedureEvent) =>
        new ProcedureEventContext(this, procedureEvent);

        protected override bool Dispatch(IReducerEventContext context, Reducer reducer)
        {
            var eventContext = (ReducerEventContext)context;
            return reducer switch {
                Reducer.ActivateBus args => Reducers.InvokeActivateBus(eventContext, args),
                Reducer.ActivateRoute args => Reducers.InvokeActivateRoute(eventContext, args),
                Reducer.ActivateSchedule args => Reducers.InvokeActivateSchedule(eventContext, args),
                Reducer.ActivateUser args => Reducers.InvokeActivateUser(eventContext, args),
                Reducer.Add args => Reducers.InvokeAdd(eventContext, args),
                Reducer.AddNewPermission args => Reducers.InvokeAddNewPermission(eventContext, args),
                Reducer.ApproveQrSession args => Reducers.InvokeApproveQrSession(eventContext, args),
                Reducer.AssignRole args => Reducers.InvokeAssignRole(eventContext, args),
                Reducer.AuthenticateUser args => Reducers.InvokeAuthenticateUser(eventContext, args),
                Reducer.CancelTicket args => Reducers.InvokeCancelTicket(eventContext, args),
                Reducer.ChangePassword args => Reducers.InvokeChangePassword(eventContext, args),
                Reducer.ClaimUserAccount args => Reducers.InvokeClaimUserAccount(eventContext, args),
                Reducer.ClearFeatureFlagOverrides args => Reducers.InvokeClearFeatureFlagOverrides(eventContext, args),
                Reducer.ClientConnected args => Reducers.InvokeClientConnected(eventContext, args),
                Reducer.CreateBus args => Reducers.InvokeCreateBus(eventContext, args),
                Reducer.CreateEmployee args => Reducers.InvokeCreateEmployee(eventContext, args),
                Reducer.CreateJob args => Reducers.InvokeCreateJob(eventContext, args),
                Reducer.CreateMagicLinkToken args => Reducers.InvokeCreateMagicLinkToken(eventContext, args),
                Reducer.CreateMaintenance args => Reducers.InvokeCreateMaintenance(eventContext, args),
                Reducer.CreateOidcAuthorization args => Reducers.InvokeCreateOidcAuthorization(eventContext, args),
                Reducer.CreateOidcScope args => Reducers.InvokeCreateOidcScope(eventContext, args),
                Reducer.CreateOidcToken args => Reducers.InvokeCreateOidcToken(eventContext, args),
                Reducer.CreateOpenIdGrant args => Reducers.InvokeCreateOpenIdGrant(eventContext, args),
                Reducer.CreatePassenger args => Reducers.InvokeCreatePassenger(eventContext, args),
                Reducer.CreateQrSession args => Reducers.InvokeCreateQrSession(eventContext, args),
                Reducer.CreateRoleReducer args => Reducers.InvokeCreateRoleReducer(eventContext, args),
                Reducer.CreateRoute args => Reducers.InvokeCreateRoute(eventContext, args),
                Reducer.CreateRouteSchedule args => Reducers.InvokeCreateRouteSchedule(eventContext, args),
                Reducer.CreateSale args => Reducers.InvokeCreateSale(eventContext, args),
                Reducer.CreateTicket args => Reducers.InvokeCreateTicket(eventContext, args),
                Reducer.CreateTwoFactorToken args => Reducers.InvokeCreateTwoFactorToken(eventContext, args),
                Reducer.CreateUserSettings args => Reducers.InvokeCreateUserSettings(eventContext, args),
                Reducer.DeactivateBus args => Reducers.InvokeDeactivateBus(eventContext, args),
                Reducer.DeactivateRoute args => Reducers.InvokeDeactivateRoute(eventContext, args),
                Reducer.DeactivateSchedule args => Reducers.InvokeDeactivateSchedule(eventContext, args),
                Reducer.DeactivateTotpSecret args => Reducers.InvokeDeactivateTotpSecret(eventContext, args),
                Reducer.DeactivateUser args => Reducers.InvokeDeactivateUser(eventContext, args),
                Reducer.DeactivateWebAuthnCredential args => Reducers.InvokeDeactivateWebAuthnCredential(eventContext, args),
                Reducer.DebugVerifyPassword args => Reducers.InvokeDebugVerifyPassword(eventContext, args),
                Reducer.DeleteBus args => Reducers.InvokeDeleteBus(eventContext, args),
                Reducer.DeleteEmployee args => Reducers.InvokeDeleteEmployee(eventContext, args),
                Reducer.DeleteFeatureFlagOverride args => Reducers.InvokeDeleteFeatureFlagOverride(eventContext, args),
                Reducer.DeleteJob args => Reducers.InvokeDeleteJob(eventContext, args),
                Reducer.DeleteMaintenance args => Reducers.InvokeDeleteMaintenance(eventContext, args),
                Reducer.DeleteOidcAuthorization args => Reducers.InvokeDeleteOidcAuthorization(eventContext, args),
                Reducer.DeleteOidcScope args => Reducers.InvokeDeleteOidcScope(eventContext, args),
                Reducer.DeleteOidcToken args => Reducers.InvokeDeleteOidcToken(eventContext, args),
                Reducer.DeletePassenger args => Reducers.InvokeDeletePassenger(eventContext, args),
                Reducer.DeletePermission args => Reducers.InvokeDeletePermission(eventContext, args),
                Reducer.DeleteQrSession args => Reducers.InvokeDeleteQrSession(eventContext, args),
                Reducer.DeleteRole args => Reducers.InvokeDeleteRole(eventContext, args),
                Reducer.DeleteRoleReducer args => Reducers.InvokeDeleteRoleReducer(eventContext, args),
                Reducer.DeleteRoute args => Reducers.InvokeDeleteRoute(eventContext, args),
                Reducer.DeleteRouteSchedule args => Reducers.InvokeDeleteRouteSchedule(eventContext, args),
                Reducer.DeleteSale args => Reducers.InvokeDeleteSale(eventContext, args),
                Reducer.DeleteTicket args => Reducers.InvokeDeleteTicket(eventContext, args),
                Reducer.DeleteTwoFactorToken args => Reducers.InvokeDeleteTwoFactorToken(eventContext, args),
                Reducer.DeleteUser args => Reducers.InvokeDeleteUser(eventContext, args),
                Reducer.DeleteWebAuthnChallenge args => Reducers.InvokeDeleteWebAuthnChallenge(eventContext, args),
                Reducer.DisableTotp args => Reducers.InvokeDisableTotp(eventContext, args),
                Reducer.DisableWebAuthn args => Reducers.InvokeDisableWebAuthn(eventContext, args),
                Reducer.EnableTotp args => Reducers.InvokeEnableTotp(eventContext, args),
                Reducer.EnableWebAuthn args => Reducers.InvokeEnableWebAuthn(eventContext, args),
                Reducer.GenerateTotpSecret args => Reducers.InvokeGenerateTotpSecret(eventContext, args),
                Reducer.GetBusMaintenanceHistory args => Reducers.InvokeGetBusMaintenanceHistory(eventContext, args),
                Reducer.GrantPermissionToRole args => Reducers.InvokeGrantPermissionToRole(eventContext, args),
                Reducer.LogAdminAction args => Reducers.InvokeLogAdminAction(eventContext, args),
                Reducer.PruneOidcAuthorizations args => Reducers.InvokePruneOidcAuthorizations(eventContext, args),
                Reducer.PruneOidcTokens args => Reducers.InvokePruneOidcTokens(eventContext, args),
                Reducer.RegisterOpenIdClient args => Reducers.InvokeRegisterOpenIdClient(eventContext, args),
                Reducer.RegisterUser args => Reducers.InvokeRegisterUser(eventContext, args),
                Reducer.RegisterWebAuthnCredential args => Reducers.InvokeRegisterWebAuthnCredential(eventContext, args),
                Reducer.RemoveRole args => Reducers.InvokeRemoveRole(eventContext, args),
                Reducer.RevokeOpenIdClient args => Reducers.InvokeRevokeOpenIdClient(eventContext, args),
                Reducer.RevokeOpenIdGrant args => Reducers.InvokeRevokeOpenIdGrant(eventContext, args),
                Reducer.RevokePermissionFromRole args => Reducers.InvokeRevokePermissionFromRole(eventContext, args),
                Reducer.SayHello args => Reducers.InvokeSayHello(eventContext, args),
                Reducer.StoreTotpSecret args => Reducers.InvokeStoreTotpSecret(eventContext, args),
                Reducer.StoreWebAuthnChallenge args => Reducers.InvokeStoreWebAuthnChallenge(eventContext, args),
                Reducer.UpdateBus args => Reducers.InvokeUpdateBus(eventContext, args),
                Reducer.UpdateEmployee args => Reducers.InvokeUpdateEmployee(eventContext, args),
                Reducer.UpdateFeatureFlag args => Reducers.InvokeUpdateFeatureFlag(eventContext, args),
                Reducer.UpdateJob args => Reducers.InvokeUpdateJob(eventContext, args),
                Reducer.UpdateMaintenance args => Reducers.InvokeUpdateMaintenance(eventContext, args),
                Reducer.UpdateOidcAuthorization args => Reducers.InvokeUpdateOidcAuthorization(eventContext, args),
                Reducer.UpdateOidcScope args => Reducers.InvokeUpdateOidcScope(eventContext, args),
                Reducer.UpdateOidcToken args => Reducers.InvokeUpdateOidcToken(eventContext, args),
                Reducer.UpdateOpenIdClient args => Reducers.InvokeUpdateOpenIdClient(eventContext, args),
                Reducer.UpdatePassenger args => Reducers.InvokeUpdatePassenger(eventContext, args),
                Reducer.UpdatePermission args => Reducers.InvokeUpdatePermission(eventContext, args),
                Reducer.UpdateRole args => Reducers.InvokeUpdateRole(eventContext, args),
                Reducer.UpdateRoleReducer args => Reducers.InvokeUpdateRoleReducer(eventContext, args),
                Reducer.UpdateRoute args => Reducers.InvokeUpdateRoute(eventContext, args),
                Reducer.UpdateRouteSchedule args => Reducers.InvokeUpdateRouteSchedule(eventContext, args),
                Reducer.UpdateSale args => Reducers.InvokeUpdateSale(eventContext, args),
                Reducer.UpdateTicket args => Reducers.InvokeUpdateTicket(eventContext, args),
                Reducer.UpdateTwoFactorToken args => Reducers.InvokeUpdateTwoFactorToken(eventContext, args),
                Reducer.UpdateUser args => Reducers.InvokeUpdateUser(eventContext, args),
                Reducer.UpdateWebAuthnCounter args => Reducers.InvokeUpdateWebAuthnCounter(eventContext, args),
                Reducer.UpdateWebAuthnCredentialCounter args => Reducers.InvokeUpdateWebAuthnCredentialCounter(eventContext, args),
                Reducer.UseMagicLinkToken args => Reducers.InvokeUseMagicLinkToken(eventContext, args),
                Reducer.UseQrSession args => Reducers.InvokeUseQrSession(eventContext, args),
                Reducer.ValidateQrCode args => Reducers.InvokeValidateQrCode(eventContext, args),
                _ => throw new ArgumentOutOfRangeException("Reducer", $"Unknown reducer {reducer}")
            };
        }

        public SubscriptionBuilder SubscriptionBuilder() => new(this);
        public event Action<ReducerEventContext, Exception> OnUnhandledReducerError
        {
            add => Reducers.InternalOnUnhandledReducerError += value;
            remove => Reducers.InternalOnUnhandledReducerError -= value;
        }
    }
}
