// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ActivateUserHandler(ReducerEventContext ctx, SpacetimeDB.Identity userId, SpacetimeDB.Identity? actingUser);
        public event ActivateUserHandler? OnActivateUser;

        public void ActivateUser(SpacetimeDB.Identity userId, SpacetimeDB.Identity? actingUser)
        {
            conn.InternalCallReducer(new Reducer.ActivateUser(userId, actingUser));
        }

        public bool InvokeActivateUser(ReducerEventContext ctx, Reducer.ActivateUser args)
        {
            if (OnActivateUser == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnActivateUser(
                ctx,
                args.UserId,
                args.ActingUser
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ActivateUser : Reducer, IReducerArgs
        {
            [DataMember(Name = "user_id")]
            public SpacetimeDB.Identity UserId;
            [DataMember(Name = "acting_user")]
            public SpacetimeDB.Identity? ActingUser;

            public ActivateUser(
                SpacetimeDB.Identity UserId,
                SpacetimeDB.Identity? ActingUser
            )
            {
                this.UserId = UserId;
                this.ActingUser = ActingUser;
            }

            public ActivateUser()
            {
            }

            string IReducerArgs.ReducerName => "activate_user";
        }
    }
}
