// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ActivateScheduleHandler(ReducerEventContext ctx, uint scheduleId, SpacetimeDB.Identity? actingUser);
        public event ActivateScheduleHandler? OnActivateSchedule;

        public void ActivateSchedule(uint scheduleId, SpacetimeDB.Identity? actingUser)
        {
            conn.InternalCallReducer(new Reducer.ActivateSchedule(scheduleId, actingUser), this.SetCallReducerFlags.ActivateScheduleFlags);
        }

        public bool InvokeActivateSchedule(ReducerEventContext ctx, Reducer.ActivateSchedule args)
        {
            if (OnActivateSchedule == null) return false;
            OnActivateSchedule(
                ctx,
                args.ScheduleId,
                args.ActingUser
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ActivateSchedule : Reducer, IReducerArgs
        {
            [DataMember(Name = "scheduleId")]
            public uint ScheduleId;
            [DataMember(Name = "actingUser")]
            public SpacetimeDB.Identity? ActingUser;

            public ActivateSchedule(
                uint ScheduleId,
                SpacetimeDB.Identity? ActingUser
            )
            {
                this.ScheduleId = ScheduleId;
                this.ActingUser = ActingUser;
            }

            public ActivateSchedule()
            {
            }

            string IReducerArgs.ReducerName => "ActivateSchedule";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ActivateScheduleFlags;
        public void ActivateSchedule(CallReducerFlags flags) => ActivateScheduleFlags = flags;
    }
}
