// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ActivateBusHandler(ReducerEventContext ctx, uint busId, SpacetimeDB.Identity? actingUser);
        public event ActivateBusHandler? OnActivateBus;

        public void ActivateBus(uint busId, SpacetimeDB.Identity? actingUser)
        {
            conn.InternalCallReducer(new Reducer.ActivateBus(busId, actingUser), this.SetCallReducerFlags.ActivateBusFlags);
        }

        public bool InvokeActivateBus(ReducerEventContext ctx, Reducer.ActivateBus args)
        {
            if (OnActivateBus == null) return false;
            OnActivateBus(
                ctx,
                args.BusId,
                args.ActingUser
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ActivateBus : Reducer, IReducerArgs
        {
            [DataMember(Name = "busId")]
            public uint BusId;
            [DataMember(Name = "actingUser")]
            public SpacetimeDB.Identity? ActingUser;

            public ActivateBus(
                uint BusId,
                SpacetimeDB.Identity? ActingUser
            )
            {
                this.BusId = BusId;
                this.ActingUser = ActingUser;
            }

            public ActivateBus()
            {
            }

            string IReducerArgs.ReducerName => "ActivateBus";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ActivateBusFlags;
        public void ActivateBus(CallReducerFlags flags) => ActivateBusFlags = flags;
    }
}
