// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddNewPermissionHandler(ReducerEventContext ctx, string name, string description, string category, SpacetimeDB.Identity? actingUserId);
        public event AddNewPermissionHandler? OnAddNewPermission;

        public void AddNewPermission(string name, string description, string category, SpacetimeDB.Identity? actingUserId)
        {
<<<<<<< HEAD
            conn.InternalCallReducer(new Reducer.AddNewPermission(name, description, category, actingUserId), this.SetCallReducerFlags.AddNewPermissionFlags);
=======
            conn.InternalCallReducer(new Reducer.AddNewPermission(name, description, category, actingUserId));
>>>>>>> maintofix
        }

        public bool InvokeAddNewPermission(ReducerEventContext ctx, Reducer.AddNewPermission args)
        {
<<<<<<< HEAD
            if (OnAddNewPermission == null) return false;
=======
            if (OnAddNewPermission == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
>>>>>>> maintofix
            OnAddNewPermission(
                ctx,
                args.Name,
                args.Description,
                args.Category,
                args.ActingUserId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddNewPermission : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "description")]
            public string Description;
            [DataMember(Name = "category")]
            public string Category;
<<<<<<< HEAD
            [DataMember(Name = "actingUserId")]
=======
            [DataMember(Name = "acting_user_id")]
>>>>>>> maintofix
            public SpacetimeDB.Identity? ActingUserId;

            public AddNewPermission(
                string Name,
                string Description,
                string Category,
                SpacetimeDB.Identity? ActingUserId
            )
            {
                this.Name = Name;
                this.Description = Description;
                this.Category = Category;
                this.ActingUserId = ActingUserId;
            }

            public AddNewPermission()
            {
                this.Name = "";
                this.Description = "";
                this.Category = "";
            }

<<<<<<< HEAD
            string IReducerArgs.ReducerName => "AddNewPermission";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddNewPermissionFlags;
        public void AddNewPermission(CallReducerFlags flags) => AddNewPermissionFlags = flags;
    }
=======
            string IReducerArgs.ReducerName => "add_new_permission";
        }
    }
>>>>>>> maintofix
}
