// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AssignRoleHandler(ReducerEventContext ctx, SpacetimeDB.Identity userId, uint roleId, SpacetimeDB.Identity? actingUserId);
        public event AssignRoleHandler? OnAssignRole;

        public void AssignRole(SpacetimeDB.Identity userId, uint roleId, SpacetimeDB.Identity? actingUserId)
        {
            conn.InternalCallReducer(new Reducer.AssignRole(userId, roleId, actingUserId));
        }

        public bool InvokeAssignRole(ReducerEventContext ctx, Reducer.AssignRole args)
        {
            if (OnAssignRole == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAssignRole(
                ctx,
                args.UserId,
                args.RoleId,
                args.ActingUserId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AssignRole : Reducer, IReducerArgs
        {
            [DataMember(Name = "user_id")]
            public SpacetimeDB.Identity UserId;
            [DataMember(Name = "role_id")]
            public uint RoleId;
            [DataMember(Name = "acting_user_id")]
            public SpacetimeDB.Identity? ActingUserId;

            public AssignRole(
                SpacetimeDB.Identity UserId,
                uint RoleId,
                SpacetimeDB.Identity? ActingUserId
            )
            {
                this.UserId = UserId;
                this.RoleId = RoleId;
                this.ActingUserId = ActingUserId;
            }

            public AssignRole()
            {
            }

            string IReducerArgs.ReducerName => "assign_role";
        }
    }
}
