// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AuthenticateUserHandler(ReducerEventContext ctx, string login, string password);
        public event AuthenticateUserHandler? OnAuthenticateUser;

        public void AuthenticateUser(string login, string password)
        {
            conn.InternalCallReducer(new Reducer.AuthenticateUser(login, password), this.SetCallReducerFlags.AuthenticateUserFlags);
        }

        public bool InvokeAuthenticateUser(ReducerEventContext ctx, Reducer.AuthenticateUser args)
        {
            if (OnAuthenticateUser == null) return false;
            OnAuthenticateUser(
                ctx,
                args.Login,
                args.Password
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AuthenticateUser : Reducer, IReducerArgs
        {
            [DataMember(Name = "login")]
            public string Login;
            [DataMember(Name = "password")]
            public string Password;

            public AuthenticateUser(
                string Login,
                string Password
            )
            {
                this.Login = Login;
                this.Password = Password;
            }

            public AuthenticateUser()
            {
                this.Login = "";
                this.Password = "";
            }

            string IReducerArgs.ReducerName => "AuthenticateUser";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AuthenticateUserFlags;
        public void AuthenticateUser(CallReducerFlags flags) => AuthenticateUserFlags = flags;
    }
}
