// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ChangePasswordHandler(ReducerEventContext ctx, SpacetimeDB.Identity userId, string currentPassword, string newPassword);
        public event ChangePasswordHandler? OnChangePassword;

        public void ChangePassword(SpacetimeDB.Identity userId, string currentPassword, string newPassword)
        {
            conn.InternalCallReducer(new Reducer.ChangePassword(userId, currentPassword, newPassword), this.SetCallReducerFlags.ChangePasswordFlags);
        }

        public bool InvokeChangePassword(ReducerEventContext ctx, Reducer.ChangePassword args)
        {
            if (OnChangePassword == null) return false;
            OnChangePassword(
                ctx,
                args.UserId,
                args.CurrentPassword,
                args.NewPassword
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ChangePassword : Reducer, IReducerArgs
        {
            [DataMember(Name = "userId")]
            public SpacetimeDB.Identity UserId;
            [DataMember(Name = "currentPassword")]
            public string CurrentPassword;
            [DataMember(Name = "newPassword")]
            public string NewPassword;

            public ChangePassword(
                SpacetimeDB.Identity UserId,
                string CurrentPassword,
                string NewPassword
            )
            {
                this.UserId = UserId;
                this.CurrentPassword = CurrentPassword;
                this.NewPassword = NewPassword;
            }

            public ChangePassword()
            {
                this.CurrentPassword = "";
                this.NewPassword = "";
            }

            string IReducerArgs.ReducerName => "ChangePassword";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ChangePasswordFlags;
        public void ChangePassword(CallReducerFlags flags) => ChangePasswordFlags = flags;
    }
}
