// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ChangePasswordHandler(ReducerEventContext ctx, SpacetimeDB.Identity userId, string currentPassword, string newPassword, SpacetimeDB.Identity? actingUser);
        public event ChangePasswordHandler? OnChangePassword;

        public void ChangePassword(SpacetimeDB.Identity userId, string currentPassword, string newPassword, SpacetimeDB.Identity? actingUser)
        {
            conn.InternalCallReducer(new Reducer.ChangePassword(userId, currentPassword, newPassword, actingUser));
        }

        public bool InvokeChangePassword(ReducerEventContext ctx, Reducer.ChangePassword args)
        {
            if (OnChangePassword == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnChangePassword(
                ctx,
                args.UserId,
                args.CurrentPassword,
                args.NewPassword,
                args.ActingUser
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ChangePassword : Reducer, IReducerArgs
        {
            [DataMember(Name = "user_id")]
            public SpacetimeDB.Identity UserId;
            [DataMember(Name = "current_password")]
            public string CurrentPassword;
            [DataMember(Name = "new_password")]
            public string NewPassword;
            [DataMember(Name = "acting_user")]
            public SpacetimeDB.Identity? ActingUser;

            public ChangePassword(
                SpacetimeDB.Identity UserId,
                string CurrentPassword,
                string NewPassword,
                SpacetimeDB.Identity? ActingUser
            )
            {
                this.UserId = UserId;
                this.CurrentPassword = CurrentPassword;
                this.NewPassword = NewPassword;
                this.ActingUser = ActingUser;
            }

            public ChangePassword()
            {
                this.CurrentPassword = "";
                this.NewPassword = "";
            }

            string IReducerArgs.ReducerName => "change_password";
        }
    }
}
