// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateSaleHandler(ReducerEventContext ctx, uint ticketId, string buyerName, string buyerPhone, string? saleLocation, string? saleNotes);
        public event CreateSaleHandler? OnCreateSale;

        public void CreateSale(uint ticketId, string buyerName, string buyerPhone, string? saleLocation, string? saleNotes)
        {
<<<<<<< HEAD
            conn.InternalCallReducer(new Reducer.CreateSale(ticketId, buyerName, buyerPhone, saleLocation, saleNotes), this.SetCallReducerFlags.CreateSaleFlags);
=======
            conn.InternalCallReducer(new Reducer.CreateSale(ticketId, buyerName, buyerPhone, saleLocation, saleNotes));
>>>>>>> maintofix
        }

        public bool InvokeCreateSale(ReducerEventContext ctx, Reducer.CreateSale args)
        {
<<<<<<< HEAD
            if (OnCreateSale == null) return false;
=======
            if (OnCreateSale == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
>>>>>>> maintofix
            OnCreateSale(
                ctx,
                args.TicketId,
                args.BuyerName,
                args.BuyerPhone,
                args.SaleLocation,
                args.SaleNotes
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateSale : Reducer, IReducerArgs
        {
<<<<<<< HEAD
            [DataMember(Name = "ticketId")]
            public uint TicketId;
            [DataMember(Name = "buyerName")]
            public string BuyerName;
            [DataMember(Name = "buyerPhone")]
            public string BuyerPhone;
            [DataMember(Name = "saleLocation")]
            public string? SaleLocation;
            [DataMember(Name = "saleNotes")]
=======
            [DataMember(Name = "ticket_id")]
            public uint TicketId;
            [DataMember(Name = "buyer_name")]
            public string BuyerName;
            [DataMember(Name = "buyer_phone")]
            public string BuyerPhone;
            [DataMember(Name = "sale_location")]
            public string? SaleLocation;
            [DataMember(Name = "sale_notes")]
>>>>>>> maintofix
            public string? SaleNotes;

            public CreateSale(
                uint TicketId,
                string BuyerName,
                string BuyerPhone,
                string? SaleLocation,
                string? SaleNotes
            )
            {
                this.TicketId = TicketId;
                this.BuyerName = BuyerName;
                this.BuyerPhone = BuyerPhone;
                this.SaleLocation = SaleLocation;
                this.SaleNotes = SaleNotes;
            }

            public CreateSale()
            {
                this.BuyerName = "";
                this.BuyerPhone = "";
            }

<<<<<<< HEAD
            string IReducerArgs.ReducerName => "CreateSale";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreateSaleFlags;
        public void CreateSale(CallReducerFlags flags) => CreateSaleFlags = flags;
    }
=======
            string IReducerArgs.ReducerName => "create_sale";
        }
    }
>>>>>>> maintofix
}
