// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateOidcScopeHandler(ReducerEventContext ctx, string oidcScopeId, string name, string? description, string? descriptionsJson, string? displayName, string? displayNamesJson, string? propertiesJson, string? resourcesJson);
        public event CreateOidcScopeHandler? OnCreateOidcScope;

        public void CreateOidcScope(string oidcScopeId, string name, string? description, string? descriptionsJson, string? displayName, string? displayNamesJson, string? propertiesJson, string? resourcesJson)
        {
            conn.InternalCallReducer(new Reducer.CreateOidcScope(oidcScopeId, name, description, descriptionsJson, displayName, displayNamesJson, propertiesJson, resourcesJson), this.SetCallReducerFlags.CreateOidcScopeFlags);
        }

        public bool InvokeCreateOidcScope(ReducerEventContext ctx, Reducer.CreateOidcScope args)
        {
            if (OnCreateOidcScope == null) return false;
            OnCreateOidcScope(
                ctx,
                args.OidcScopeId,
                args.Name,
                args.Description,
                args.DescriptionsJson,
                args.DisplayName,
                args.DisplayNamesJson,
                args.PropertiesJson,
                args.ResourcesJson
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateOidcScope : Reducer, IReducerArgs
        {
            [DataMember(Name = "oidcScopeId")]
            public string OidcScopeId;
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "description")]
            public string? Description;
            [DataMember(Name = "descriptionsJson")]
            public string? DescriptionsJson;
            [DataMember(Name = "displayName")]
            public string? DisplayName;
            [DataMember(Name = "displayNamesJson")]
            public string? DisplayNamesJson;
            [DataMember(Name = "propertiesJson")]
            public string? PropertiesJson;
            [DataMember(Name = "resourcesJson")]
            public string? ResourcesJson;

            public CreateOidcScope(
                string OidcScopeId,
                string Name,
                string? Description,
                string? DescriptionsJson,
                string? DisplayName,
                string? DisplayNamesJson,
                string? PropertiesJson,
                string? ResourcesJson
            )
            {
                this.OidcScopeId = OidcScopeId;
                this.Name = Name;
                this.Description = Description;
                this.DescriptionsJson = DescriptionsJson;
                this.DisplayName = DisplayName;
                this.DisplayNamesJson = DisplayNamesJson;
                this.PropertiesJson = PropertiesJson;
                this.ResourcesJson = ResourcesJson;
            }

            public CreateOidcScope()
            {
                this.OidcScopeId = "";
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "CreateOidcScope";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreateOidcScopeFlags;
        public void CreateOidcScope(CallReducerFlags flags) => CreateOidcScopeFlags = flags;
    }
}
