// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateBusHandler(ReducerEventContext ctx, string model, string? registrationNumber, SpacetimeDB.Identity? actingUser);
        public event CreateBusHandler? OnCreateBus;

        public void CreateBus(string model, string? registrationNumber, SpacetimeDB.Identity? actingUser)
        {
<<<<<<< HEAD
            conn.InternalCallReducer(new Reducer.CreateBus(model, registrationNumber, actingUser), this.SetCallReducerFlags.CreateBusFlags);
=======
            conn.InternalCallReducer(new Reducer.CreateBus(model, registrationNumber, actingUser));
>>>>>>> maintofix
        }

        public bool InvokeCreateBus(ReducerEventContext ctx, Reducer.CreateBus args)
        {
<<<<<<< HEAD
            if (OnCreateBus == null) return false;
=======
            if (OnCreateBus == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
>>>>>>> maintofix
            OnCreateBus(
                ctx,
                args.Model,
                args.RegistrationNumber,
                args.ActingUser
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateBus : Reducer, IReducerArgs
        {
            [DataMember(Name = "model")]
            public string Model;
<<<<<<< HEAD
            [DataMember(Name = "registrationNumber")]
            public string? RegistrationNumber;
            [DataMember(Name = "actingUser")]
=======
            [DataMember(Name = "registration_number")]
            public string? RegistrationNumber;
            [DataMember(Name = "acting_user")]
>>>>>>> maintofix
            public SpacetimeDB.Identity? ActingUser;

            public CreateBus(
                string Model,
                string? RegistrationNumber,
                SpacetimeDB.Identity? ActingUser
            )
            {
                this.Model = Model;
                this.RegistrationNumber = RegistrationNumber;
                this.ActingUser = ActingUser;
            }

            public CreateBus()
            {
                this.Model = "";
            }

<<<<<<< HEAD
            string IReducerArgs.ReducerName => "CreateBus";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreateBusFlags;
        public void CreateBus(CallReducerFlags flags) => CreateBusFlags = flags;
    }
=======
            string IReducerArgs.ReducerName => "create_bus";
        }
    }
>>>>>>> maintofix
}
