// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateQrSessionHandler(ReducerEventContext ctx, string sessionId, SpacetimeDB.Identity userId, string validationCode, ulong expiryTime, string initiatingDevice);
        public event CreateQrSessionHandler? OnCreateQrSession;

        public void CreateQrSession(string sessionId, SpacetimeDB.Identity userId, string validationCode, ulong expiryTime, string initiatingDevice)
        {
            conn.InternalCallReducer(new Reducer.CreateQrSession(sessionId, userId, validationCode, expiryTime, initiatingDevice));
        }

        public bool InvokeCreateQrSession(ReducerEventContext ctx, Reducer.CreateQrSession args)
        {
            if (OnCreateQrSession == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateQrSession(
                ctx,
                args.SessionId,
                args.UserId,
                args.ValidationCode,
                args.ExpiryTime,
                args.InitiatingDevice
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateQrSession : Reducer, IReducerArgs
        {
            [DataMember(Name = "session_id")]
            public string SessionId;
            [DataMember(Name = "user_id")]
            public SpacetimeDB.Identity UserId;
            [DataMember(Name = "validation_code")]
            public string ValidationCode;
            [DataMember(Name = "expiry_time")]
            public ulong ExpiryTime;
            [DataMember(Name = "initiating_device")]
            public string InitiatingDevice;

            public CreateQrSession(
                string SessionId,
                SpacetimeDB.Identity UserId,
                string ValidationCode,
                ulong ExpiryTime,
                string InitiatingDevice
            )
            {
                this.SessionId = SessionId;
                this.UserId = UserId;
                this.ValidationCode = ValidationCode;
                this.ExpiryTime = ExpiryTime;
                this.InitiatingDevice = InitiatingDevice;
            }

            public CreateQrSession()
            {
                this.SessionId = "";
                this.ValidationCode = "";
                this.InitiatingDevice = "";
            }

            string IReducerArgs.ReducerName => "create_qr_session";
        }
    }
}
