// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreatePassengerHandler(ReducerEventContext ctx, string name, string email, string phoneNumber);
        public event CreatePassengerHandler? OnCreatePassenger;

        public void CreatePassenger(string name, string email, string phoneNumber)
        {
<<<<<<< HEAD
            conn.InternalCallReducer(new Reducer.CreatePassenger(name, email, phoneNumber), this.SetCallReducerFlags.CreatePassengerFlags);
=======
            conn.InternalCallReducer(new Reducer.CreatePassenger(name, email, phoneNumber));
>>>>>>> maintofix
        }

        public bool InvokeCreatePassenger(ReducerEventContext ctx, Reducer.CreatePassenger args)
        {
<<<<<<< HEAD
            if (OnCreatePassenger == null) return false;
=======
            if (OnCreatePassenger == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
>>>>>>> maintofix
            OnCreatePassenger(
                ctx,
                args.Name,
                args.Email,
                args.PhoneNumber
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreatePassenger : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "email")]
            public string Email;
<<<<<<< HEAD
            [DataMember(Name = "phoneNumber")]
=======
            [DataMember(Name = "phone_number")]
>>>>>>> maintofix
            public string PhoneNumber;

            public CreatePassenger(
                string Name,
                string Email,
                string PhoneNumber
            )
            {
                this.Name = Name;
                this.Email = Email;
                this.PhoneNumber = PhoneNumber;
            }

            public CreatePassenger()
            {
                this.Name = "";
                this.Email = "";
                this.PhoneNumber = "";
            }

<<<<<<< HEAD
            string IReducerArgs.ReducerName => "CreatePassenger";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreatePassengerFlags;
        public void CreatePassenger(CallReducerFlags flags) => CreatePassengerFlags = flags;
    }
=======
            string IReducerArgs.ReducerName => "create_passenger";
        }
    }
>>>>>>> maintofix
}
