// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateOpenIdGrantHandler(ReducerEventContext ctx, string grantId, string clientId, SpacetimeDB.Identity userId, string type, System.Collections.Generic.List<string> scopes, ulong expiresAt);
        public event CreateOpenIdGrantHandler? OnCreateOpenIdGrant;

        public void CreateOpenIdGrant(string grantId, string clientId, SpacetimeDB.Identity userId, string type, System.Collections.Generic.List<string> scopes, ulong expiresAt)
        {
            conn.InternalCallReducer(new Reducer.CreateOpenIdGrant(grantId, clientId, userId, type, scopes, expiresAt), this.SetCallReducerFlags.CreateOpenIdGrantFlags);
        }

        public bool InvokeCreateOpenIdGrant(ReducerEventContext ctx, Reducer.CreateOpenIdGrant args)
        {
            if (OnCreateOpenIdGrant == null) return false;
            OnCreateOpenIdGrant(
                ctx,
                args.GrantId,
                args.ClientId,
                args.UserId,
                args.Type,
                args.Scopes,
                args.ExpiresAt
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateOpenIdGrant : Reducer, IReducerArgs
        {
            [DataMember(Name = "grantId")]
            public string GrantId;
            [DataMember(Name = "clientId")]
            public string ClientId;
            [DataMember(Name = "userId")]
            public SpacetimeDB.Identity UserId;
            [DataMember(Name = "type")]
            public string Type;
            [DataMember(Name = "scopes")]
            public System.Collections.Generic.List<string> Scopes;
            [DataMember(Name = "expiresAt")]
            public ulong ExpiresAt;

            public CreateOpenIdGrant(
                string GrantId,
                string ClientId,
                SpacetimeDB.Identity UserId,
                string Type,
                System.Collections.Generic.List<string> Scopes,
                ulong ExpiresAt
            )
            {
                this.GrantId = GrantId;
                this.ClientId = ClientId;
                this.UserId = UserId;
                this.Type = Type;
                this.Scopes = Scopes;
                this.ExpiresAt = ExpiresAt;
            }

            public CreateOpenIdGrant()
            {
                this.GrantId = "";
                this.ClientId = "";
                this.Type = "";
                this.Scopes = new();
            }

            string IReducerArgs.ReducerName => "CreateOpenIdGrant";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreateOpenIdGrantFlags;
        public void CreateOpenIdGrant(CallReducerFlags flags) => CreateOpenIdGrantFlags = flags;
    }
}
