// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeactivateUserHandler(ReducerEventContext ctx, SpacetimeDB.Identity userId, SpacetimeDB.Identity? actingUser);
        public event DeactivateUserHandler? OnDeactivateUser;

        public void DeactivateUser(SpacetimeDB.Identity userId, SpacetimeDB.Identity? actingUser)
        {
            conn.InternalCallReducer(new Reducer.DeactivateUser(userId, actingUser), this.SetCallReducerFlags.DeactivateUserFlags);
        }

        public bool InvokeDeactivateUser(ReducerEventContext ctx, Reducer.DeactivateUser args)
        {
            if (OnDeactivateUser == null) return false;
            OnDeactivateUser(
                ctx,
                args.UserId,
                args.ActingUser
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeactivateUser : Reducer, IReducerArgs
        {
            [DataMember(Name = "userId")]
            public SpacetimeDB.Identity UserId;
            [DataMember(Name = "actingUser")]
            public SpacetimeDB.Identity? ActingUser;

            public DeactivateUser(
                SpacetimeDB.Identity UserId,
                SpacetimeDB.Identity? ActingUser
            )
            {
                this.UserId = UserId;
                this.ActingUser = ActingUser;
            }

            public DeactivateUser()
            {
            }

            string IReducerArgs.ReducerName => "DeactivateUser";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DeactivateUserFlags;
        public void DeactivateUser(CallReducerFlags flags) => DeactivateUserFlags = flags;
    }
}
