// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeactivateTotpSecretHandler(ReducerEventContext ctx, SpacetimeDB.Identity userId);
        public event DeactivateTotpSecretHandler? OnDeactivateTotpSecret;

        public void DeactivateTotpSecret(SpacetimeDB.Identity userId)
        {
            conn.InternalCallReducer(new Reducer.DeactivateTotpSecret(userId), this.SetCallReducerFlags.DeactivateTotpSecretFlags);
        }

        public bool InvokeDeactivateTotpSecret(ReducerEventContext ctx, Reducer.DeactivateTotpSecret args)
        {
            if (OnDeactivateTotpSecret == null) return false;
            OnDeactivateTotpSecret(
                ctx,
                args.UserId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeactivateTotpSecret : Reducer, IReducerArgs
        {
            [DataMember(Name = "userId")]
            public SpacetimeDB.Identity UserId;

            public DeactivateTotpSecret(SpacetimeDB.Identity UserId)
            {
                this.UserId = UserId;
            }

            public DeactivateTotpSecret()
            {
            }

            string IReducerArgs.ReducerName => "DeactivateTotpSecret";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DeactivateTotpSecretFlags;
        public void DeactivateTotpSecret(CallReducerFlags flags) => DeactivateTotpSecretFlags = flags;
    }
}
