// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeactivateScheduleHandler(ReducerEventContext ctx, uint scheduleId, SpacetimeDB.Identity? actingUser);
        public event DeactivateScheduleHandler? OnDeactivateSchedule;

        public void DeactivateSchedule(uint scheduleId, SpacetimeDB.Identity? actingUser)
        {
            conn.InternalCallReducer(new Reducer.DeactivateSchedule(scheduleId, actingUser));
        }

        public bool InvokeDeactivateSchedule(ReducerEventContext ctx, Reducer.DeactivateSchedule args)
        {
            if (OnDeactivateSchedule == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeactivateSchedule(
                ctx,
                args.ScheduleId,
                args.ActingUser
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeactivateSchedule : Reducer, IReducerArgs
        {
            [DataMember(Name = "schedule_id")]
            public uint ScheduleId;
            [DataMember(Name = "acting_user")]
            public SpacetimeDB.Identity? ActingUser;

            public DeactivateSchedule(
                uint ScheduleId,
                SpacetimeDB.Identity? ActingUser
            )
            {
                this.ScheduleId = ScheduleId;
                this.ActingUser = ActingUser;
            }

            public DeactivateSchedule()
            {
            }

            string IReducerArgs.ReducerName => "deactivate_schedule";
        }
    }
}
