// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeactivateScheduleHandler(ReducerEventContext ctx, uint scheduleId);
        public event DeactivateScheduleHandler? OnDeactivateSchedule;

        public void DeactivateSchedule(uint scheduleId)
        {
            conn.InternalCallReducer(new Reducer.DeactivateSchedule(scheduleId), this.SetCallReducerFlags.DeactivateScheduleFlags);
        }

        public bool InvokeDeactivateSchedule(ReducerEventContext ctx, Reducer.DeactivateSchedule args)
        {
            if (OnDeactivateSchedule == null) return false;
            OnDeactivateSchedule(
                ctx,
                args.ScheduleId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeactivateSchedule : Reducer, IReducerArgs
        {
            [DataMember(Name = "scheduleId")]
            public uint ScheduleId;

            public DeactivateSchedule(uint ScheduleId)
            {
                this.ScheduleId = ScheduleId;
            }

            public DeactivateSchedule()
            {
            }

            string IReducerArgs.ReducerName => "DeactivateSchedule";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DeactivateScheduleFlags;
        public void DeactivateSchedule(CallReducerFlags flags) => DeactivateScheduleFlags = flags;
    }
}
