// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeactivateWebAuthnCredentialHandler(ReducerEventContext ctx, uint id);
        public event DeactivateWebAuthnCredentialHandler? OnDeactivateWebAuthnCredential;

        public void DeactivateWebAuthnCredential(uint id)
        {
            conn.InternalCallReducer(new Reducer.DeactivateWebAuthnCredential(id), this.SetCallReducerFlags.DeactivateWebAuthnCredentialFlags);
        }

        public bool InvokeDeactivateWebAuthnCredential(ReducerEventContext ctx, Reducer.DeactivateWebAuthnCredential args)
        {
            if (OnDeactivateWebAuthnCredential == null) return false;
            OnDeactivateWebAuthnCredential(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeactivateWebAuthnCredential : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public uint Id;

            public DeactivateWebAuthnCredential(uint Id)
            {
                this.Id = Id;
            }

            public DeactivateWebAuthnCredential()
            {
            }

            string IReducerArgs.ReducerName => "DeactivateWebAuthnCredential";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DeactivateWebAuthnCredentialFlags;
        public void DeactivateWebAuthnCredential(CallReducerFlags flags) => DeactivateWebAuthnCredentialFlags = flags;
    }
}
