// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeactivateWebAuthnCredentialHandler(ReducerEventContext ctx, uint id);
        public event DeactivateWebAuthnCredentialHandler? OnDeactivateWebAuthnCredential;

        public void DeactivateWebAuthnCredential(uint id)
        {
<<<<<<< HEAD
            conn.InternalCallReducer(new Reducer.DeactivateWebAuthnCredential(id), this.SetCallReducerFlags.DeactivateWebAuthnCredentialFlags);
=======
            conn.InternalCallReducer(new Reducer.DeactivateWebAuthnCredential(id));
>>>>>>> maintofix
        }

        public bool InvokeDeactivateWebAuthnCredential(ReducerEventContext ctx, Reducer.DeactivateWebAuthnCredential args)
        {
<<<<<<< HEAD
            if (OnDeactivateWebAuthnCredential == null) return false;
=======
            if (OnDeactivateWebAuthnCredential == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
>>>>>>> maintofix
            OnDeactivateWebAuthnCredential(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeactivateWebAuthnCredential : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public uint Id;

            public DeactivateWebAuthnCredential(uint Id)
            {
                this.Id = Id;
            }

            public DeactivateWebAuthnCredential()
            {
            }

<<<<<<< HEAD
            string IReducerArgs.ReducerName => "DeactivateWebAuthnCredential";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DeactivateWebAuthnCredentialFlags;
        public void DeactivateWebAuthnCredential(CallReducerFlags flags) => DeactivateWebAuthnCredentialFlags = flags;
    }
=======
            string IReducerArgs.ReducerName => "deactivate_web_authn_credential";
        }
    }
>>>>>>> maintofix
}
