// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteWebAuthnChallengeHandler(ReducerEventContext ctx, uint id);
        public event DeleteWebAuthnChallengeHandler? OnDeleteWebAuthnChallenge;

        public void DeleteWebAuthnChallenge(uint id)
        {
            conn.InternalCallReducer(new Reducer.DeleteWebAuthnChallenge(id));
        }

        public bool InvokeDeleteWebAuthnChallenge(ReducerEventContext ctx, Reducer.DeleteWebAuthnChallenge args)
        {
            if (OnDeleteWebAuthnChallenge == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteWebAuthnChallenge(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteWebAuthnChallenge : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public uint Id;

            public DeleteWebAuthnChallenge(uint Id)
            {
                this.Id = Id;
            }

            public DeleteWebAuthnChallenge()
            {
            }

            string IReducerArgs.ReducerName => "delete_web_authn_challenge";
        }
    }
}
