// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteRouteScheduleHandler(ReducerEventContext ctx, uint scheduleId, SpacetimeDB.Identity? actingUser);
        public event DeleteRouteScheduleHandler? OnDeleteRouteSchedule;

        public void DeleteRouteSchedule(uint scheduleId, SpacetimeDB.Identity? actingUser)
        {
            conn.InternalCallReducer(new Reducer.DeleteRouteSchedule(scheduleId, actingUser), this.SetCallReducerFlags.DeleteRouteScheduleFlags);
        }

        public bool InvokeDeleteRouteSchedule(ReducerEventContext ctx, Reducer.DeleteRouteSchedule args)
        {
            if (OnDeleteRouteSchedule == null) return false;
            OnDeleteRouteSchedule(
                ctx,
                args.ScheduleId,
                args.ActingUser
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteRouteSchedule : Reducer, IReducerArgs
        {
            [DataMember(Name = "scheduleId")]
            public uint ScheduleId;
            [DataMember(Name = "actingUser")]
            public SpacetimeDB.Identity? ActingUser;

            public DeleteRouteSchedule(
                uint ScheduleId,
                SpacetimeDB.Identity? ActingUser
            )
            {
                this.ScheduleId = ScheduleId;
                this.ActingUser = ActingUser;
            }

            public DeleteRouteSchedule()
            {
            }

            string IReducerArgs.ReducerName => "DeleteRouteSchedule";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DeleteRouteScheduleFlags;
        public void DeleteRouteSchedule(CallReducerFlags flags) => DeleteRouteScheduleFlags = flags;
    }
}
