// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteEmployeeHandler(ReducerEventContext ctx, uint employeeId);
        public event DeleteEmployeeHandler? OnDeleteEmployee;

        public void DeleteEmployee(uint employeeId)
        {
            conn.InternalCallReducer(new Reducer.DeleteEmployee(employeeId), this.SetCallReducerFlags.DeleteEmployeeFlags);
        }

        public bool InvokeDeleteEmployee(ReducerEventContext ctx, Reducer.DeleteEmployee args)
        {
            if (OnDeleteEmployee == null) return false;
            OnDeleteEmployee(
                ctx,
                args.EmployeeId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteEmployee : Reducer, IReducerArgs
        {
            [DataMember(Name = "employeeId")]
            public uint EmployeeId;

            public DeleteEmployee(uint EmployeeId)
            {
                this.EmployeeId = EmployeeId;
            }

            public DeleteEmployee()
            {
            }

            string IReducerArgs.ReducerName => "DeleteEmployee";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DeleteEmployeeFlags;
        public void DeleteEmployee(CallReducerFlags flags) => DeleteEmployeeFlags = flags;
    }
}
