// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteOidcAuthorizationHandler(ReducerEventContext ctx, uint internalId);
        public event DeleteOidcAuthorizationHandler? OnDeleteOidcAuthorization;

        public void DeleteOidcAuthorization(uint internalId)
        {
            conn.InternalCallReducer(new Reducer.DeleteOidcAuthorization(internalId), this.SetCallReducerFlags.DeleteOidcAuthorizationFlags);
        }

        public bool InvokeDeleteOidcAuthorization(ReducerEventContext ctx, Reducer.DeleteOidcAuthorization args)
        {
            if (OnDeleteOidcAuthorization == null) return false;
            OnDeleteOidcAuthorization(
                ctx,
                args.InternalId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteOidcAuthorization : Reducer, IReducerArgs
        {
            [DataMember(Name = "internalId")]
            public uint InternalId;

            public DeleteOidcAuthorization(uint InternalId)
            {
                this.InternalId = InternalId;
            }

            public DeleteOidcAuthorization()
            {
            }

            string IReducerArgs.ReducerName => "DeleteOidcAuthorization";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DeleteOidcAuthorizationFlags;
        public void DeleteOidcAuthorization(CallReducerFlags flags) => DeleteOidcAuthorizationFlags = flags;
    }
}
