// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteQrSessionHandler(ReducerEventContext ctx, string sessionId);
        public event DeleteQrSessionHandler? OnDeleteQrSession;

        public void DeleteQrSession(string sessionId)
        {
<<<<<<< HEAD
            conn.InternalCallReducer(new Reducer.DeleteQrSession(sessionId), this.SetCallReducerFlags.DeleteQrSessionFlags);
=======
            conn.InternalCallReducer(new Reducer.DeleteQrSession(sessionId));
>>>>>>> maintofix
        }

        public bool InvokeDeleteQrSession(ReducerEventContext ctx, Reducer.DeleteQrSession args)
        {
<<<<<<< HEAD
            if (OnDeleteQrSession == null) return false;
=======
            if (OnDeleteQrSession == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
>>>>>>> maintofix
            OnDeleteQrSession(
                ctx,
                args.SessionId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteQrSession : Reducer, IReducerArgs
        {
<<<<<<< HEAD
            [DataMember(Name = "sessionId")]
=======
            [DataMember(Name = "session_id")]
>>>>>>> maintofix
            public string SessionId;

            public DeleteQrSession(string SessionId)
            {
                this.SessionId = SessionId;
            }

            public DeleteQrSession()
            {
                this.SessionId = "";
            }

<<<<<<< HEAD
            string IReducerArgs.ReducerName => "DeleteQRSession";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DeleteQrSessionFlags;
        public void DeleteQrSession(CallReducerFlags flags) => DeleteQrSessionFlags = flags;
    }
=======
            string IReducerArgs.ReducerName => "delete_qr_session";
        }
    }
>>>>>>> maintofix
}
