// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteJobHandler(ReducerEventContext ctx, uint jobId);
        public event DeleteJobHandler? OnDeleteJob;

        public void DeleteJob(uint jobId)
        {
            conn.InternalCallReducer(new Reducer.DeleteJob(jobId), this.SetCallReducerFlags.DeleteJobFlags);
        }

        public bool InvokeDeleteJob(ReducerEventContext ctx, Reducer.DeleteJob args)
        {
            if (OnDeleteJob == null) return false;
            OnDeleteJob(
                ctx,
                args.JobId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteJob : Reducer, IReducerArgs
        {
            [DataMember(Name = "jobId")]
            public uint JobId;

            public DeleteJob(uint JobId)
            {
                this.JobId = JobId;
            }

            public DeleteJob()
            {
            }

            string IReducerArgs.ReducerName => "DeleteJob";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DeleteJobFlags;
        public void DeleteJob(CallReducerFlags flags) => DeleteJobFlags = flags;
    }
}
