// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteRoleHandler(ReducerEventContext ctx, uint roleId, SpacetimeDB.Identity? actingUserId);
        public event DeleteRoleHandler? OnDeleteRole;

        public void DeleteRole(uint roleId, SpacetimeDB.Identity? actingUserId)
        {
<<<<<<< HEAD
            conn.InternalCallReducer(new Reducer.DeleteRole(roleId, actingUserId), this.SetCallReducerFlags.DeleteRoleFlags);
=======
            conn.InternalCallReducer(new Reducer.DeleteRole(roleId, actingUserId));
>>>>>>> maintofix
        }

        public bool InvokeDeleteRole(ReducerEventContext ctx, Reducer.DeleteRole args)
        {
<<<<<<< HEAD
            if (OnDeleteRole == null) return false;
=======
            if (OnDeleteRole == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
>>>>>>> maintofix
            OnDeleteRole(
                ctx,
                args.RoleId,
                args.ActingUserId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteRole : Reducer, IReducerArgs
        {
<<<<<<< HEAD
            [DataMember(Name = "roleId")]
            public uint RoleId;
            [DataMember(Name = "actingUserId")]
=======
            [DataMember(Name = "role_id")]
            public uint RoleId;
            [DataMember(Name = "acting_user_id")]
>>>>>>> maintofix
            public SpacetimeDB.Identity? ActingUserId;

            public DeleteRole(
                uint RoleId,
                SpacetimeDB.Identity? ActingUserId
            )
            {
                this.RoleId = RoleId;
                this.ActingUserId = ActingUserId;
            }

            public DeleteRole()
            {
            }

<<<<<<< HEAD
            string IReducerArgs.ReducerName => "DeleteRole";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DeleteRoleFlags;
        public void DeleteRole(CallReducerFlags flags) => DeleteRoleFlags = flags;
    }
=======
            string IReducerArgs.ReducerName => "delete_role";
        }
    }
>>>>>>> maintofix
}
