// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DisableWebAuthnHandler(ReducerEventContext ctx, SpacetimeDB.Identity userId);
        public event DisableWebAuthnHandler? OnDisableWebAuthn;

        public void DisableWebAuthn(SpacetimeDB.Identity userId)
        {
            conn.InternalCallReducer(new Reducer.DisableWebAuthn(userId), this.SetCallReducerFlags.DisableWebAuthnFlags);
        }

        public bool InvokeDisableWebAuthn(ReducerEventContext ctx, Reducer.DisableWebAuthn args)
        {
            if (OnDisableWebAuthn == null) return false;
            OnDisableWebAuthn(
                ctx,
                args.UserId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DisableWebAuthn : Reducer, IReducerArgs
        {
            [DataMember(Name = "userId")]
            public SpacetimeDB.Identity UserId;

            public DisableWebAuthn(SpacetimeDB.Identity UserId)
            {
                this.UserId = UserId;
            }

            public DisableWebAuthn()
            {
            }

            string IReducerArgs.ReducerName => "DisableWebAuthn";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DisableWebAuthnFlags;
        public void DisableWebAuthn(CallReducerFlags flags) => DisableWebAuthnFlags = flags;
    }
}
