// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EnableWebAuthnHandler(ReducerEventContext ctx, SpacetimeDB.Identity userId);
        public event EnableWebAuthnHandler? OnEnableWebAuthn;

        public void EnableWebAuthn(SpacetimeDB.Identity userId)
        {
            conn.InternalCallReducer(new Reducer.EnableWebAuthn(userId), this.SetCallReducerFlags.EnableWebAuthnFlags);
        }

        public bool InvokeEnableWebAuthn(ReducerEventContext ctx, Reducer.EnableWebAuthn args)
        {
            if (OnEnableWebAuthn == null) return false;
            OnEnableWebAuthn(
                ctx,
                args.UserId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EnableWebAuthn : Reducer, IReducerArgs
        {
            [DataMember(Name = "userId")]
            public SpacetimeDB.Identity UserId;

            public EnableWebAuthn(SpacetimeDB.Identity UserId)
            {
                this.UserId = UserId;
            }

            public EnableWebAuthn()
            {
            }

            string IReducerArgs.ReducerName => "EnableWebAuthn";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags EnableWebAuthnFlags;
        public void EnableWebAuthn(CallReducerFlags flags) => EnableWebAuthnFlags = flags;
    }
}
