// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void GetBusMaintenanceHistoryHandler(ReducerEventContext ctx, uint busId, SpacetimeDB.Identity? actingUser);
        public event GetBusMaintenanceHistoryHandler? OnGetBusMaintenanceHistory;

        public void GetBusMaintenanceHistory(uint busId, SpacetimeDB.Identity? actingUser)
        {
            conn.InternalCallReducer(new Reducer.GetBusMaintenanceHistory(busId, actingUser), this.SetCallReducerFlags.GetBusMaintenanceHistoryFlags);
        }

        public bool InvokeGetBusMaintenanceHistory(ReducerEventContext ctx, Reducer.GetBusMaintenanceHistory args)
        {
            if (OnGetBusMaintenanceHistory == null) return false;
            OnGetBusMaintenanceHistory(
                ctx,
                args.BusId,
                args.ActingUser
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class GetBusMaintenanceHistory : Reducer, IReducerArgs
        {
            [DataMember(Name = "busId")]
            public uint BusId;
            [DataMember(Name = "actingUser")]
            public SpacetimeDB.Identity? ActingUser;

            public GetBusMaintenanceHistory(
                uint BusId,
                SpacetimeDB.Identity? ActingUser
            )
            {
                this.BusId = BusId;
                this.ActingUser = ActingUser;
            }

            public GetBusMaintenanceHistory()
            {
            }

            string IReducerArgs.ReducerName => "GetBusMaintenanceHistory";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags GetBusMaintenanceHistoryFlags;
        public void GetBusMaintenanceHistory(CallReducerFlags flags) => GetBusMaintenanceHistoryFlags = flags;
    }
}
