// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void GrantPermissionToRoleHandler(ReducerEventContext ctx, uint roleId, uint permissionId, SpacetimeDB.Identity? actingUserId);
        public event GrantPermissionToRoleHandler? OnGrantPermissionToRole;

        public void GrantPermissionToRole(uint roleId, uint permissionId, SpacetimeDB.Identity? actingUserId)
        {
            conn.InternalCallReducer(new Reducer.GrantPermissionToRole(roleId, permissionId, actingUserId));
        }

        public bool InvokeGrantPermissionToRole(ReducerEventContext ctx, Reducer.GrantPermissionToRole args)
        {
            if (OnGrantPermissionToRole == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnGrantPermissionToRole(
                ctx,
                args.RoleId,
                args.PermissionId,
                args.ActingUserId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class GrantPermissionToRole : Reducer, IReducerArgs
        {
            [DataMember(Name = "role_id")]
            public uint RoleId;
            [DataMember(Name = "permission_id")]
            public uint PermissionId;
            [DataMember(Name = "acting_user_id")]
            public SpacetimeDB.Identity? ActingUserId;

            public GrantPermissionToRole(
                uint RoleId,
                uint PermissionId,
                SpacetimeDB.Identity? ActingUserId
            )
            {
                this.RoleId = RoleId;
                this.PermissionId = PermissionId;
                this.ActingUserId = ActingUserId;
            }

            public GrantPermissionToRole()
            {
            }

            string IReducerArgs.ReducerName => "grant_permission_to_role";
        }
    }
}
