// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RegisterWebAuthnCredentialHandler(ReducerEventContext ctx, SpacetimeDB.Identity userId, System.Collections.Generic.List<byte> credentialId, string publicKey, uint counter, string? deviceName);
        public event RegisterWebAuthnCredentialHandler? OnRegisterWebAuthnCredential;

        public void RegisterWebAuthnCredential(SpacetimeDB.Identity userId, System.Collections.Generic.List<byte> credentialId, string publicKey, uint counter, string? deviceName)
        {
<<<<<<< HEAD
            conn.InternalCallReducer(new Reducer.RegisterWebAuthnCredential(userId, credentialId, publicKey, counter, deviceName), this.SetCallReducerFlags.RegisterWebAuthnCredentialFlags);
=======
            conn.InternalCallReducer(new Reducer.RegisterWebAuthnCredential(userId, credentialId, publicKey, counter, deviceName));
>>>>>>> maintofix
        }

        public bool InvokeRegisterWebAuthnCredential(ReducerEventContext ctx, Reducer.RegisterWebAuthnCredential args)
        {
<<<<<<< HEAD
            if (OnRegisterWebAuthnCredential == null) return false;
=======
            if (OnRegisterWebAuthnCredential == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
>>>>>>> maintofix
            OnRegisterWebAuthnCredential(
                ctx,
                args.UserId,
                args.CredentialId,
                args.PublicKey,
                args.Counter,
                args.DeviceName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RegisterWebAuthnCredential : Reducer, IReducerArgs
        {
<<<<<<< HEAD
            [DataMember(Name = "userId")]
            public SpacetimeDB.Identity UserId;
            [DataMember(Name = "credentialId")]
            public System.Collections.Generic.List<byte> CredentialId;
            [DataMember(Name = "publicKey")]
            public string PublicKey;
            [DataMember(Name = "counter")]
            public uint Counter;
            [DataMember(Name = "deviceName")]
=======
            [DataMember(Name = "user_id")]
            public SpacetimeDB.Identity UserId;
            [DataMember(Name = "credential_id")]
            public System.Collections.Generic.List<byte> CredentialId;
            [DataMember(Name = "public_key")]
            public string PublicKey;
            [DataMember(Name = "counter")]
            public uint Counter;
            [DataMember(Name = "device_name")]
>>>>>>> maintofix
            public string? DeviceName;

            public RegisterWebAuthnCredential(
                SpacetimeDB.Identity UserId,
                System.Collections.Generic.List<byte> CredentialId,
                string PublicKey,
                uint Counter,
                string? DeviceName
            )
            {
                this.UserId = UserId;
                this.CredentialId = CredentialId;
                this.PublicKey = PublicKey;
                this.Counter = Counter;
                this.DeviceName = DeviceName;
            }

            public RegisterWebAuthnCredential()
            {
                this.CredentialId = new();
                this.PublicKey = "";
            }

<<<<<<< HEAD
            string IReducerArgs.ReducerName => "RegisterWebAuthnCredential";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RegisterWebAuthnCredentialFlags;
        public void RegisterWebAuthnCredential(CallReducerFlags flags) => RegisterWebAuthnCredentialFlags = flags;
    }
=======
            string IReducerArgs.ReducerName => "register_web_authn_credential";
        }
    }
>>>>>>> maintofix
}
