// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RevokeOpenIdGrantHandler(ReducerEventContext ctx, string grantId);
        public event RevokeOpenIdGrantHandler? OnRevokeOpenIdGrant;

        public void RevokeOpenIdGrant(string grantId)
        {
            conn.InternalCallReducer(new Reducer.RevokeOpenIdGrant(grantId), this.SetCallReducerFlags.RevokeOpenIdGrantFlags);
        }

        public bool InvokeRevokeOpenIdGrant(ReducerEventContext ctx, Reducer.RevokeOpenIdGrant args)
        {
            if (OnRevokeOpenIdGrant == null) return false;
            OnRevokeOpenIdGrant(
                ctx,
                args.GrantId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RevokeOpenIdGrant : Reducer, IReducerArgs
        {
            [DataMember(Name = "grantId")]
            public string GrantId;

            public RevokeOpenIdGrant(string GrantId)
            {
                this.GrantId = GrantId;
            }

            public RevokeOpenIdGrant()
            {
                this.GrantId = "";
            }

            string IReducerArgs.ReducerName => "RevokeOpenIdGrant";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RevokeOpenIdGrantFlags;
        public void RevokeOpenIdGrant(CallReducerFlags flags) => RevokeOpenIdGrantFlags = flags;
    }
}
