// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RevokeOpenIdClientHandler(ReducerEventContext ctx, string clientId);
        public event RevokeOpenIdClientHandler? OnRevokeOpenIdClient;

        public void RevokeOpenIdClient(string clientId)
        {
<<<<<<< HEAD
            conn.InternalCallReducer(new Reducer.RevokeOpenIdClient(clientId), this.SetCallReducerFlags.RevokeOpenIdClientFlags);
=======
            conn.InternalCallReducer(new Reducer.RevokeOpenIdClient(clientId));
>>>>>>> maintofix
        }

        public bool InvokeRevokeOpenIdClient(ReducerEventContext ctx, Reducer.RevokeOpenIdClient args)
        {
<<<<<<< HEAD
            if (OnRevokeOpenIdClient == null) return false;
=======
            if (OnRevokeOpenIdClient == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
>>>>>>> maintofix
            OnRevokeOpenIdClient(
                ctx,
                args.ClientId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RevokeOpenIdClient : Reducer, IReducerArgs
        {
<<<<<<< HEAD
            [DataMember(Name = "clientId")]
=======
            [DataMember(Name = "client_id")]
>>>>>>> maintofix
            public string ClientId;

            public RevokeOpenIdClient(string ClientId)
            {
                this.ClientId = ClientId;
            }

            public RevokeOpenIdClient()
            {
                this.ClientId = "";
            }

<<<<<<< HEAD
            string IReducerArgs.ReducerName => "RevokeOpenIdClient";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RevokeOpenIdClientFlags;
        public void RevokeOpenIdClient(CallReducerFlags flags) => RevokeOpenIdClientFlags = flags;
    }
=======
            string IReducerArgs.ReducerName => "revoke_open_id_client";
        }
    }
>>>>>>> maintofix
}
