// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RevokeOpenIdGrantHandler(ReducerEventContext ctx, string grantId);
        public event RevokeOpenIdGrantHandler? OnRevokeOpenIdGrant;

        public void RevokeOpenIdGrant(string grantId)
        {
            conn.InternalCallReducer(new Reducer.RevokeOpenIdGrant(grantId));
        }

        public bool InvokeRevokeOpenIdGrant(ReducerEventContext ctx, Reducer.RevokeOpenIdGrant args)
        {
            if (OnRevokeOpenIdGrant == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRevokeOpenIdGrant(
                ctx,
                args.GrantId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RevokeOpenIdGrant : Reducer, IReducerArgs
        {
            [DataMember(Name = "grant_id")]
            public string GrantId;

            public RevokeOpenIdGrant(string GrantId)
            {
                this.GrantId = GrantId;
            }

            public RevokeOpenIdGrant()
            {
                this.GrantId = "";
            }

            string IReducerArgs.ReducerName => "revoke_open_id_grant";
        }
    }
}
