// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RevokePermissionHandler(ReducerEventContext ctx, uint roleId, uint permissionId);
        public event RevokePermissionHandler? OnRevokePermission;

        public void RevokePermission(uint roleId, uint permissionId)
        {
            conn.InternalCallReducer(new Reducer.RevokePermission(roleId, permissionId), this.SetCallReducerFlags.RevokePermissionFlags);
        }

        public bool InvokeRevokePermission(ReducerEventContext ctx, Reducer.RevokePermission args)
        {
            if (OnRevokePermission == null) return false;
            OnRevokePermission(
                ctx,
                args.RoleId,
                args.PermissionId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RevokePermission : Reducer, IReducerArgs
        {
            [DataMember(Name = "roleId")]
            public uint RoleId;
            [DataMember(Name = "permissionId")]
            public uint PermissionId;

            public RevokePermission(
                uint RoleId,
                uint PermissionId
            )
            {
                this.RoleId = RoleId;
                this.PermissionId = PermissionId;
            }

            public RevokePermission()
            {
            }

            string IReducerArgs.ReducerName => "RevokePermission";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RevokePermissionFlags;
        public void RevokePermission(CallReducerFlags flags) => RevokePermissionFlags = flags;
    }
}
