// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateOidcAuthorizationHandler(ReducerEventContext ctx, uint internalId, string? propertiesJson, string? scopesJson, string? status);
        public event UpdateOidcAuthorizationHandler? OnUpdateOidcAuthorization;

        public void UpdateOidcAuthorization(uint internalId, string? propertiesJson, string? scopesJson, string? status)
        {
<<<<<<< HEAD
            conn.InternalCallReducer(new Reducer.UpdateOidcAuthorization(internalId, propertiesJson, scopesJson, status), this.SetCallReducerFlags.UpdateOidcAuthorizationFlags);
=======
            conn.InternalCallReducer(new Reducer.UpdateOidcAuthorization(internalId, propertiesJson, scopesJson, status));
>>>>>>> maintofix
        }

        public bool InvokeUpdateOidcAuthorization(ReducerEventContext ctx, Reducer.UpdateOidcAuthorization args)
        {
<<<<<<< HEAD
            if (OnUpdateOidcAuthorization == null) return false;
=======
            if (OnUpdateOidcAuthorization == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
>>>>>>> maintofix
            OnUpdateOidcAuthorization(
                ctx,
                args.InternalId,
                args.PropertiesJson,
                args.ScopesJson,
                args.Status
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateOidcAuthorization : Reducer, IReducerArgs
        {
<<<<<<< HEAD
            [DataMember(Name = "internalId")]
            public uint InternalId;
            [DataMember(Name = "propertiesJson")]
            public string? PropertiesJson;
            [DataMember(Name = "scopesJson")]
=======
            [DataMember(Name = "internal_id")]
            public uint InternalId;
            [DataMember(Name = "properties_json")]
            public string? PropertiesJson;
            [DataMember(Name = "scopes_json")]
>>>>>>> maintofix
            public string? ScopesJson;
            [DataMember(Name = "status")]
            public string? Status;

            public UpdateOidcAuthorization(
                uint InternalId,
                string? PropertiesJson,
                string? ScopesJson,
                string? Status
            )
            {
                this.InternalId = InternalId;
                this.PropertiesJson = PropertiesJson;
                this.ScopesJson = ScopesJson;
                this.Status = Status;
            }

            public UpdateOidcAuthorization()
            {
            }

<<<<<<< HEAD
            string IReducerArgs.ReducerName => "UpdateOidcAuthorization";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateOidcAuthorizationFlags;
        public void UpdateOidcAuthorization(CallReducerFlags flags) => UpdateOidcAuthorizationFlags = flags;
    }
=======
            string IReducerArgs.ReducerName => "update_oidc_authorization";
        }
    }
>>>>>>> maintofix
}
