// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateRouteHandler(ReducerEventContext ctx, uint routeId, string? startPoint, string? endPoint, uint? driverId, uint? busId, string? travelTime, bool? isActive, SpacetimeDB.Identity? actingUser);
        public event UpdateRouteHandler? OnUpdateRoute;

        public void UpdateRoute(uint routeId, string? startPoint, string? endPoint, uint? driverId, uint? busId, string? travelTime, bool? isActive, SpacetimeDB.Identity? actingUser)
        {
            conn.InternalCallReducer(new Reducer.UpdateRoute(routeId, startPoint, endPoint, driverId, busId, travelTime, isActive, actingUser), this.SetCallReducerFlags.UpdateRouteFlags);
        }

        public bool InvokeUpdateRoute(ReducerEventContext ctx, Reducer.UpdateRoute args)
        {
            if (OnUpdateRoute == null) return false;
            OnUpdateRoute(
                ctx,
                args.RouteId,
                args.StartPoint,
                args.EndPoint,
                args.DriverId,
                args.BusId,
                args.TravelTime,
                args.IsActive,
                args.ActingUser
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateRoute : Reducer, IReducerArgs
        {
            [DataMember(Name = "routeId")]
            public uint RouteId;
            [DataMember(Name = "startPoint")]
            public string? StartPoint;
            [DataMember(Name = "endPoint")]
            public string? EndPoint;
            [DataMember(Name = "driverId")]
            public uint? DriverId;
            [DataMember(Name = "busId")]
            public uint? BusId;
            [DataMember(Name = "travelTime")]
            public string? TravelTime;
            [DataMember(Name = "isActive")]
            public bool? IsActive;
            [DataMember(Name = "actingUser")]
            public SpacetimeDB.Identity? ActingUser;

            public UpdateRoute(
                uint RouteId,
                string? StartPoint,
                string? EndPoint,
                uint? DriverId,
                uint? BusId,
                string? TravelTime,
                bool? IsActive,
                SpacetimeDB.Identity? ActingUser
            )
            {
                this.RouteId = RouteId;
                this.StartPoint = StartPoint;
                this.EndPoint = EndPoint;
                this.DriverId = DriverId;
                this.BusId = BusId;
                this.TravelTime = TravelTime;
                this.IsActive = IsActive;
                this.ActingUser = ActingUser;
            }

            public UpdateRoute()
            {
            }

            string IReducerArgs.ReducerName => "UpdateRoute";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateRouteFlags;
        public void UpdateRoute(CallReducerFlags flags) => UpdateRouteFlags = flags;
    }
}
