// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateWebAuthnCounterHandler(ReducerEventContext ctx, System.Collections.Generic.List<byte> credentialId, uint counter);
        public event UpdateWebAuthnCounterHandler? OnUpdateWebAuthnCounter;

        public void UpdateWebAuthnCounter(System.Collections.Generic.List<byte> credentialId, uint counter)
        {
            conn.InternalCallReducer(new Reducer.UpdateWebAuthnCounter(credentialId, counter), this.SetCallReducerFlags.UpdateWebAuthnCounterFlags);
        }

        public bool InvokeUpdateWebAuthnCounter(ReducerEventContext ctx, Reducer.UpdateWebAuthnCounter args)
        {
            if (OnUpdateWebAuthnCounter == null) return false;
            OnUpdateWebAuthnCounter(
                ctx,
                args.CredentialId,
                args.Counter
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateWebAuthnCounter : Reducer, IReducerArgs
        {
            [DataMember(Name = "credentialId")]
            public System.Collections.Generic.List<byte> CredentialId;
            [DataMember(Name = "counter")]
            public uint Counter;

            public UpdateWebAuthnCounter(
                System.Collections.Generic.List<byte> CredentialId,
                uint Counter
            )
            {
                this.CredentialId = CredentialId;
                this.Counter = Counter;
            }

            public UpdateWebAuthnCounter()
            {
                this.CredentialId = new();
            }

            string IReducerArgs.ReducerName => "UpdateWebAuthnCounter";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateWebAuthnCounterFlags;
        public void UpdateWebAuthnCounter(CallReducerFlags flags) => UpdateWebAuthnCounterFlags = flags;
    }
}
