// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateTwoFactorTokenHandler(ReducerEventContext ctx, uint id, SpacetimeDB.Identity userId, string token, bool isUsed, ulong expiresAt);
        public event UpdateTwoFactorTokenHandler? OnUpdateTwoFactorToken;

        public void UpdateTwoFactorToken(uint id, SpacetimeDB.Identity userId, string token, bool isUsed, ulong expiresAt)
        {
            conn.InternalCallReducer(new Reducer.UpdateTwoFactorToken(id, userId, token, isUsed, expiresAt), this.SetCallReducerFlags.UpdateTwoFactorTokenFlags);
        }

        public bool InvokeUpdateTwoFactorToken(ReducerEventContext ctx, Reducer.UpdateTwoFactorToken args)
        {
            if (OnUpdateTwoFactorToken == null) return false;
            OnUpdateTwoFactorToken(
                ctx,
                args.Id,
                args.UserId,
                args.Token,
                args.IsUsed,
                args.ExpiresAt
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateTwoFactorToken : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public uint Id;
            [DataMember(Name = "userId")]
            public SpacetimeDB.Identity UserId;
            [DataMember(Name = "token")]
            public string Token;
            [DataMember(Name = "isUsed")]
            public bool IsUsed;
            [DataMember(Name = "expiresAt")]
            public ulong ExpiresAt;

            public UpdateTwoFactorToken(
                uint Id,
                SpacetimeDB.Identity UserId,
                string Token,
                bool IsUsed,
                ulong ExpiresAt
            )
            {
                this.Id = Id;
                this.UserId = UserId;
                this.Token = Token;
                this.IsUsed = IsUsed;
                this.ExpiresAt = ExpiresAt;
            }

            public UpdateTwoFactorToken()
            {
                this.Token = "";
            }

            string IReducerArgs.ReducerName => "UpdateTwoFactorToken";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateTwoFactorTokenFlags;
        public void UpdateTwoFactorToken(CallReducerFlags flags) => UpdateTwoFactorTokenFlags = flags;
    }
}
