// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateJobHandler(ReducerEventContext ctx, uint jobId, string? jobTitle, string? internship, SpacetimeDB.Identity? actingUser);
        public event UpdateJobHandler? OnUpdateJob;

        public void UpdateJob(uint jobId, string? jobTitle, string? internship, SpacetimeDB.Identity? actingUser)
        {
<<<<<<< HEAD
            conn.InternalCallReducer(new Reducer.UpdateJob(jobId, jobTitle, internship, actingUser), this.SetCallReducerFlags.UpdateJobFlags);
=======
            conn.InternalCallReducer(new Reducer.UpdateJob(jobId, jobTitle, internship, actingUser));
>>>>>>> maintofix
        }

        public bool InvokeUpdateJob(ReducerEventContext ctx, Reducer.UpdateJob args)
        {
<<<<<<< HEAD
            if (OnUpdateJob == null) return false;
=======
            if (OnUpdateJob == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
>>>>>>> maintofix
            OnUpdateJob(
                ctx,
                args.JobId,
                args.JobTitle,
                args.Internship,
                args.ActingUser
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateJob : Reducer, IReducerArgs
        {
<<<<<<< HEAD
            [DataMember(Name = "jobId")]
            public uint JobId;
            [DataMember(Name = "jobTitle")]
            public string? JobTitle;
            [DataMember(Name = "internship")]
            public string? Internship;
            [DataMember(Name = "actingUser")]
=======
            [DataMember(Name = "job_id")]
            public uint JobId;
            [DataMember(Name = "job_title")]
            public string? JobTitle;
            [DataMember(Name = "internship")]
            public string? Internship;
            [DataMember(Name = "acting_user")]
>>>>>>> maintofix
            public SpacetimeDB.Identity? ActingUser;

            public UpdateJob(
                uint JobId,
                string? JobTitle,
                string? Internship,
                SpacetimeDB.Identity? ActingUser
            )
            {
                this.JobId = JobId;
                this.JobTitle = JobTitle;
                this.Internship = Internship;
                this.ActingUser = ActingUser;
            }

            public UpdateJob()
            {
            }

<<<<<<< HEAD
            string IReducerArgs.ReducerName => "UpdateJob";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateJobFlags;
        public void UpdateJob(CallReducerFlags flags) => UpdateJobFlags = flags;
    }
=======
            string IReducerArgs.ReducerName => "update_job";
        }
    }
>>>>>>> maintofix
}
