// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdatePassengerHandler(ReducerEventContext ctx, uint passengerId, string? name, string? email, string? phoneNumber, bool? isActive);
        public event UpdatePassengerHandler? OnUpdatePassenger;

        public void UpdatePassenger(uint passengerId, string? name, string? email, string? phoneNumber, bool? isActive)
        {
<<<<<<< HEAD
            conn.InternalCallReducer(new Reducer.UpdatePassenger(passengerId, name, email, phoneNumber, isActive), this.SetCallReducerFlags.UpdatePassengerFlags);
=======
            conn.InternalCallReducer(new Reducer.UpdatePassenger(passengerId, name, email, phoneNumber, isActive));
>>>>>>> maintofix
        }

        public bool InvokeUpdatePassenger(ReducerEventContext ctx, Reducer.UpdatePassenger args)
        {
<<<<<<< HEAD
            if (OnUpdatePassenger == null) return false;
=======
            if (OnUpdatePassenger == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
>>>>>>> maintofix
            OnUpdatePassenger(
                ctx,
                args.PassengerId,
                args.Name,
                args.Email,
                args.PhoneNumber,
                args.IsActive
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdatePassenger : Reducer, IReducerArgs
        {
<<<<<<< HEAD
            [DataMember(Name = "passengerId")]
=======
            [DataMember(Name = "passenger_id")]
>>>>>>> maintofix
            public uint PassengerId;
            [DataMember(Name = "name")]
            public string? Name;
            [DataMember(Name = "email")]
            public string? Email;
<<<<<<< HEAD
            [DataMember(Name = "phoneNumber")]
            public string? PhoneNumber;
            [DataMember(Name = "isActive")]
=======
            [DataMember(Name = "phone_number")]
            public string? PhoneNumber;
            [DataMember(Name = "is_active")]
>>>>>>> maintofix
            public bool? IsActive;

            public UpdatePassenger(
                uint PassengerId,
                string? Name,
                string? Email,
                string? PhoneNumber,
                bool? IsActive
            )
            {
                this.PassengerId = PassengerId;
                this.Name = Name;
                this.Email = Email;
                this.PhoneNumber = PhoneNumber;
                this.IsActive = IsActive;
            }

            public UpdatePassenger()
            {
            }

<<<<<<< HEAD
            string IReducerArgs.ReducerName => "UpdatePassenger";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdatePassengerFlags;
        public void UpdatePassenger(CallReducerFlags flags) => UpdatePassengerFlags = flags;
    }
=======
            string IReducerArgs.ReducerName => "update_passenger";
        }
    }
>>>>>>> maintofix
}
