// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateEmployeeHandler(ReducerEventContext ctx, uint employeeId, string? employeeName, string? employeeSurname, string? employeePatronym, uint? jobId, SpacetimeDB.Identity? actingUser);
        public event UpdateEmployeeHandler? OnUpdateEmployee;

        public void UpdateEmployee(uint employeeId, string? employeeName, string? employeeSurname, string? employeePatronym, uint? jobId, SpacetimeDB.Identity? actingUser)
        {
            conn.InternalCallReducer(new Reducer.UpdateEmployee(employeeId, employeeName, employeeSurname, employeePatronym, jobId, actingUser));
        }

        public bool InvokeUpdateEmployee(ReducerEventContext ctx, Reducer.UpdateEmployee args)
        {
            if (OnUpdateEmployee == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateEmployee(
                ctx,
                args.EmployeeId,
                args.EmployeeName,
                args.EmployeeSurname,
                args.EmployeePatronym,
                args.JobId,
                args.ActingUser
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateEmployee : Reducer, IReducerArgs
        {
            [DataMember(Name = "employee_id")]
            public uint EmployeeId;
            [DataMember(Name = "employee_name")]
            public string? EmployeeName;
            [DataMember(Name = "employee_surname")]
            public string? EmployeeSurname;
            [DataMember(Name = "employee_patronym")]
            public string? EmployeePatronym;
            [DataMember(Name = "job_id")]
            public uint? JobId;
            [DataMember(Name = "acting_user")]
            public SpacetimeDB.Identity? ActingUser;

            public UpdateEmployee(
                uint EmployeeId,
                string? EmployeeName,
                string? EmployeeSurname,
                string? EmployeePatronym,
                uint? JobId,
                SpacetimeDB.Identity? ActingUser
            )
            {
                this.EmployeeId = EmployeeId;
                this.EmployeeName = EmployeeName;
                this.EmployeeSurname = EmployeeSurname;
                this.EmployeePatronym = EmployeePatronym;
                this.JobId = JobId;
                this.ActingUser = ActingUser;
            }

            public UpdateEmployee()
            {
            }

            string IReducerArgs.ReducerName => "update_employee";
        }
    }
}
