// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateWebAuthnCredentialCounterHandler(ReducerEventContext ctx, uint id, uint counter);
        public event UpdateWebAuthnCredentialCounterHandler? OnUpdateWebAuthnCredentialCounter;

        public void UpdateWebAuthnCredentialCounter(uint id, uint counter)
        {
            conn.InternalCallReducer(new Reducer.UpdateWebAuthnCredentialCounter(id, counter), this.SetCallReducerFlags.UpdateWebAuthnCredentialCounterFlags);
        }

        public bool InvokeUpdateWebAuthnCredentialCounter(ReducerEventContext ctx, Reducer.UpdateWebAuthnCredentialCounter args)
        {
            if (OnUpdateWebAuthnCredentialCounter == null) return false;
            OnUpdateWebAuthnCredentialCounter(
                ctx,
                args.Id,
                args.Counter
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateWebAuthnCredentialCounter : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public uint Id;
            [DataMember(Name = "counter")]
            public uint Counter;

            public UpdateWebAuthnCredentialCounter(
                uint Id,
                uint Counter
            )
            {
                this.Id = Id;
                this.Counter = Counter;
            }

            public UpdateWebAuthnCredentialCounter()
            {
            }

            string IReducerArgs.ReducerName => "UpdateWebAuthnCredentialCounter";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateWebAuthnCredentialCounterFlags;
        public void UpdateWebAuthnCredentialCounter(CallReducerFlags flags) => UpdateWebAuthnCredentialCounterFlags = flags;
    }
}
