// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateOidcScopeHandler(ReducerEventContext ctx, uint internalId, string? description, string? descriptionsJson, string? displayName, string? displayNamesJson, string? propertiesJson, string? resourcesJson);
        public event UpdateOidcScopeHandler? OnUpdateOidcScope;

        public void UpdateOidcScope(uint internalId, string? description, string? descriptionsJson, string? displayName, string? displayNamesJson, string? propertiesJson, string? resourcesJson)
        {
            conn.InternalCallReducer(new Reducer.UpdateOidcScope(internalId, description, descriptionsJson, displayName, displayNamesJson, propertiesJson, resourcesJson), this.SetCallReducerFlags.UpdateOidcScopeFlags);
        }

        public bool InvokeUpdateOidcScope(ReducerEventContext ctx, Reducer.UpdateOidcScope args)
        {
            if (OnUpdateOidcScope == null) return false;
            OnUpdateOidcScope(
                ctx,
                args.InternalId,
                args.Description,
                args.DescriptionsJson,
                args.DisplayName,
                args.DisplayNamesJson,
                args.PropertiesJson,
                args.ResourcesJson
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateOidcScope : Reducer, IReducerArgs
        {
            [DataMember(Name = "internalId")]
            public uint InternalId;
            [DataMember(Name = "description")]
            public string? Description;
            [DataMember(Name = "descriptionsJson")]
            public string? DescriptionsJson;
            [DataMember(Name = "displayName")]
            public string? DisplayName;
            [DataMember(Name = "displayNamesJson")]
            public string? DisplayNamesJson;
            [DataMember(Name = "propertiesJson")]
            public string? PropertiesJson;
            [DataMember(Name = "resourcesJson")]
            public string? ResourcesJson;

            public UpdateOidcScope(
                uint InternalId,
                string? Description,
                string? DescriptionsJson,
                string? DisplayName,
                string? DisplayNamesJson,
                string? PropertiesJson,
                string? ResourcesJson
            )
            {
                this.InternalId = InternalId;
                this.Description = Description;
                this.DescriptionsJson = DescriptionsJson;
                this.DisplayName = DisplayName;
                this.DisplayNamesJson = DisplayNamesJson;
                this.PropertiesJson = PropertiesJson;
                this.ResourcesJson = ResourcesJson;
            }

            public UpdateOidcScope()
            {
            }

            string IReducerArgs.ReducerName => "UpdateOidcScope";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateOidcScopeFlags;
        public void UpdateOidcScope(CallReducerFlags flags) => UpdateOidcScopeFlags = flags;
    }
}
