// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateFeatureFlagHandler(ReducerEventContext ctx, string flagName, bool enabled, SpacetimeDB.Identity? actingUserId);
        public event UpdateFeatureFlagHandler? OnUpdateFeatureFlag;

        public void UpdateFeatureFlag(string flagName, bool enabled, SpacetimeDB.Identity? actingUserId)
        {
            conn.InternalCallReducer(new Reducer.UpdateFeatureFlag(flagName, enabled, actingUserId));
        }

        public bool InvokeUpdateFeatureFlag(ReducerEventContext ctx, Reducer.UpdateFeatureFlag args)
        {
            if (OnUpdateFeatureFlag == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateFeatureFlag(
                ctx,
                args.FlagName,
                args.Enabled,
                args.ActingUserId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateFeatureFlag : Reducer, IReducerArgs
        {
            [DataMember(Name = "flag_name")]
            public string FlagName;
            [DataMember(Name = "enabled")]
            public bool Enabled;
            [DataMember(Name = "acting_user_id")]
            public SpacetimeDB.Identity? ActingUserId;

            public UpdateFeatureFlag(
                string FlagName,
                bool Enabled,
                SpacetimeDB.Identity? ActingUserId
            )
            {
                this.FlagName = FlagName;
                this.Enabled = Enabled;
                this.ActingUserId = ActingUserId;
            }

            public UpdateFeatureFlag()
            {
                this.FlagName = "";
            }

            string IReducerArgs.ReducerName => "update_feature_flag";
        }
    }
}
