// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateSaleHandler(ReducerEventContext ctx, uint saleId, uint? ticketId, string? ticketSoldToUser, string? ticketSoldToUserPhone, string? saleLocation, string? saleNotes, SpacetimeDB.Identity? actingUser);
        public event UpdateSaleHandler? OnUpdateSale;

        public void UpdateSale(uint saleId, uint? ticketId, string? ticketSoldToUser, string? ticketSoldToUserPhone, string? saleLocation, string? saleNotes, SpacetimeDB.Identity? actingUser)
        {
<<<<<<< HEAD
            conn.InternalCallReducer(new Reducer.UpdateSale(saleId, ticketId, ticketSoldToUser, ticketSoldToUserPhone, saleLocation, saleNotes, actingUser), this.SetCallReducerFlags.UpdateSaleFlags);
=======
            conn.InternalCallReducer(new Reducer.UpdateSale(saleId, ticketId, ticketSoldToUser, ticketSoldToUserPhone, saleLocation, saleNotes, actingUser));
>>>>>>> maintofix
        }

        public bool InvokeUpdateSale(ReducerEventContext ctx, Reducer.UpdateSale args)
        {
<<<<<<< HEAD
            if (OnUpdateSale == null) return false;
=======
            if (OnUpdateSale == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
>>>>>>> maintofix
            OnUpdateSale(
                ctx,
                args.SaleId,
                args.TicketId,
                args.TicketSoldToUser,
                args.TicketSoldToUserPhone,
                args.SaleLocation,
                args.SaleNotes,
                args.ActingUser
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateSale : Reducer, IReducerArgs
        {
<<<<<<< HEAD
            [DataMember(Name = "saleId")]
            public uint SaleId;
            [DataMember(Name = "ticketId")]
            public uint? TicketId;
            [DataMember(Name = "ticketSoldToUser")]
            public string? TicketSoldToUser;
            [DataMember(Name = "ticketSoldToUserPhone")]
            public string? TicketSoldToUserPhone;
            [DataMember(Name = "saleLocation")]
            public string? SaleLocation;
            [DataMember(Name = "saleNotes")]
            public string? SaleNotes;
            [DataMember(Name = "actingUser")]
=======
            [DataMember(Name = "sale_id")]
            public uint SaleId;
            [DataMember(Name = "ticket_id")]
            public uint? TicketId;
            [DataMember(Name = "ticket_sold_to_user")]
            public string? TicketSoldToUser;
            [DataMember(Name = "ticket_sold_to_user_phone")]
            public string? TicketSoldToUserPhone;
            [DataMember(Name = "sale_location")]
            public string? SaleLocation;
            [DataMember(Name = "sale_notes")]
            public string? SaleNotes;
            [DataMember(Name = "acting_user")]
>>>>>>> maintofix
            public SpacetimeDB.Identity? ActingUser;

            public UpdateSale(
                uint SaleId,
                uint? TicketId,
                string? TicketSoldToUser,
                string? TicketSoldToUserPhone,
                string? SaleLocation,
                string? SaleNotes,
                SpacetimeDB.Identity? ActingUser
            )
            {
                this.SaleId = SaleId;
                this.TicketId = TicketId;
                this.TicketSoldToUser = TicketSoldToUser;
                this.TicketSoldToUserPhone = TicketSoldToUserPhone;
                this.SaleLocation = SaleLocation;
                this.SaleNotes = SaleNotes;
                this.ActingUser = ActingUser;
            }

            public UpdateSale()
            {
            }

<<<<<<< HEAD
            string IReducerArgs.ReducerName => "UpdateSale";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateSaleFlags;
        public void UpdateSale(CallReducerFlags flags) => UpdateSaleFlags = flags;
    }
=======
            string IReducerArgs.ReducerName => "update_sale";
        }
    }
>>>>>>> maintofix
}
