// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UseQrSessionHandler(ReducerEventContext ctx, string sessionId);
        public event UseQrSessionHandler? OnUseQrSession;

        public void UseQrSession(string sessionId)
        {
            conn.InternalCallReducer(new Reducer.UseQrSession(sessionId));
        }

        public bool InvokeUseQrSession(ReducerEventContext ctx, Reducer.UseQrSession args)
        {
            if (OnUseQrSession == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUseQrSession(
                ctx,
                args.SessionId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UseQrSession : Reducer, IReducerArgs
        {
            [DataMember(Name = "session_id")]
            public string SessionId;

            public UseQrSession(string SessionId)
            {
                this.SessionId = SessionId;
            }

            public UseQrSession()
            {
                this.SessionId = "";
            }

            string IReducerArgs.ReducerName => "use_qr_session";
        }
    }
}
