// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ValidateQrCodeHandler(ReducerEventContext ctx, string sessionId, string validationCode);
        public event ValidateQrCodeHandler? OnValidateQrCode;

        public void ValidateQrCode(string sessionId, string validationCode)
        {
<<<<<<< HEAD
            conn.InternalCallReducer(new Reducer.ValidateQrCode(sessionId, validationCode), this.SetCallReducerFlags.ValidateQrCodeFlags);
=======
            conn.InternalCallReducer(new Reducer.ValidateQrCode(sessionId, validationCode));
>>>>>>> maintofix
        }

        public bool InvokeValidateQrCode(ReducerEventContext ctx, Reducer.ValidateQrCode args)
        {
<<<<<<< HEAD
            if (OnValidateQrCode == null) return false;
=======
            if (OnValidateQrCode == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
>>>>>>> maintofix
            OnValidateQrCode(
                ctx,
                args.SessionId,
                args.ValidationCode
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ValidateQrCode : Reducer, IReducerArgs
        {
<<<<<<< HEAD
            [DataMember(Name = "sessionId")]
            public string SessionId;
            [DataMember(Name = "validationCode")]
=======
            [DataMember(Name = "session_id")]
            public string SessionId;
            [DataMember(Name = "validation_code")]
>>>>>>> maintofix
            public string ValidationCode;

            public ValidateQrCode(
                string SessionId,
                string ValidationCode
            )
            {
                this.SessionId = SessionId;
                this.ValidationCode = ValidationCode;
            }

            public ValidateQrCode()
            {
                this.SessionId = "";
                this.ValidationCode = "";
            }

<<<<<<< HEAD
            string IReducerArgs.ReducerName => "ValidateQRCode";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ValidateQrCodeFlags;
        public void ValidateQrCode(CallReducerFlags flags) => ValidateQrCodeFlags = flags;
    }
=======
            string IReducerArgs.ReducerName => "validate_qr_code";
        }
    }
>>>>>>> maintofix
}
